# detail_cargos_g3.py — Cargos detalhados: GO, MA, MT, MS, MG
# Chaveado por id de órgão existente em detail_data_g3.

CARGOS = {

# ── GOIÁS (Lei nº 21.792/2023 + Regimento) ──
"go": {
  "emg": [
    {"cargo": "Chefe do Estado-Maior Geral", "subordinadoA": "Comandante-Geral", "requisito": "Coronel ou Tenente-Coronel QOCBM", "desdobramentos": ["Seções BM/1 a BM/9", "Secretaria do EMG"], "atribuicoes": ["Assessorar o Comandante-Geral nos níveis mais elevados", "Realizar estudos e planejamentos coordenando atividades", "Elaborar diretrizes, legislações internas, planos e ordens"]},
    {"cargo": "Chefe da 1ª Seção (BM/1)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Assessoria às Comissões de Promoções e de Medalhas"]},
    {"cargo": "Chefe da 2ª Seção (BM/2)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Inteligência"]},
    {"cargo": "Chefe da 3ª Seção (BM/3)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Planejamento de operações e eventos"]},
    {"cargo": "Chefe da 4ª Seção (BM/4)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Planejamento, orçamento e convênios"]},
    {"cargo": "Chefe da 5ª Seção (BM/5)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Comunicação social"]},
    {"cargo": "Chefe da 6ª Seção (BM/6)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Tecnologia da informação e comunicações"]},
    {"cargo": "Chefe da 7ª Seção (BM/7)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Gestão e fiscalização de recursos"]},
    {"cargo": "Chefe da 8ª Seção (BM/8)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": ["Corpo Musical", "Guarda de Honra Especial"], "atribuicoes": ["Ações sociais, corpo musical e guarda de honra especial"]},
    {"cargo": "Chefe da 9ª Seção (BM/9)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Estatística e análise da informação"]},
  ],
  "ccd": [{"cargo": "Comandante de Correições e Disciplina", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Preservação da disciplina e hierarquia", "Apuração de infrações administrativas e penais militares"]}],
  "codec": [{"cargo": "Comandante de Operações de Defesa Civil", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Coordenar atividades de defesa civil"]}],
  "caebm": [{"cargo": "Comandante da Academia e Ensino Bombeiro Militar", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": ["Academia de Bombeiro Militar"], "atribuicoes": ["Formação, aperfeiçoamento e especialização"]}],
  "cal": [{"cargo": "Comandante de Apoio Logístico", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": ["Centro de Suprimento", "Centro de Manutenção"], "atribuicoes": ["Suprimento, material, equipamentos e viaturas"]}],
  "cgf": [{"cargo": "Comandante de Gestão e Finanças", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Gestão financeira e orçamentária"]}],
  "cat": [{"cargo": "Comandante de Atividades Técnicas", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Atividades técnicas de prevenção e análise"]}],
  "cge": [{"cargo": "Comandante de Gestão Estratégica", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Planejamento estratégico"]}],
  "cme": [{"cargo": "Comandante de Missões Especiais", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": ["BSE", "BOPAR", "BEOPP", "CIAF"], "atribuicoes": ["Operações especializadas"]}],
  "csau": [{"cargo": "Comandante de Saúde", "subordinadoA": "Subcomandante-Geral", "requisito": "Coronel QOSBM", "desdobramentos": ["Departamento de Saúde"], "atribuicoes": ["Assistência médica, farmacêutica e sanitária"]}],
  "coa": [{"cargo": "Chefe do Centro de Operações Aéreas", "subordinadoA": "Subcomandante-Geral", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Operações aéreas"]}],
  "cob": [{"cargo": "Chefe do Centro Operacional de Bombeiros", "subordinadoA": "Subcomandante-Geral", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Central de despacho operacional"]}],
  "crbm": [{"cargo": "Comandante Regional Bombeiro Militar (1º ao 9º CRBM)", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": ["Batalhões e Companhias"], "atribuicoes": ["Coordenação operacional regional"]}],
  "bbm-go": [
    {"cargo": "Comandante do Batalhão de Salvamento em Emergência (BSE)", "subordinadoA": "Comando de Missões Especiais / CRBM", "requisito": "Tenente-Coronel/Major QOCBM", "desdobramentos": ["Companhias", "Pelotões"], "atribuicoes": ["Operações de salvamento e emergência"]},
    {"cargo": "Comandante do Batalhão de Operações, Proteção Ambiental e Resposta a Desastres (BOPAR)", "subordinadoA": "Comando de Missões Especiais", "requisito": "Tenente-Coronel/Major QOCBM", "desdobramentos": [], "atribuicoes": ["Proteção ambiental e resposta a desastres"]},
    {"cargo": "Comandante do Batalhão Especializado em Operações com Produtos Perigosos (BEOPP)", "subordinadoA": "Comando de Missões Especiais", "requisito": "Tenente-Coronel/Major QOCBM", "desdobramentos": [], "atribuicoes": ["Operações com produtos perigosos"]},
  ],
},

# ── MARANHÃO (Lei nº 10.230/2015) ──
"ma": {
  "cg-ma": [
    {"cargo": "Comandante-Geral", "subordinadoA": "Governador do Estado", "requisito": "Coronel QOCBM", "desdobramentos": ["Gabinete", "Comissões", "Assessorias", "Alto-Comando"], "atribuicoes": ["Comando, administração e emprego da Corporação", "Assessorar o Governador em assuntos bombeiro-militar", "Nomeação e exoneração de oficiais em funções de comando", "Aprovação de regulamentos e planos de emprego"]},
    {"cargo": "Comandante Adjunto / Chefe do EMG", "subordinadoA": "Comandante-Geral", "requisito": "Coronel QOCBM", "desdobramentos": ["Estado-Maior Geral"], "atribuicoes": ["Orientação, coordenação e fiscalização dos órgãos", "Responsável superior pela elaboração de diretrizes do Comando"]},
  ],
  "emg-ma": [
    {"cargo": "Chefe do Estado-Maior-Geral", "subordinadoA": "Comandante Adjunto", "requisito": "Coronel QOCBM", "desdobramentos": ["Subchefe", "Seções BM/1 a BM/5"], "atribuicoes": ["Responsável pela elaboração de diretrizes e ordens do Comando", "Planejamento até aplicação dos trabalhos do EMG"]},
    {"cargo": "Subchefe do Estado-Maior-Geral", "subordinadoA": "Chefe do EMG", "requisito": "Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Substituto do Chefe do EMG; precedência funcional (exceto CG e Cmt. Adjunto)"]},
    {"cargo": "Chefe da 1ª Seção (BM/1)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Pessoal e legislação"]},
    {"cargo": "Chefe da 2ª Seção (BM/2)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Legislação técnica, pesquisa, perícias e prevenção"]},
    {"cargo": "Chefe da 3ª Seção (BM/3)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Ensino, instrução, operações, comunicações e doutrina"]},
    {"cargo": "Chefe da 4ª Seção (BM/4)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Modernização, material, armamento, estatística, suprimento e orçamento"]},
    {"cargo": "Chefe da 5ª Seção (BM/5)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": [], "atribuicoes": ["Relações públicas, ação comunitária e comunicação social"]},
  ],
  "diretoria-pessoal-ma": [{"cargo": "Diretor de Pessoal", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": ["Departamento de Recursos Humanos", "Departamento de Assistência Psicossocial"], "atribuicoes": ["Planejamento, coordenação, execução, controle e fiscalização de pessoal", "Assistência social e religiosa"]}],
  "diretoria-financas-ma": [{"cargo": "Diretor de Finanças", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": ["Departamento de Recursos Financeiros e Contábeis", "Departamento de Contratos e Convênios"], "atribuicoes": ["Sistema de administração financeira, programação, orçamento e contabilidade"]}],
  "diretoria-ensino-ma": [{"cargo": "Diretor de Ensino e Pesquisa", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": ["Academia de Bombeiro Militar", "Colégios Militares"], "atribuicoes": ["Planejamento, coordenação e fiscalização de formação, aperfeiçoamento e especialização"]}],
  "diretoria-apoio-ma": [{"cargo": "Diretor de Apoio Logístico", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": ["Centro de Suprimento e Manutenção"], "atribuicoes": ["Aquisição, coordenação e fiscalização de suprimento, material, equipamentos e viaturas"]}],
  "diretoria-tecnica-ma": [{"cargo": "Diretor de Atividades Técnicas", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": ["Departamento de Investigação e Prevenção", "Departamento de Vistorias e Pareceres"], "atribuicoes": ["Planejamento, fiscalização e controle de prevenção, vistorias e pareceres técnicos"]}],
  "diretoria-inteligencia-ma": [{"cargo": "Diretor de Inteligência", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": ["Departamento de Inteligência e Contra-Inteligência"], "atribuicoes": ["Assessoramento direto ao Comandante-Geral em inteligência"]}],
  "diretoria-planejamento-ma": [{"cargo": "Diretor de Planejamento e Modernização", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOCBM", "desdobramentos": ["Departamento de Planejamento Orçamentário", "Departamento de Tecnologia da Informação"], "atribuicoes": ["Planejamento orçamentário, gestão de projetos e tecnologia da informação"]}],
  "ajudancia-geral-ma": [{"cargo": "Ajudante-Geral", "subordinadoA": "Comandante Adjunto", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": ["Seção de Administração e Expediente", "Companhia de Guarda, Comando e Serviços", "Banda de Música"], "atribuicoes": ["Publicação de atos administrativos", "Administração e conservação de instalações físicas"]}],
  "controladoria-ma": [{"cargo": "Controlador", "subordinadoA": "Comandante Adjunto", "requisito": "Tenente-Coronel QOCBM", "desdobramentos": ["Seção de Planejamento e Controle"], "atribuicoes": ["Controle financeiro, contábil, orçamentário, patrimonial e operacional"]}],
  "cocb-ma": [{"cargo": "Comando Operacional do Corpo de Bombeiros", "subordinadoA": "Comando-Geral", "requisito": "", "desdobramentos": ["Batalhões", "Companhias Independentes", "Postos"], "atribuicoes": ["Realização das atividades-fim da Corporação por áreas territoriais"]}],
},

# ── MATO GROSSO (LC nº 775/2023 + Regimento) ──
"mt": {
  "comando-geral-mt": [
    {"cargo": "Comandante-Geral", "subordinadoA": "Governador do Estado", "requisito": "Oficial superior da ativa, do último posto do Quadro de Oficiais Combatentes (QOBM), escolhido e nomeado pelo Governador do Estado (Art. 6º)", "desdobramentos": ["Gabinete do Comandante-Geral", "Comandante-Geral Adjunto", "Conselho Superior de Bombeiros", "Órgãos de direção, apoio e execução"], "atribuicoes": [
       "A administração, o comando e o emprego da instituição são de sua competência e responsabilidade, através de diretrizes e ordens a todos os demais níveis (Art. 7º)",
       "Assessorar o Governador do Estado e o Secretário Estadual de Segurança Pública nos assuntos relacionados com as atividades bombeiro-militar (Art. 8º, I)",
       "Decidir, em grau de recurso, questões administrativas (II)",
       "Planejar e supervisionar, assessorado pelo Comandante-Geral Adjunto e demais órgãos de direção, apoio e execução, todas as atividades operacionais e administrativas do Corpo de Bombeiros Militar (III)",
       "Elaborar, aprovar e zelar pelo cumprimento dos planos de aplicação dos recursos orçamentários e financeiros da Instituição (IV)",
       "Aprovar o Regulamento Geral da instituição, após apreciação do Conselho Superior de Bombeiros (V)",
       "Aprovar o plano de emprego da instituição (VI)",
       "Baixar portarias, resoluções, instruções normativas, ordens de serviço, diretrizes e planos que promovam a eficácia da gestão administrativa e operacional da instituição, em consonância com a legislação em vigor (VII)",
       "Constituir comissões, conselhos e assessorias previstas em lei e outras necessárias ao bom desempenho da instituição (VIII)",
       "Promover, agregar, reverter e excluir as Praças e declarar os aspirantes a oficial (IX)",
       "Delegar atribuições de sua competência que não sejam vedadas por lei (X)",
       "Exercer a função de Presidente da Comissão de Promoção de Oficiais da corporação (XI)",
       "Movimentar oficiais e praças na conformidade do Regulamento de Movimentação de oficiais e praças (XII)",
       "Propor ao Governador do Estado a indicação de oficiais Bombeiros Militares para nomeação em cargos de função de confiança em âmbito interinstitucional (XIII)",
       "Desempenhar outras atribuições que lhe forem delegadas pelo Governador do Estado ou Secretário de Estado de Segurança Pública ou previstas em lei (XIV)",
       "Mandar instaurar Inquéritos Policiais Militares, Inquéritos Sanitários de Origem e Inquéritos Técnicos (XV)",
       "Determinar a abertura de Sindicância (XVI)",
       "Readaptar oficiais e praças obedecendo à decisão da perícia médica da Secretaria de Estado de Administração (XVII)",
       "Exigir de todos os integrantes do Corpo de Bombeiros Militar o estrito cumprimento do dever militar, da disciplina, da observância à hierarquia, da boa conduta social, das normas e da assistência à família (XVIII)",
       "Providenciar para que o Corpo de Bombeiros Militar esteja sempre em condições de pronto emprego (XIX)",
       "Fazer publicar ou transcrever em Boletim Geral Eletrônico (BGE) notas ou documentos referentes a atos e fatos administrativos de interesse da instituição, legitimando a publicidade e validade dos mesmos (XX)",
       "Despachar ou informar, nos prazos regulamentares, os documentos que lhes forem encaminhados (XXI)",
       "Corresponder diretamente com as autoridades civis ou militares, quando o assunto não exigir a intervenção da autoridade superior, ressalvadas as restrições regulamentares (XXII)",
       "Cumprir e fazer cumprir por todos os integrantes do Corpo de Bombeiros Militar a legislação em vigor na corporação (XXIII)",
       "Propor ao Governador do Estado criar, transformar, extinguir, denominar, localizar e estruturar os órgãos de direção superior, de apoio e de direção institucional do Corpo de Bombeiros Militar (XXIV)",
       "Promover e manter intercâmbio com as demais Secretarias de Estado, instituições civis e militares e outras organizações do Brasil e do exterior, nas áreas de interesse institucional (XXV)",
       "Traçar as diretrizes Gerais do Comando Geral e as Políticas Setoriais (XXVI)"
     ]},
  ],
  "conselho-superior-mt": [{"cargo": "Conselho Superior de Bombeiros (CSB)", "subordinadoA": "Comandante-Geral", "requisito": "Órgão consultivo", "desdobramentos": [], "atribuicoes": ["Apresentar propostas sobre matérias estratégicas", "Avaliar o emprego da instituição", "Examinar a política estadual de segurança pública", "Apreciar processos de promoção por ato de bravura"]}],
  "comando-adjunto-mt": [{"cargo": "Comandante-Geral Adjunto / Chefe do Estado-Maior-Geral", "subordinadoA": "Comandante-Geral", "requisito": "Substituto eventual do Comandante-Geral (Art. 11)", "desdobramentos": ["Estado-Maior Geral", "Gabinete do Adjunto"], "atribuicoes": [
       "Responsável pelo estudo, planejamento, direção, orientação, coordenação, fiscalização e controle de todas as atividades administrativas e operacionais da instituição, encarregado pela elaboração de diretrizes e ordens do Comando aos demais órgãos (Art. 11)",
       "Chefiar o Estado-Maior Geral da Corporação (Art. 12, I)",
       "Substituir o Comandante-Geral em seus impedimentos (II)",
       "Exercer a função de Presidente da Comissão de Promoção de Praças (III)",
       "Fiscalizar a conduta civil e militar dos oficiais e praças do Corpo de Bombeiros Militar, respeitados os princípios da disciplina, hierarquia e ética Bombeiro Militar (IV)",
       "Assinar todos os documentos referentes à vida funcional do Comandante-Geral (V)",
       "Promover e coordenar estudos estratégicos e sistêmicos sobre assuntos de ordem técnica pertinente à instituição (VI)",
       "Exercer outras atribuições que lhe forem delegadas pelo Comandante-Geral (VII)",
       "Encaminhar ao Comandante-Geral todos os documentos que dependam da decisão deste (VIII)",
       "Levar ao conhecimento do Comandante-Geral todas as ocorrências e fatos que tenham sido providenciadas por iniciativa própria (IX)",
       "Despachar ou informar, nos prazos regulamentares, os documentos que lhes forem encaminhados (X)",
       "Assegurar-se de que as instruções expedidas pelo Comandante-Geral estejam sendo cumpridas de acordo com os objetivos da Corporação (XII)",
       "Conferir com os originais e mandar publicar os documentos cabíveis no Boletim Geral Eletrônico (BGE) (XIII)",
       "Apresentar ao Comandante-Geral o Relatório Anual das Atividades do CBMMT, bem como os periódicos necessários nas épocas previstas pelas diretrizes em vigor (XIV)"
     ]}],
  "corregedoria-mt": [{"cargo": "Corregedor-Geral", "subordinadoA": "Comandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": ["Seção Administrativa", "Seção de Polícia Judiciária Militar", "Seção de Procedimentos Administrativos Disciplinares"], "atribuicoes": ["Preservação da disciplina, hierarquia e ética", "Apuração de infrações administrativas e penais militares", "Realizar visitas de inspeção; elaborar mapas disciplinares mensais"]}],
  "emg-mt": [
    {"cargo": "Coordenador de Gestão de Pessoas (BM/1)", "subordinadoA": "Comandante Adjunto", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Gestão de pessoas e recursos humanos"]},
    {"cargo": "Coordenador de Assistência Social (BM/2)", "subordinadoA": "Comandante Adjunto", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Assistência social corporativa"]},
    {"cargo": "Coordenador de Articulação e Integração Comunitária (BM/3)", "subordinadoA": "Comandante Adjunto", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Articulação e integração comunitária"]},
    {"cargo": "Coordenador de Logística e Patrimônio (BM/4)", "subordinadoA": "Comandante Adjunto", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Logística e patrimônio"]},
    {"cargo": "Coordenador de Comunicação Social (BM/5)", "subordinadoA": "Comandante Adjunto", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Comunicação social"]},
    {"cargo": "Coordenador de Planejamento, Orçamento e Gestão de Projetos (BM/6)", "subordinadoA": "Comandante Adjunto", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Planejamento, orçamento e gestão de projetos"]},
    {"cargo": "Coordenador de Tecnologia da Informação (BM/7)", "subordinadoA": "Comandante Adjunto", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Tecnologia da informação"]},
    {"cargo": "Coordenador de Legislação e Doutrinas (BM/8)", "subordinadoA": "Comandante Adjunto", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Legislação e doutrinas"]},
    {"cargo": "Coordenador de Finanças (BM/9)", "subordinadoA": "Comandante Adjunto", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Administração financeira"]},
    {"cargo": "Coordenador de Ajudância Geral (BM/10)", "subordinadoA": "Comandante Adjunto", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Ajudância geral corporativa"]},
  ],
  "diretoria-administracao-mt": [{"cargo": "Diretor de Administração Institucional", "subordinadoA": "Comandante Adjunto", "requisito": "Coronel QOBM", "desdobramentos": ["Seção Administrativa", "Seção de Finanças", "Seção Logística e Patrimônio", "Seção de TI e Comunicação", "Seção de Engenharia"], "atribuicoes": ["Administração institucional sistêmica"]}],
  "diretoria-ensino-mt": [{"cargo": "Diretor de Ensino, Instrução e Pesquisa", "subordinadoA": "Comandante Adjunto", "requisito": "Coronel QOBM", "desdobramentos": ["Escola Superior de Bombeiros", "Academia de Bombeiros Militar", "Escola de Formação de Praças"], "atribuicoes": ["Planejamento, coordenação e controle de formação e especialização"]}],
  "diretoria-seguranca-mt": [{"cargo": "Diretor de Segurança Contra Incêndio e Pânico", "subordinadoA": "Nível de Execução", "requisito": "Coronel QOBM", "desdobramentos": ["Coord. de Estudos e Análise de Processos", "Coord. de Fiscalização", "Coord. de Legislação e Pareceres", "Coord. de Perícia Técnica", "Coord. de Hidrantes"], "atribuicoes": ["Atividades de prevenção contra incêndio e pânico"]}],
  "diretoria-operacional-mt": [{"cargo": "Diretor Operacional", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOBM", "desdobramentos": ["Coordenadoria de Planejamento Operacional e Estatística", "Coordenadoria de Atendimento Pré-Hospitalar", "Comandos Regionais BM", "Batalhão de Emergências Ambientais"], "atribuicoes": ["Operações bombeiro-militar e coordenação de unidades operacionais"]}],
  "bea-mt": [{"cargo": "Comandante do Batalhão de Emergências Ambientais (BEA)", "subordinadoA": "Diretoria Operacional", "requisito": "", "desdobramentos": ["CPP", "CBS", "CPCIF", "GAvBM"], "atribuicoes": ["Emergências ambientais, produtos perigosos, busca e salvamento e incêndio florestal"]}],
  "gabinete-cg-mt": [{"cargo": "Chefe de Gabinete do Comandante-Geral", "subordinadoA": "Comando-Geral", "requisito": "", "desdobramentos": ["Secretaria do Gabinete", "Ajudante-de-ordens", "Agência Central de Inteligência", "Centro de Comunicação Social BM"], "atribuicoes": ["Apoio e assessoramento direto ao Comandante-Geral"]}],
},

# ── MATO GROSSO DO SUL (LC nº 188/2014) ──
"ms": {
  "comando-geral-ms": [{"cargo": "Comandante-Geral", "subordinadoA": "Governador do Estado", "requisito": "Coronel QOBM (último posto)", "desdobramentos": ["Gabinete", "Comissões", "Assessorias"], "atribuicoes": ["Responsável superior pelo comando, administração e emprego", "Dirigir atividades técnicas, operacionais e administrativas", "Baixar portarias, diretrizes, planos e ordens", "Presidir a Comissão de Promoção de Oficiais", "Nomear e exonerar oficiais em funções de comando"]}],
  "subcomando-geral-ms": [{"cargo": "Subcomandante-Geral", "subordinadoA": "Comandante-Geral", "requisito": "Coronel QOBM (penúltimo posto)", "desdobramentos": ["Gabinete do Subcomandante", "Diretorias"], "atribuicoes": ["Auxiliar diretamente o Comandante-Geral", "Zelar pela disciplina, hierarquia e ética", "Presidir a Comissão de Promoção de Praças", "Exercer função de coordenador operacional"]}],
  "emg-ms": [
    {"cargo": "Chefe do Estado-Maior-Geral", "subordinadoA": "Subcomandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": ["Seções BM-1 a BM-7"], "atribuicoes": ["Assessor direto do Comandante-Geral", "Dirigir, orientar, coordenar e fiscalizar o trabalho do EMG"]},
    {"cargo": "Chefe da 1ª Seção (BM-1)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Pessoal e legislação"]},
    {"cargo": "Chefe da 2ª Seção (BM-2)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Inteligência"]},
    {"cargo": "Chefe da 3ª Seção (BM-3)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Instrução, operação, ensino, estatística e meio ambiente"]},
    {"cargo": "Chefe da 4ª Seção (BM-4)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Logística, patrimônio e informática"]},
    {"cargo": "Chefe da 5ª Seção (BM-5)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Comunicação social"]},
    {"cargo": "Chefe da 6ª Seção (BM-6)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Planejamento administrativo, orçamentário e financeiro"]},
    {"cargo": "Chefe da 7ª Seção (BM-7)", "subordinadoA": "Chefe do EMG", "requisito": "Tenente-Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Proteção contra incêndio, pânico e outros riscos"]},
  ],
  "corregedoria-ms": [{"cargo": "Corregedor", "subordinadoA": "Comandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": ["Gabinete do Corregedor", "Cartório", "Seção de Justiça e Disciplina", "Conselho Permanente de Disciplina", "Ouvidoria", "Seção de Inteligência", "Patrulha Disciplinar Ostensiva"], "atribuicoes": ["Preservação da disciplina, hierarquia e ética", "Apuração de fatos envolvendo responsabilidade penal, administrativa e disciplinar", "Poder disciplinar e polícia judiciária militar"]}],
  "diretoria-pessoal-ms": [{"cargo": "Diretor de Pessoal", "subordinadoA": "Subcomandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": ["Subdiretor", "Chefes de Seção"], "atribuicoes": ["Planejamento, orientação normativa e coordenação de gestão de pessoal"]}],
  "diretoria-apoio-ms": [{"cargo": "Diretor de Apoio Logístico", "subordinadoA": "Subcomandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": ["Centro de Suprimento e Manutenção"], "atribuicoes": ["Gestão de material, patrimônio e informática"]}],
  "diretoria-financas-ms": [{"cargo": "Diretor de Finanças", "subordinadoA": "Subcomandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Gestão financeira, orçamentária, contabilidade e auditoria"]}],
  "diretoria-atividades-tecnicas-ms": [{"cargo": "Diretor de Atividades Técnicas", "subordinadoA": "Subcomandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Normatização, estudo, análise e planejamento de atividades preventivas e de segurança contra incêndio"]}],
  "deipe-ms": [{"cargo": "Diretor de Ensino, Instrução, Pesquisa e Educação", "subordinadoA": "Subcomandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": ["Academia de Bombeiros Militar", "Escolas Militares"], "atribuicoes": ["Administração do ensino, instrução, pesquisa e educação bombeiro-militar"]}],
  "diretoria-saude-ms": [{"cargo": "Diretor de Saúde", "subordinadoA": "Subcomandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Atividades de saúde e atendimento pré-hospitalar"]}],
  "diretoria-telematica-ms": [{"cargo": "Diretor de Telemática e Estatística", "subordinadoA": "Subcomandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Sistemas de tecnologia da informação e estatística"]}],
  "diretoria-ambiental-ms": [{"cargo": "Diretor de Proteção Ambiental", "subordinadoA": "Subcomandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Planejamento e execução de atividades de proteção ambiental"]}],
  "diretoria-inteligencia-ms": [{"cargo": "Diretor de Inteligência", "subordinadoA": "Subcomandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Sistema de gestão de inteligência; controle de material bélico"]}],
  "cmb-ms": [{"cargo": "Comandante Metropolitano de Bombeiros (CMB)", "subordinadoA": "Subcomandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": ["CBDiv", "CBFron", "CBEsp", "COCB"], "atribuicoes": ["Planejamento, coordenação e fiscalização de atividades operacionais e prevenção na capital"]}],
},

# ── MINAS GERAIS (LC nº 54/1999) ──
"mg": {
  "comando-geral-mg": [{"cargo": "Comandante-Geral", "subordinadoA": "Governador do Estado", "requisito": "Coronel QOBM (último posto)", "desdobramentos": ["Gabinete", "Auditoria"], "atribuicoes": ["Responsável pelo comando e administração geral", "Prerrogativas de Secretário de Estado", "Precedência hierárquica e funcional sobre todos os Oficiais", "Presidir a Comissão de Promoção de Oficiais"]}],
  "estado-maior-mg": [
    {"cargo": "Chefe do Estado-Maior (Subcomandante)", "subordinadoA": "Comandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": ["Subchefia", "Seções do Estado-Maior"], "atribuicoes": ["Subcomandante da Corporação; substituto eventual do Comandante-Geral", "Dirigir, orientar, coordenar e fiscalizar os trabalhos do Estado-Maior"]},
    {"cargo": "Subchefe do Estado-Maior", "subordinadoA": "Chefe do Estado-Maior", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Substituto eventual do Chefe do Estado-Maior; prerrogativas de Secretário Adjunto"]},
  ],
  "diretorias-mg": [{"cargo": "Diretor", "subordinadoA": "Comandante-Geral", "requisito": "Coronel QOBM", "desdobramentos": ["Diretoria de Recursos Humanos", "Diretoria de Apoio Logístico", "Diretoria de Contabilidade e Finanças"], "atribuicoes": ["Gestão de pessoal, orçamentária, financeira, contabilidade, auditoria e apoio logístico"]}],
  "comandos-operacionais-mg": [{"cargo": "Comandante Operacional de Bombeiros (COB)", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOBM", "desdobramentos": ["Batalhões", "Companhias Independentes"], "atribuicoes": ["Coordenação de atividades operacionais em sua área (sedes de RISP)"]}],
  "academia-mg": [{"cargo": "Diretor da Academia de Bombeiros Militar", "subordinadoA": "Comando-Geral", "requisito": "Coronel QOBM", "desdobramentos": [], "atribuicoes": ["Formação, aperfeiçoamento e especialização de Bombeiros"]}],
  "csm-mg": [{"cargo": "Chefe do Centro de Suprimento e Manutenção", "subordinadoA": "Diretoria de Apoio Logístico", "requisito": "", "desdobramentos": [], "atribuicoes": ["Suprimento logístico e manutenção de viaturas e equipamentos"]}],
  "cat-mg": [{"cargo": "Diretor do Centro de Atividades Técnicas", "subordinadoA": "Comando-Geral", "requisito": "", "desdobramentos": [], "atribuicoes": ["Pesquisa, análise, normatização e fiscalização", "Perícias de incêndio; 2ª instância em análise de projetos de prevenção"]}],
  "ajudancia-mg": [{"cargo": "Ajudante-Geral", "subordinadoA": "Comando-Geral", "requisito": "", "desdobramentos": ["Secretaria", "Protocolo", "Segurança do Quartel"], "atribuicoes": ["Funções administrativas do Comando-Geral; secretaria, protocolo e arquivo", "Apoio ao quartel em pessoal e material"]}],
  "execucao-mg": [
    {"cargo": "Comandante de Batalhão (BBM)", "subordinadoA": "Comando Operacional de Bombeiros", "requisito": "Tenente-Coronel QOBM", "desdobramentos": ["Companhias", "Pelotões"], "atribuicoes": ["Ações de prevenção e combate a incêndio, busca e salvamento"]},
    {"cargo": "Comandante de Companhia Independente (CIA IND BM)", "subordinadoA": "Comando Operacional de Bombeiros", "requisito": "Major ou Capitão QOBM", "desdobramentos": ["Pelotões"], "atribuicoes": ["Ações de prevenção e combate a incêndio"]},
    {"cargo": "Comandante de Pelotão (PEL BM)", "subordinadoA": "Companhia", "requisito": "1º ou 2º Tenente QOBM", "desdobramentos": [], "atribuicoes": ["Comando de pelotão operacional"]},
  ],
},

}
