# GERADO por scripts/extrair_regulamentos.py — NÃO editar à mão.
# Fonte: Pará - Regimento Interno.md (extração determinística; mapa nos de-paras).
ENRICHMENT = {
    ('competencias-apoio-assessoramento', 'pa'): [
        {
            'heading': 'TÍT. I, Cap. V — Coordenadoria Estadual de Proteção e Defesa Civil',
            'caput': 'Art.32. A Coordenadoria Estadual de Proteção e Defesa Civil do Pará (CEDEC), órgão de direção-geral, é o órgão central e coordenador do Sistema Estadual de Proteção e Defesa Civil (SEPDEC) tem a missão de contribuir para proteção da vida, patrimônio e meio ambien te, atendendo a população no território paraense, em situação de emergência ou calamidade pública, desencadeadas por fatores anormais e adversos, bem como limitar riscos e perdas para a comunidade, com a finalidade de preservar e restabelecer a normalidade da vida comunitária.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 32',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. V — Coordenadoria Estadual de Proteção e Defesa Civil',
            'caput': 'Art.33. Compete à Coordenadoria Estadual de Proteção e Defesa Civil do Pará (CEDEC):',
            'dispositivos': ['I – integrar, planejar, organizar, coordenar e supervisionar a execução das medidas preventivas de socorro assistenciais e de recuperação, considerando os efeitos produzidos por fatos adversos de qualquer natureza e nas situações de emergência ou de calamidade pública;', 'II – preservar a moral da população e o restabelecimento da normalidade da vida comunitária em todo o território do Estado do Pará;', 'III – elaborar o Plano Estadual de Proteção e Defesa Civil, e suas diretrizes;', 'IV – celebrar e executar convênios com a União e com os municípios do Estado;', 'V – desenvolver programas, projetos e atividades de defesa civil nas fases de normalidade ou anormalidade, voltados para prevenção, preparação e resposta;', 'VI – fazer mobilização entre os órgãos governamentais e não governamentais; e', 'VII – fomentar a proteção e defesa civil nos municípios do Estado.', 'Parágrafo único. As competências dos órgãos, atribuições dos membros e o funcionamento da Coordenadoria Estadual de Proteção e Defesa Civil do Pará obedecerá às normas estabelecidas em Regimento Interno próprio.'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 33',
            'match': 'exata',
        },
    ],
    ('competencias-direcao', 'pa'): [
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.5º O Comando-Geral do Corpo de Bombeiros Militar do Pará (CBMPA) é constituído pelos órgãos de direção-geral, realiza o comando, a gestão, o planejamento estratégico e a correição, visand o a organização e o emprego da Corporação para o cumprimento de suas missões, acionando, por meio de diretrizes e ordens, os órgãos de direção intermediária ou setorial, de apoio e de execução, supervisionando, coordenando, controlando e fiscalizando a atuação desses órgãos.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 5',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.6º Compete ao Comando-Geral, órgão de assessoramento ao Comandante-Geral:',
            'dispositivos': ['I – assessorar o Comandante-Geral na adoção de decisões técnicas e administrativas;', 'II – auxiliar o Comandante-Geral na elaboração e cumprimento do plano de comando; e', 'III – acompanhar os programas, projetos e atividades da Corporação, mantendo o Comandante -Geral informado sobre o andamento das ações.'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 6',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.7º Ao Comandante-Geral, na condição de responsável pela administração, comando e emprego da Corporação, sem prejuízo a outras atribuições previstas na legislação, cabem as seguintes atribuições:',
            'dispositivos': ['I – comandar, gerir, empregar, supervisionar e coordenar d e forma geral as atividades da Corporação, assessorado pelos órgãos de direção, apoio e de execução;', 'II – presidir o Alto Comando do Corpo de Bombeiros Militar do Pará (CBMPA), a Comissão de Promoção de Oficiais e o Conselho do Mérito Bombeiro Militar;', 'III – encaminhar ao órgão competente, o projeto de orçamento anual referente ao Corpo de Bombeiros Militar do Pará (CBMPA) e participar, no que couber, da elaboração do Plano Plurianual;', 'IV – celebrar convênios e contratos de interesse do Corpo de Bombeiros Militar do Pará (CBMPA) com entidades de direito público ou privado, nos termos da lei;', 'V – nomear e exonerar bombeiros militares no exercício das funções de direção, comando e assessoramento, nos termos desta Lei;', 'VI – autorizar bombeiros militares e servidores civis da Corporação a se afastarem do Estado;', 'VII – ordenar o emprego de verbas orçamentárias ou de créditos abertos em favor do Corpo de Bombeiros Militar do Pará (CBMPA) e de outros recursos que este venha a receber, oriundos de quaisquer fontes de 5 receitas;', 'VIII – expedir os atos necessários para a administração do Corpo de Bombeiros M ilitar do Pará (CBMPA);', 'IX – incorporar praças e praças especiais;', 'X – promover praças e declarar aspirantes-a-oficial;', 'XI – conceder férias, licenças ou afastamentos de qualquer natureza;', 'XII – instaurar e solucionar procedimentos e processos administrativos, disciplinares ou não, aplicando as penalidades previstas na legislação vigente;', 'XIII – criar, desenvolver e gerenciar programas de prevenção e proteção nas atividades bombeiro militar que visem à melhoria da qualidade de vida do cidadão;', 'XIV – certificar o atendimento do direito ao porte de arma de seus militares, bem como as hipóteses excepcionais de suspensão e cassação de porte de arma; e', 'XV – encaminhar ao Chefe do Poder Executivo a lista de promoção dos oficiais, nos termos da lei que estabelece as regras de promoção.', '§1º O Comandante-Geral poderá delegar competência para a expedição de atos administrativos, visando à agilização da gestão da Corporação.', '§2º Nos impedimentos ou ausências do Comandante-Geral, responderá pelo Comando-Geral o Chefe do Estado-Maior Geral e, no impedimento ou ausência deste, seguirá a seguinte ordem de prioridade: o Coordenador-Adjunto Estadual de Proteção e Defes a Civil, o Corregedor -Geral, o Comandante Operacional e o Chefe do Departamento-Geral mais antigo.', '§3º Para efeito do previsto no § 2º deste artigo não será considerado o oficial que estiver respondendo pela função.', '§4º O Comandante-Geral nomeado deverá apresentar, em até 60 (ses senta) dias úteis da posse, plano de comando com metas, indicadores, prestação de contas e participação da sociedade, ajustado aos planos estratégicos da instituição, que contenham:', 'I – metas qualitativas e quantitativas de produtividade e de maior proteção à população;', 'II – diagnóstico da necessidade de recursos humanos e materiais e medi das de otimização e de busca da eficiência;', 'III – programas de capacitação do efetivo;', 'IV – planejamento das ações específicas direcionadas ao melhor exercício das atribuições do órgão; e', 'V – previsão de criação ou extinção de unidades bombeiros militares e de estrutura organizacional.'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 7',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.8º O Alto Comando do CBMPA é o órgão colegiado de direção -geral, com atribuições deliberativas e consultivas destinado a:',
            'dispositivos': ['I – em caráter consultivo, manifestar-se sobre:', 'a) orçamento anual do CBMPA; e', 'b) outros assuntos de interesse da Corporação.', 'II – em caráter deliberativo, manifestar-se sobre:', 'a) elaboração de reforma ou projeto de lei que envolva o CBMPA;', 'b) expedição de atos normativos provenientes de suas deliberações;', 'c) propostas referentes ao aumento de efetivo e criação, e extinção de cargos, a serem encaminhadas ao Governo do Estado;', 'd) conflitos de atribuições entre órgãos de direção, de apoio e de execução; e', 'e) proposta referente à remuneração, a ser encaminhada ao Chefe do Poder Executivo Estadual. 6'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 8',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.9º O Alto Comando do CBMPA tem como presidente o C omandante Geral, dele participando oficiais da Corporação como membros natos e efetivos:',
            'dispositivos': ['I – Membros natos:', 'a) Chefe do Estado Maior Geral;', 'b) Coordenador Adjunto Estadual de Proteção e Defesa Civil;', 'c) Corregedor-Geral;', 'd) Comandante Operacional;', 'e) Chefe do Departamento Geral de Administração;', 'f) Chefe do Departamento Geral de Pessoal;', 'g) Chefe do Departamento Geral de Cultura, Educação e Pesquisa; e', 'h) Chefe do Departamento Geral de Segurança contra incêndios e Emergências.', 'II – membros efetivos: 3 (três) oficiais do último posto da Corporação designados pelo Comandante Geral, podendo ser reconduzidos, individualmente.', '§1º O Secretário do Alto Comando será um dos membros efetivos designado pelo Presidente do alto comando do CBMPA.', '§2º Comparecerá às reuniões do Alto Comando, como assessor direto do Comandante Geral, o seu Chefe de Gabinete.', '§3º As competências dos membros e o funcionamento do Alto Comando obedecerá às normas estabelecidas em Regimento Interno próprio. Da Secretaria'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 9',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.10. Compete à secretaria dos Órgãos de Direção Geral:',
            'dispositivos': ['I – organizar, protocolar, distribuir e acompanhar a tramitação dos documentos oficiais e processos administrativos do setor, utilizando os sistemas corporativos (PAE/SIGA ou equivalentes);', 'II – produzir expedientes endereçados a autoridades internas e externas, na área de sua competência;', 'III – elaborar memorandos, ofícios, despachos, informações, certidões, minutas e outros documentos necessários à instrução processual;', 'IV – receber, controlar, protocolar, tramitar, dar baixa, juntar e arquivar documentos e processos administrativos atinentes ao setor;', 'V – realizar o controle de prazo dos processos que estejam na carga do setor;', 'VI – acompanhar publicações em Boletim Geral, Boletim de Acesso Restrito, Diário Oficial relacioanadas ao setor e adotar as medidas administrativas necessárias;', 'VII – programar e controlar os afastamentos e as informações funcionais dos militares lotados no setor ou à disposição;', 'VIII – confeccionar e controlar as escalas de serviço interno e de representação de oficiais e praças do setor;', 'IX – controlar os serviços de patrimônio, almoxarifado, manutenção e transporte do setor;', 'X – promover estudos e análises com vistas ao aprimoramento da gestão de suas atividades;', 'XI – repassar a assessoria de comunicação, quando necessário, release e informações relacionada ao setor; e', 'XII – coordenar o atendimento ao público, controlando a agenda de audiências e reuniões. 7'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 10',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.11. Compete a o Estado-Maior Geral, órgão de direção -geral, subordinado diretamente ao Comandante-Geral:',
            'dispositivos': ['I – propor políticas e diretrizes voltadas ao cumprimento da missão institucional;', 'II – elaborar, coordenar e atualizar o planejamento estratégico e os planos de ação da Corporação;', 'III – propor medidas de aperfeiçoamento dos processos de sua área de atuação, inclusive no tocante à inovação, digitalização e sustentabilidade;', 'IV – orientar quanto ao preparo e o emprego da Corporação, a organização, a direção e pelo controle das atividades da Corporação;', 'V – elaborar diretrizes e ordens de comando em consonância com a missão institucional e a política de segurança pública do Estado;', 'VI – acompanhar o cumprimento das ordens e planos emanados do Comando-Geral; e', 'VII – fornecer ao Comandante-Geral subsídios técnicos e estratégicos para decisões complexas. Da Organização'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 11',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.12. O Estado-Maior Geral - EMG possui a seguinte estrutura:',
            'dispositivos': ['I – Chefe do Estado Maior Geral;', 'II – Subchefe do Estado Maior Geral;', 'III – Seções do Estado Maior:', 'a) 1ª Seção (BM/1): Política e Planejamento de Pessoal e Legislação;', 'b) 2ª Seção (BM/2): Política e Planejamento de Gestão do Conhecimento, Cultura e Inovação;', 'c) 3ª Seção (BM/3): Política e Planejamento de Operações, Doutrina e Estatística;', 'd) 4ª Seção (BM/4): Política e Planejamento de Logística;', 'e) 5ª Seção (BM/5): Gestão pela Qualidade; e', 'f) 6ª Seção (BM/6): Planejamento e Orçamento Institucional.', 'IV – Escritório de Projetos;', 'V – Ajudância de Ordens; e', 'VI – Secretaria. Das Competências Orgânicas Da 1ª Seção do Estado Maior Geral'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 12',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.13. A 1ª Seção do Estado Maior Geral (BM/1) é o órgão de assessoramento ao Chefe do Estado-Maior Geral nos assuntos relacionados ao efetivo militar e civil da Corporação, seu ingresso, ciclos e carreira profissional, controle de quadros e estatísticas de efetivo, bem como de planejamentos e legisla ções da Corporação.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 13',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.14. Compete à 1ª Seção do Estado Maior Geral:',
            'dispositivos': ['I – elaborar planos e ordens inerentes à política de pessoal da Corporação;', 'II – realizar estudo da política de efetivos, incluindo planejamento dos quadros de organização e distribuição da Corporação;', 'III – definir prioridades para distribuição de efetivos, por criticidade e necessidade;', 'IV – analisar o estado de saúde mental , suas c ausas, possíveis doenças do trabalho e sugestões de 8 medidas;', 'V – normatizar sobre inclusão, seleção e movimentações de militares da ativa e militares convocados;', 'VI – normatizar sobre inclusão e processo de seleção de civis empregados em atividades de competência da Corporação;', 'VII – realizar estudo das necessidades de formação e aperfeiçoamento no tocante a ascenção funcional do efetivo;', 'VIII – realizar estudo da necessidade de concurso público para ingressos de novos bombeiros militares;', 'IX – elaborar diretrizes sobre férias, afastamentos, licenças e movimentação de pessoal;', 'X – assessorar o Comandante-Geral em revisões e atualizações legislativas;', 'XI – redigir, revisar e consolidar proposições normativas internas (regulamentos, portarias, re soluções, ordens de serviço) e demais atos administrativos da Corporação;', 'XII – produzir material explicativo e orientações internas sobre normativos aplicáveis;', 'XIII – manter repositório organizado e atualizado de atos normativos da Corporação, assegurando controle de versões e histórico de alterações; e', 'XIV – propor ajustes em normas internas para adequação à legislação federal, estadual, decisões judiciais e administrativas aplicáveis.', 'Parágrafo único. A BM/1 é composta por 02(duas) subseções:', 'I – Subseção de Estudos Estratégicos de Pessoal - SEEP; e', 'II – Subseção de Estudos Estratégicos de Legislação - SEEL. 2ª Seção do Estado Maior Geral'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 14',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.15. A 2ª Seção do Estado Maior Geral (BM/2) é o órgão do Estado Maior Geral que atua no desenvolvimento de ações a fim de garantir a continuidade e a qualidade de todos os processos praticados pela Corporação em assuntos relativos à gestão de conhecimento, cultura e inovação.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 15',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.16. Compete à 2ª Seção do Estado Maior Geral:',
            'dispositivos': ['I – realizar estudos e formular propostas de necessidade de conhecimento s sobre os diversos domínios de interesse do Corpo de Bombeiros Militar e de Defesa Civil relacionados com o futuro da Corporação;', 'II – elaborar mapeamento por competências necessárias a todas as funções dos órgãos e setores da Corporação;', 'III – identificar, avaliar e documentar as habilidades, competências e conhecimentos dos militares e civis da Corporação;', 'IV – criar indicadores de desempenho para mensuração das habilidades pessoais e profissionais militares;', 'V – elaborar políticas e diretrizes para:', 'a) a pesquisa, produção, avaliação, divulgação e consolidação do conhecimento na Corporação;', 'b) a preservação e governança do patrimônio histórico e cultural do CBMPA; e', 'c) implantação de projetos de boas práticas isoladas, avaliá -los durante a maturação e evoluí -los em padrões em toda a Corporação.', 'VI – propor políticas e diretrizes para planejar, elaborar, orientar, gerenciar e consolidar a execução dos Planos de Gestão do Conhecimento, Cultura e Inovação;', 'VII – propor e coordenar projetos de inovação tecnológica e metodológica nas áreas administrativa, prevencionista e operacional;', 'VIII – pesquisar e avaliar novas tecnologias aplicáveis à atividade bombeiro -militar (equipamentos, softwares, aplicativos e métodos operacionais);', 'IX – elaborar relatórios referentes à política da gestão de gestão do conhecimento, cultura e inovação da Corporação; e', 'X – estimular a sistematização e a aplicação do conhecimento obtido de intercâmbios institucionais. 9', 'Parágrafo único. A BM/2 é composta por 02 (duas) subseções:', 'I – Subseção de pesquisa, análise de dados e boas práticas em Gestão do Conhecimento - SPBG; e', 'II – Subseção de tecnologia, cultura e inovação - STCI. 3ª Seção do Estado Maior Geral'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 16',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.17. A 3ª Seção do Estado Maior Geral (BM/3) é o órgão do Estado Maior Geral responsável pelo assessoramento ao Comandante -Geral nos assuntos pertinentes à organização, operação, doutrina e estatísticas de ocorrência.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 17',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.18. Compete à 3ª Seção do Estado Maior Geral:',
            'dispositivos': ['I – analisar cenários e identificar riscos para o dimensionamento do efetivo e dos recursos operacionais;', 'II – planejar o atendimento às operações e eventos institucionais, emitindo as respectivas Notas de Serviço, para execução por parte dos setores pertinentes;', 'III – estabelecer e atualizar o Plano de Emprego Operacional do Corpo de Bombeiros Militar;', 'IV – definir o planejamento anual de simulados operacionais envolvendo o Comando de Operações Comandos Regionais Intermediários e Unidades Bombeiro Militar;', 'V – planejar a participação da Corporação em exercícios e simulações operacionais conjuntas;', 'VI – representar o CBMPA em operações ou ações integradas com outros órgãos ou coirmãs;', 'VII – estabelecer e atualizar o Plano de Emprego Operacional do Corpo de Bombeiros Militar;', 'VIII – orientar e supervisionar as atividades operacionais durante as operações e eventos;', 'IX – realizar estudos avaliativos sobre o nível de resposta operacional da instituição e planejamento de instruções para a manutenção e adestramento operacional da tropa e seu pronto emprego;', 'X – realizar estudos do emprego de técnicas e táticas nas operações bombeiro militar;', 'XI – estabelecer a doutrina operacional institucional, traduzindo-a em manuais, normas, protocolos e procedimentos padrões a serem adotados no CBMPA;', 'XII – definir diretrizes operacionais para resposta a emergências, desastres, g randes eventos e mobilizações;', 'XIII – monitorar indicadores de desempenho operacional;', 'XIV – emitir relatório sobre desempenho operacional das Unidades;', 'XV – coletar, analisar e divulgar dados estatísticos das ocorrências operacionais;', 'XVI – realizar estudos e formular propostas de necessidade de ensino e instrução anual da Corporação;', 'XVII – avaliar o desempenho operacional das Unidades após grandes ocorrências e operações;', 'XVIII – definir e elaborar o calendário anual dos grandes eventos e operações que envolvam a Corporação (Calendário de Atividades Institucionais-CAI) e monitorar e avaliar a efetividade do mesmo; e', 'XIX – elaborar relatórios referentes à política de organização, operação, doutrina e estatísticas de ocorrência da Corporação.', 'Parágrafo único. A BM/3, é composta por 02 (duas) subseções:', 'I – Subseção de Operações e Grandes Eventos - SOGE; e', 'II – Subseção de Estudos Estratégicos de Doutrina e Estatística - SEED. 4ª Seção do Estado Maior Geral'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 18',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.19. A 4ª Seção do Estado Maior Geral (BM/4) é o órgão de controle e assessoramento do Comandante Geral no tocante aos recursos logísticos utilizados no âmbito institucional, a mobilização, a aquisição e emprego destes nas missões da Corporação.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 19',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.20. Compete a 4ª Seção do Estado Maior: 10',
            'dispositivos': ['I – elaborar diagnóstico logístico da Corporação;', 'II – promover estudos das necessidades da Corporação em apoio logístico e patrimonial;', 'III – participar e contribuir no planejamento de compras e contratações anuais;', 'IV – acompanhar a execução do plano estratégico relacionados à logística da Corporação;', 'V – elaborar portfólio de materiais e equipamentos operacionais da Corporação;', 'VI – manter atualizad o o banco de especificações de materiais e equipamentos operacionais da Corporação;', 'VII – controlar e supervisionar as atividades de logística e patrimônio na Corporação;', 'VIII – elaborar diretrizes que visem à padronização, controle e orientação quanto a aquisição e uso de viaturas, embarcações, instalações, materiais e equipamentos sob responsabilidade da Corporação;', 'IX – elaborar diretrizes de manutenção preventiva das viaturas, embarcações e equipamentos em carga e sob responsabilidade da Corporação;', 'X – elaborar diretrizes de manutenção predial e conservação geral das unidades administrativas e operacionais da Corporação;', 'XI – definir a identidade visual da Corporação mantendo atualizada a padronização de bens logísticos e patrimoniais, tais como uniformes, viaturas e fachadas de quarteis;', 'XII – contribuir com estudos em nível estadual para distribuição de materiais, equipamentos e viaturas;', 'XIII – gerenciar sistema de Gestão de Demandas do CBMPA (GEDEM); e', 'XVII – elaborar relatórios das necessidades de recursos materiais e logísticos da Corporação.', 'Parágrafo único. A BM/4 é composta por 02 (duas) subseções:', 'I – Subseção de Planejamento logístico - SPL; e', 'II – Subseção de Análise e Controle - SAC. 5ª Seção do Estado Maior Geral'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 20',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.21. A 5ª Seção do Estado Maior Geral (BM/5) é o órgão do Estado Maior Geral que atua na implementação e manutenção de práticas de qualidade organizacional.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 21',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.22. Compete à 5ª Seção do Estado Maior Geral:',
            'dispositivos': ['I – criar e implementar procedimentos, fluxos e rotinas que garantem consistência, eficiência e segurança na execução dos serviços administrativos e operacionais;', 'II – gerenciar não conformidades e ações corretivas de procedimentos operacionais e administrativos padrão, utilizando o PANCO (Procedimento de Análise de Não Conduta Operacional), investigando suas causas e implementando ações corretivas e preventivas;', 'III – aplicar o ciclo do PDCA (Plan - Do-Check-Act) para avaliar a eficiência dos processos, propor correções e promover ajustes periódicos;', 'IV – elaborar planos de ações baseadas nas normas ISO 9001, ISO 14001 e ISO 45001 com objetivos claros e indicadores para monitoramento relacionados à gestão da qualidade, ao meio ambiente e à segurança no trabalho respectivamente;', 'V – estimular o compromisso de todas as áreas da Corporação no cumprimento da política de qualidade e na cultura de melhoria contínua;', 'VI – elaborar relatórios referentes à política da gestão pela qualidade na Corporação;', 'VII – treinar militares e servidores civis das diversas áreas sobre os requisitos e práticas de gestão de qualidade;', 'VIII – avaliar as conformidades das aquisições logísticas e de materiais, a fim de observar se atendem aos parâmetros de qualidade e aos requisitos técnicos previamente definidos no processo; e', 'IX – definir diretrizes, metas e indicadores de desempenho das atividades da Corporação.', 'Parágrafo único. A BM/5 é composta por 02 (duas) subseções: 11', 'I – Subseção de Gestão por Processos e avaliação de resultados - SGAR; e', 'II – Subseção de Planejamento da Qualidade - SPQ. 6ª Seção do Estado Maior Geral'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 22',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.23. A 6ª Seção do Estado Maior Geral (BM/6) é o órgão do Estado Maior Geral que atua no planejamento e orçamento institucional.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 23',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.24. Compete à 6ª Seção do Estado Maior Geral:',
            'dispositivos': ['I – planejar, coordenar, subsidiar, monitorar, avaliar e revisar as atividades relacionadas ao planejamento e orçamento institucional, à programação física e financeira, à proposta orçamentári a e à execução orçamentária da Corporação;', 'II – assessorar a Chefia do Estado -Maior Geral concernente aos assuntos de planejamento e orçamento institucional, mantendo o foco de alinhamento com o plano estratégico da Corporação, bem como, com os Planos Estratégicos seguidos pelo Governo do Estado do Pará;', 'III – participar da formulação do Plano Plurianual (PPA), da Lei de Diretrizes Orçamentárias (LDO) e da Lei Orçamentária Anual (LOA), do Estado do Pará, no âmbito da Corporação;', 'IV – acompanhar a execução das metas e indicadores estratégicos no âmbito d o Planejamento Orçamentário do Estado, no que concerne ao CBMPA;', 'V – manter participação e colaboração efetivas com os diversos órgãos internos da Corporação e com os demais órgãos da administração pública do Estado do Pará, quanto ao ciclo de gestão dos i nstrumentos constitucionais de planejamento;', 'VI – controlar a execução orçamentária mensal e anual da Corporação;', 'VII – elaborar e revisar cronogramas de desembolso e planos de aplicação de recursos;', 'VIII – gerar relatórios gerenciais e demonstrativos financeiros;', 'IX – controlar e acompanhar a execução física e financeira dos recursos oriundos de Fundos;', 'X – elaborar relatórios e demonstrativos para órgãos de controle interno e externo;', 'XI – atender e apoiar auditorias e fiscalizações de órgãos competentes; e', 'XII – gerar informações para subsidiar a prestação de contas anual da Corporação.', 'Parágrafo único. A BM/6, é composta por 02 (duas) subseções:', 'I – Subseção de Planejamento, Programação, Orçamento e Gestão de Recursos - SPPOGR; e', 'II – Subseção de Administração e Patrimônio – SAP. Escritório de Projetos e Convênios'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 24',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.25. O Escritório de Projetos (EPC/Bm) é o órgão do Estado Maior Geral que atua na gestão estratégica e operacional de projetos institucionais.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 25',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.26. Compete ao Escritório de Projetos e Convênios:',
            'dispositivos': ['I – planejar, coordenar e monitorar projetos estratégicos e convênios da Corporação;', 'II – padronizar metodologias, processos e ferramentas de gerenciamento de projetos;', 'III – apoiar o planejamento estratégico da Corporação, traduzindo diretrizes do Comandante -Geral em iniciativas concretas;', 'IV – apoiar as unidades e seções da Corporação na elaboração, execução e controle de projetos institucionais;', 'V – produzir relatórios sistemáticos sobre o progresso, riscos e entregas dos projetos;', 'VI – gerenciar o portfólio de projetos e convênios em andamento, avaliando riscos, prazos e recursos envolvidos; 12', 'VII – garantir a aderência dos projetos ao planejamento estratégico, missões e valores institucionais;', 'VIII – avaliar e priorizar pro postas de novos projetos e convênios, conforme critérios técnicos e estratégicos;', 'IX – interagir com outras áreas estratégicas como a assessoria de assuntos institucionais;', 'X – formular termos de cooperação ou convênios com outras instituições públicas ou privadas; e', 'XI – promover a melhoria contínua na gestão de projetos e convênios da Corporação. Da Ajudância de ordens do EMG'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 26',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.27. Compete à Ajudância de Ordens do Chefe do Estado Maior Geral:',
            'dispositivos': ['I – assistir o chefe do EMG em compromissos sociais, de natureza civil e militar;', 'II – transmitir as ordens emanadas pelo chefe do EMG aos diversos segmentos da Corporação;', 'III – assessorar o chefe do EMG nos assuntos referentes à segurança pessoal;', 'IV – coordenar e fiscalizar o serviço de recepção do Gabinete do chefe do EMG;', 'V – coordenar e fiscalizar o serviço de condutores e a frota de uso direto do chefe do EMG;', 'VI – controlar a agenda institucional do chefe do Estado Maior Geral, registrando compromissos, reuniões, visitas técnicas e eventos; e', 'VII – manter atualizado o cadastro de autoridades. Da Secretaria do EMG'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 27',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.28. Compete à Secretaria do EMG o previsto no art. 10. Das atribuições dos Dirigentes Do Chefe do Estado Maior',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 28',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.29. Ao Chefe do Estado-Maior Geral cabem as seguintes atribuições:',
            'dispositivos': ['I – substituir o Comandante-Geral nos seus impedimentos ou ausências, respondendo pelo Comando- Geral da Corporação;', 'II – dirigir, coordenar e controlar as atividades relacionadas a:', 'a) política e Planejamento de Pessoal e Legislação;', 'b) política e Planejamento de Gestão do Conhecimento, Cultura e Inovação;', 'c) política e Planejamento de Operações, Doutrina e Estatística;', 'd) política e Planejamento de Logística', 'e) política de Gestão pela Qualidade; e', 'f) Planejamento e Orçamento Institucional;', 'III – executar o planejamento aprovado pelo Comandante-Geral no tocante à competência dos órgãos subordinados;', 'IV – assessorar o Comandante-Geral na coordenação e supervisão geral das atividades da Corporação por meio do controle das atividades dos órgãos de direção setorial, compreendendo:', 'a) Diretoria de Apoio Logístico (DAL);', 'b) Diretoria de Finanças (DF); 13', 'c) Diretoria de Contratações e aquisições (DCA);', 'd) Diretoria de Tecnologia da Informação e Comunicação (DTIC); e', 'e) Diretoria de Saúde (DS).', 'V – assegurar a atuação convergente e dinâmica dos órgãos de direção, apoio e execução;', 'VI – supervisionar a execução das diretrizes, planos e ordens;', 'VII – realizar inspeções periódicas; e', 'VIII – desempenhar outras atribuições delegadas pelo Comandante-Geral.', 'Parágrafo único. No impedimento ou ausência do Chefe do Estado Maior Geral, responderá por esta função, seguindo a ordem de prioridade: o Coordenador-Adjunto Estadual de Defesa Civil, o Corregedor- Geral, o Comandante Operacional e o Chefe do Departamento-Geral mais antigo. Do Subchefe do Estado Maior'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 29',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.30. Constituem atribuições básicas do Subchefe do Estado Maior Geral:',
            'dispositivos': ['I – dirigir, supervisionar e coordenar os trabalhos do Estado Maior Geral no que diz respeito às atividades de todos os órgãos subordinados, auxiliando as atividades do Chefe do Estado Maior Geral;', 'II – elaborar e expedir as normas de funcionamento do Estado Maior Geral;', 'III – manter o Chefe do Estado Maior Ge ral e os Chefes de Seções do Estado Maior Geral informados a respeito de assuntos que influenciam o processo decisório em curso;', 'IV – representar o Chefe do Estado Maior Geral quando designado;', 'V – receber as decisões do Chefe do Estado Maior Geral e trans formá-las em ordens e diretrizes a serem executadas pela Corporação;', 'VI – atribuir às Seções do Estado Maior Geral a tarefa de elaboração de planos, estudos, levantamentos, ordens e relatórios detalhados e outras atividades pertinentes;', 'VII – inspecionar as atividades do Estado Maior Geral para assegurar-se de que são adequadas, integradas e destinadas a produzir os resultados pretendidos e aprovação de atos ou encaminhamento ao Chefe do Estado Maior Geral para aprovação;', 'VI – assegurar que as ordens e instruções do Chefe do Estado Maior Geral sejam cumpridas; e', 'VII – atuar como sub fiscal administrativo, monitorando as atividades administrativas de todos os órgãos de direção setorial do CBMPA. Dos Chefes de Seção do Estado Maior Geral'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 30',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I — Direção Geral (Comando-Geral, Alto Comando, EMG)',
            'caput': 'Art.31. Aos Chefes de Seção do EMG cabem as seguintes atribuições:',
            'dispositivos': ['I – assessorar o Comandante Geral e o Chefe do Estado -Maior Geral nos assuntos da alçada de sua respectiva Seção;', 'II – propor medidas para implementação de desenvolvimento institucional nas respectivas áreas;', 'III – responder por toda documentação, comunicação, planejamento, levantamento e/ou informação pertinente à Seção;', 'IV – manter a comunicação de chefia entre as demais Seções do Estado Maior Geral, especialmente quando houver trabalhos que envolvam dados ou trabalhos colaborativos entre sua Seção e outras:', 'V – baixar instruções pertinentes à Seção, delegando atribuições da respectiva competência para o fiel cumprimento do disposto no presente regimento;', 'VI – chefiar, supervisionar e controlar as atividades e atos administrativos desenvolvidos nas Seções do Estado Maior Geral por seus subordinados;', 'VII – elaborar plano anual de metas a serem atingidas pela Corporação, nas respectivas atribuições, de acordo com as diretrizes do Comandante Geral, da Secretaria de Estado da Segurança Pública e Defesa 14 Social e do Governo do Estado do Pará;', 'VIII – propor e elaborar diretrizes e normas de acordo com as respectivas atribuições;', 'IX – apresentar estudos comparativos e evolutivos de atividades operacionais e administrativas; e', 'X – analisar e encaminhar matérias a serem disponibilizadas no website da Corporação para a assessoria de comunicação, ouvindo o Chefe do Estado Maior Geral.'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 31',
            'match': 'exata',
        },
    ],
    ('disciplina-correicao', 'pa'): [
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.34. Compete a Corregedoria-Geral (CORREG), órgão de direção-geral, subordinado diretamente ao Comandante-Geral, é o órgão correcional da Corporação:',
            'dispositivos': ['I – asessorar o Comandante-Geral na disciplina da Corporação; e', 'II – orientar, prevenir e fiscalizar as atividades funcionais e da conduta profissional dos bombeiros militares, visando o aprimoramento da ética, da disciplina e da hier arquia entre os integrantes da Corporação. Da Organização'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 34',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.35. A Corrergedoria-Geral possui a seguinte estrutura:',
            'dispositivos': ['I – Corregedor-Geral;', 'II – Subcorregedor-Geral;', 'III – Comissão Disciplinar Geral; 15', 'IV – Comissão Disciplinar de Recurso;', 'V – Seção de Inteligência Correcional e Operações;', 'VI – Seção de Gestão de Processos e Apoio Administrativo; e', 'VII – Secretaria.', 'Parágrafo único. É vedado o ingresso, nos quadros funcionais da Corregedoria -Geral, de bombeiros militares que tenham análises desfavorável dos seus assentamentos funcionais por parte do órgão correcional condenados criminalmente por órgão colegiado ou com trânsito em julgado. Das Competências Orgânicas Da Comissão Disciplinar Geral'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 35',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.36. A Comissão Disciplinar Geral será composta pelo Subcorregedor-Geral na condição de presidente e mais 3 (três) oficiais membros, preferencialmente bacharéis em Direito, bem como até 4 (quatro) praças nomeados como auxiliares, obrigatoriamente bacharéis em direito, conforme a necessidade do serviço.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 36',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.37. Compete à Comissão Disciplinar Geral:',
            'dispositivos': ['I – atuar como órgão de fundamentação e apoio técnico às decisões disciplinares do Corregedor -Geral, funcionando como um núcleo de assessoramento jurídico-disciplinar especializado;', 'II – realizar análise de autos processuais, de Procedimento Adminitrativo Disciplinar Simplificado (PADS), Sindicâncias e Inquéritos Policiais Militares, com vistas à instrução de pareceres técnicos para subsidiar as decisões administrativas disciplinares do Corregedor;', 'III – preparar fundamentação técnico jurídica das decisões adm inistrativas disciplinares para apreciação do Corregedor-Geral, propondo possíveis enquadramentos disciplinares, penalidades ou arquivamento, de acordo com os indícios, evidências, provas e normas jurídicas vigentes;', 'IV – auxiliar o Subcorregedor-Geral na uniformização de entendimentos e procedimentos disciplinares;', 'V – emitir opinião técnica e alertas ao Corregedor -Geral e o Subcorregedor - Geral quanto a eventuais riscos de prescrição administrativa;', 'VI – manter atualizadas as planilhas e relatórios de controle processual, referentes ao fluxo de processos que estão conclusos, sobre a sua guarda e responsabilidade para solução;', 'VII – alimentar o sistema informatizado de acompanhamento processual, quando este estiver operante, com dados atualizados sobre os processos que estão conclusos para decisão;', 'VIII – fornecer modelos padronizados de peças processuais (despachos, decisões, notificações, intimações, relatórios finais, assegurando uniformidade em todo o CBMPA;', 'IX – prestar assessoria técnica às comissões disciplinares regionais, quando demandado pelo Subcorregedor-Geral;', 'X – sugerir medidas de orientação e capacitação em matéria disciplinar, com base em falhas recorrentes observadas nos processos analisados; e', 'XI – Colaborar com a produção de súmulas administrativas internas, pareceres, orientações e notas técnicas, sobre temas reiterados, a serem homologadas pelo Corregedor-Geral. Da Comissão Disciplinar de Recurso'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 37',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.38. A Comissão Disciplinar de Recursos será composta pelo Corregedor -Geral na condição de presidente e até de 3 (três) oficiais membros, preferencialmente bacharéis em Direito.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 38',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.39. Compete à Comissão Disciplinar de Recursos: 16',
            'dispositivos': ['I – atuar como órgão de fundamentação e apoio técnico às decisões disciplinares do Corregedor -Geral, em sede recursal, funcionando como um núcleo de assessoramento jurídico -disciplinar em processos e procedimentos em fase recursal;', 'II – realizar análise de au tos e peças processuais, com vistas a instrução de pareceres técnicos para subsidiar as decisões administrativas disciplinares do Corregedor em nível recursal;', 'III – preparar fundamentação técnico jurídica das decisões administrativas disciplinares, em sede recursal para apreciação do Corregedor -Geral, em recursos interpostos contra decisões disciplinares proferidas por:', 'a) o próprio Corregedor-Geral, em primeira instância correcional; e', 'b) todas as demais autoridades disciplinares listadas no art. 26 do Código de Ética e Disciplinar do CBMPA, desde que situadas abaixo de sua precedência funcional.', 'IV – sugerir ao Corregedor Geral, manutenção, reforma ou anulação das decisões recorridas, conforme o mérito do caso;', 'V – identificar teses jurídicas recorrentes nos r ecursos e propor ao Corregedor - Geral a edição de enunciados e súmulas administrativas internas para padronizar entendimentos;', 'VI – apoiar a consolidação da jurisprudência administrativa disciplinar do CBMPA, promovendo segurança jurídica e isonomia no julgamento dos recursos;', 'VII – controlar prazos processuais em grau de recurso, em articulação com a Seção de Gestão de Processos e Apoio Administrativo de modo a garantir a razoável duração do processo;', 'VIII – alimentar o sistema informatizado de acompanhamento processual, quando este estiver operante, com dados atualizados sobre recursos interpostos, julgados e pendentes;', 'IX – elaborar relatórios periódicos com análise das principais causas de recursos, subsidiando o Corregedor-Geral na adoção de medidas de prevenção disciplinar e aperfeiçoamento normativo; e', 'X – sugerir medidas de orientação e capacitação em matéria disciplina r das autoridades julgadoras em matéria recursal. Das Comissões Disciplinares de Núcleos de Corregedorias Regionais'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 39',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.40. As Comissões Disciplinares de Núcleos de Corregedorias Regionais, vinculadas diretamente ao Subcorregedor-Geral, com estrutura funcional e competência correcional no âmbito de suas circunscrições, serão instaladas no ato de criação e ativação dos Comandos Regionais de Bombeiros de Proteção e Emergência Ambiental (CRB).',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 40',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.41. Compete às Comissões Disciplinares dos Núcleos de Corregedoria Regionais:',
            'dispositivos': ['I – instaurar processos administrativos disciplinares e demais procedimentos correcionais instaurados pelo Chefe do Núcleo, promovendo a colheita de provas, oitivas, diligências e demais atos necessários à apuração dos fatos;', 'II – elaborar relatórios conclusivos e minutas de decisões administrativas disciplinares, para apreciação e julgamento pelo Chefe do Núcleo de Corregedoria Regional;', 'III – prestar assessoramento técnico -jurídico ao Chefe do Núcleo em sua condição de autor idade disciplinar, sugerindo o enquadramento das condutas e a sanção cabível, ou o arquivamento, quando for o caso;', 'IV – zelar pela observância dos princípios do devido processo legal, ampla defesa, contraditório, razoabilidade, legalidade e eficiência em todos os procedimentos sob sua responsabilidade;', 'V – exercer suas atribuições exclusivamente no âmbito da circunscrição territorial do respectivo Núcleo Regional, encaminhando ao Corregedor-Geral os casos que, pela gravidade, complexidade ou repercussão institucional, exijam decisão em instância superior;', 'VI – acompanhar os prazos de tramitação dos processos disciplinares, alertando a autoridade competente sobre risco de prescrição administrativa, e manter atualizados os sistemas informatizados de gestão 17 processual disciplinar;', 'VII – observar as orientações normativas, manuais, modelos e diretrizes expedidas pela Corregedor ia- Geral, assegurando a padronização dos procedimentos correcionais em todo o Estado;', 'VIII – elaborar relatórios estatísticos periódicos de sua atuação e remetê -los à Corregedoria-Geral, para fins de consolidação e planejamento estratégico;', 'IX – realizar, em articulação com os Comandos Regionais, atividades de formação, orientação e prevenção disciplinar junto aos militares de sua região;', 'X – colaborar com a Corregedoria-Geral e com a Seção de Inteligência Correcional e Operações, quando solicitado, na execução de inspeções, diligências e ações integradas;', 'XI – prestar informações e relatórios sempre que requisitado pelo Corregedor - Geral ou Subcorregedor- Geral; e', 'XII – prestar orientações sobre atividades de polícia judiciária militar as unidades operacionais e aos comandos regionais sobre a sua circunscrição correcional. Da Seção de Inteligência Correcional e Operações'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 41',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.42. A Seção de Inteligência Correcional e Operações (SICO) é o órgão da Corregedoria -Geral incumbido realizar segurança orgânica de autoridades, coleta, análise, sistematização e difusão de informações estratégicas voltadas à prevenção e repressão de desvios disciplinares e ilícitos praticados por bombeiros militares.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 42',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.43. Compete à Seção de Inteligência Correcional e Operações:',
            'dispositivos': ['I – realizar atividade de inteligência correcional;', 'II – coletar, tratar e organizar informações relacionadas à condutas disciplinares e ético -profissionais de bombeiros militares;', 'III – planejar, coordenar e executar ações de segurança orgânica, abrangendo pessoas, informações, instalações e materiais;', 'IV – promover a segurança das autoridades e instalações do Comando-Geral e demais órgãos de direção, quando determinado pelo Comandante-Geral; e', 'V – realizar tratativas para trabalhos em conjunto com o Centro de Inteligência do CBMPA. Da Seção de Gestão de Processos e Apoio Administrativo'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 43',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.44. A Seção de Gestão de Processos e Apoio Administrativo (SGPAA) é o órgão responsável pelo planejamento, coordenação, controle Processual e suporte administrativo das atividades da Corregedoria-Geral, assegurando a organização, a padronização e a fluidez do trâmite processual disciplinar no âmbito do CBMPA.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 44',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.45. Compete à Seção de Gestão de Processos e Apoio Administrativo:',
            'dispositivos': ['I – controlar fluxo processual de Processos e Procedimentos Disciplinares Instaurados pela Corregedoria Geral;', 'II – organizar, controlar e monitorar a tramitação de todos os processos e procedimentos disci plinares instaurados pela Corregedoria-Geral;', 'III – distribuir os processos e procedimentos disciplinares aos encarregados, acompanhando sua movimentação, interna e externa até decisão final e arquivamento;', 'IV – registrar, monitorar e consolidar prazos de instauração, instrução processual, análise, solução, impetração de recursos e decisão final, alertando as autoridades competentes quanto ao risco de prescrição administrativa;', 'V – alimentar e manter atualizadas as planilhas de dados referentes à instauraç ão e tramitação de 18 processos e procedimentos disciplinares instaurados pela corregedoria geral;', 'VI – elaborar e atualizar as estatísticas referentes ao andamento dos processos e procedimentos disciplinares instaurados pela Corporação;', 'VII – elaborar relatórios estatísticos sobre as apurações e punições discipl inares aplicadas ao efetivo da Corporação, mapeando o perfil disciplinar da tropa, com vistas a subsidiar tomadas de decisão do corregedor quanto a políticas orientação, prevenção a serem implementadas pela Corregedoria;', 'VIII – operar, alimentar, administrar e manter atualizado o sistema informatizado de gestão processual disciplinar, assegurando rastreabilidade e transparência;', 'IX – fornecer apoio técnico-logístico às comissões disciplinares, às seções da Corregedoria;', 'X – disponibilizar modelos, manuais técnicos e orientações padronizadas, procedimentos e processos disciplinares, portarias de instauração e outros atos administrativos aos órgãos do CBMPA, garantindo uniformidade processual;', 'XI – gerenciar e controlar fluxos de trabalho, sistemas informatizados de gestão correcional e rotinas administrativas, visando maior eficiência;', 'XII – enviar aos encarregados, investigados e acusados, termos de livre ciência, diligências entre outros documentos necessários à continuidade e complementação da instrução processual;', 'XIII – armazenar, tabular e processar os dados encaminhados pelos Núcleos de Corregedoria Regionais e pelas demais seções, garantindo a integração do sistema correcional;', 'XIV – propor ao Corregedor Geral, medidas de modernização e inovação administrativa para otimizar a gestão processual; e', 'XV – confeccionar todas as minutas de portaria de instauração de procedimentos e processos administrativos, inclusive as determinações contidas nas soluções dos procedimentos e processos. Da Secretaria da Corregedoria'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 45',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.46. Compete à Secretaria da Corregedoria previsto no art. 10. Das atribuições dos Dirigentes Do Corregedor-Geral',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 46',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.47. Constituem atribuições básicas do Corregedor-Geral:',
            'dispositivos': ['I – exercer a direção superior da Corregedoria -Geral, coordenando, supervisionando e orientando todas as atividades correcionais;', 'II – presidir a Comissão Disciplinar de Recursos, zelando pela uniformização da jurisprudência administrativa disciplinar no âmbito do CBMPA;', 'III – propor ao Comandante -Geral alterações normativas referentes a seara disciplinar, por meio da elaboração de estudos, notas técnicas e minutas de normas atinentes a legislação disciplinar;', 'IV – expedir notas técnicas, instruções normativas e recomendações para a melhoria contínua do sistema disciplinar da Corporação;', 'V – determinar a instauração de sindicâncias, processos administrativos disciplinares e demais procedimentos correcionais previstos no código de Ética do CBMPA;', 'VI – decidir sobre medidas cautelares de afastamento ou restrição de funções, quando cabíveis;', 'VII – proferir decisões disciplinares em primeira instância administrativa sobre processos ou procedimentos disciplinares que tenha instaurado, assegurando o devido processo legal;', 'VIII – decidir, em última instância administrativa disciplinar, sobre os Recur sos Hierárquicos, interpostos 19 contra decisões disciplinares proferidas por todas as autoridades disciplinares prevista no art. 26 do Código de Ética e Disciplinar da Corporação que estejam funcionalmente abaixo da sua precedência funcional;', 'IX – elaborar e supervisionar a implementação do plano estratégico correcional do CBMPA;', 'X – gerenciar estudos, juntamente com a 5ª Seção do Estado Maior Geral , com o objetivo de estabeler indicadores de desempenho e metas de produtividade da Corregedoria;', 'XI – promover a elaboração de políticas de prevenção disciplinar que envolvam: educação, orientação ética- disciplinar e cursos de capacitação;', 'XII – gerenciar os recursos humanos, logísticos e orçamentários da Corregedoria;', 'XIII – determinar e revisar a produção dos dados contidos nos relatórios estatísticos e administrativos da corregedoria e encaminhá-los ao CONSEP e ao Comandante-Geral da Corporação; e', 'XIV – representar institucionalmente à Corregedoria -Geral perante o CONSEP, Comandante -Geral da Corporação, órgãos de controle interno e externo, bem como em eventos institucionais ou de outros órgãos, sempre que determinado pelo Comando Geral da Corporação. Do Subcorregedor-Geral'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 47',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VI — Corregedoria-Geral',
            'caput': 'Art.48. Constituem atribuições básicas do Subcorregedor-Geral:',
            'dispositivos': ['I – auxiliar diretamente o Corregedor-Geral no planejamento e coordenação das atividades correcionais;', 'II – presidir a Comissão Disciplinar Geral, orientando sobre os entendimentos jurídicos aplicados nas análises dos procedimentos disciplinares, revisando a s soluções de procedimentos e processos em primeira instância que serão levados para julgamento do Corregedor;', 'III – coordenar e orientar as Comissões Disciplinares Regionais, garantindo a padronização de procedimentos e decisões;', 'IV – propor ao Corregedor -Geral medidas de prevenção e correção de falhas detectadas no funcionamento do sistema de correção disciplinar;', 'V – propor ao Corregedor -Geral melhorias nos fluxos internos de trabalho, capacitação de pessoal e modernização dos sistemas informatizados de acompanhamento processual;', 'VI – substituir o Corregedor-Geral em suas ausências, afastamentos e impedimentos legais;', 'VII – coordenar e supervisionar o trabalho das seções internas da Corregedoria garantindo a integração das atividades funcionais;', 'VIII – chefiar a Secretaria e Subcorregedoria-Geral;', 'IX – acompanhar o fluxo processual e tramitação interna dos procedimento s e processos disciplinares, zelando pela razoável duração dos processos;', 'X – participar da elaboração, gerenciar e supervisionar diretamente a execução das metas estabelecidas no plano estratégico correcional;', 'XI – supervisionar o trabalho das Seções inte rnas na execução das metas estabelecidas pelo Corregedor Geral e planejamento estratégico correcional;', 'XII – estimular e orientar a interlocução dos núcleos de Corregedorias Regionais com os Comandos Regionais de modo a possibilitar a integração das ações correcionais; e', 'XIII – representar a Corregedoria Geral em reuniões, eventos ou audiências, quando delegado formalmente ou determinado verbalmente pelo Corregedor- Geral.'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 48',
            'match': 'exata',
        },
    ],
    ('disposicoes-finais', 'pa'): [
        {
            'heading': 'Disposições Finais',
            'caput': 'Art.316. O Art. 4º do Decreto Estadual nº 2.360 de 16 de maio de 2022, passa a vigorar com a seguinte redação: “Art. 4º....................................................................................................................................................... .',
            'dispositivos': ['VI – o chefe do Departamento Geral de Segurança Contra Incêndio e Emergências; e', 'VII – o assistente do Comandante-Geral.', '§1º O presidente da Comissão de Mérito Bombeiro Militar será o Comandante -Geral do Corpo de Bombeiros Militar do Pará (CBMPA) e o Secretário, o assistente do Comandante-Geral.”'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 316',
            'match': 'exata',
        },
        {
            'heading': 'Disposições Finais',
            'caput': 'Art.317. Os casos omissos e as dúvidas surgidas na aplicação do presente Regimento I nterno serão interpretados e decididos pelo Alto Comando do Corpo de Bombeiros Militar do Pará.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 317',
            'match': 'exata',
        },
        {
            'heading': 'Disposições Finais',
            'caput': 'Art.318. O presente Regimento entra em vigor na data de sua publicação. PALÁCIO DO GOVERNO, de de 2026 .',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 318',
            'match': 'exata',
        },
    ],
    ('disposicoes-preliminares', 'pa'): [
        {
            'heading': 'TÍT. I, Cap. I — Natureza e Finalidade',
            'caput': 'Art.1º O Corpo de Bombeiros Militar do Estado do Pará (CBMPA) é instituição permanente, força auxiliar e reserva do Exército, organizado com base na hierarquia e disciplina militares, subordinado ao Governador do Estado, o qual é o seu Comandante Supremo, destina-se a realizar serviços específicos de Bombeiro Militar e de Proteção e Defesa Civil no Estado do Pará criada conforme preceitua os art. 42 e 144 da Constituição Federal de 05 de outubro de 1988 e o art. 200 da Constituição Es tadual de 05 de outubro de 1989.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 1',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. I — Natureza e Finalidade',
            'caput': 'Art.2º O Corpo de Bombeiros Militar do Estado do Pará (CBMPA) é um órgão da Administração Direta do Estado com dotação orçamentária própria, dotado de autonomia administrativa e funcional, e tem por finalidade realizar serviços específicos de Bombeiro-Militar e de Proteção e Defesa Civil no Estado do Pará, visando à preservação da ordem pública, incolumidade das pessoas, do patrimônio e do meio ambiente.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 2',
            'match': 'exata',
        },
    ],
    ('ensino-instrucao', 'pa'): [
        {
            'heading': 'Cap. XI — Departamento-Geral de Cultura, Educação e Pesquisa',
            'caput': 'Art.83. O Departamento-Geral de Cultura, Educação e Pesquisa (DGCEP), o órgão de direção -geral, diretamente subordinado ao Comandante -Geral, responsável pela gestão do s istema de ensino bombeiro militar, das atividades de pesquisa, relacionados à formação, à capacitação, ao aperfeiçoamento, à especialização, à extensão e a qualificação dos oficiais e praças, bem como pela promoção da cultura.',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 83',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XI — Departamento-Geral de Cultura, Educação e Pesquisa',
            'caput': 'Art.84. Compete ao Departamento-Geral de Cultura, Educação e Pesquisa , além do previsto no art. 60:',
            'dispositivos': ['I – assessorar o Comandante Geral em assuntos de natureza do ensino bombeiro militar, com vistas à tomada de decisão;', 'II – coordenar, controlar, acompanhar e supervisionar as atividades de gestão estratégica do sistema de ensino bombeiro militar;', 'III – planejar todas as ações de educação para formação inicial, capacitação continuada, aperfeiçoamento, habilitação, especialização bombeiro militar, extensão e qualifi cação dos oficiais e praças da Corporação;', 'IV – planejar todas as ações de educação pública em pa rceria com os demais setores envolvidos no processo;', 'V – coordenar a atividades de preservação e divulgação do patrimônio histórico e cultural, material e imaterial, do CBMPA;', 'VI – estabelecer programas para o desenvolvimento da prática da atividade físic a e do desporto no CBMPA;', 'VII – promover ações que proporcionem ao CBMPA uma atuação destacada em competições desportivas de nível nacional e internacional;', 'VIII – coordenar as ações de desenvolvimento da produção científica e cultural;', 'IX – estabelecer ações para ampliar a integração do Sistema de Ensino do CBMPA, na esfera de suas atribuições, com sistemas similares;', 'X – estabelecer a educação preparatória e assistencial no Corpo de Bombeiros Militar do Pará; e', 'XI – acompanhar os processos de aquisições e contratações relativos ao DGCEP. Da Organização'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 84',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XI — Departamento-Geral de Cultura, Educação e Pesquisa',
            'caput': 'Art.85. O Departamento-Geral de Cultura, Educação e Pesquisa possui a seguinte estrutura:',
            'dispositivos': ['I – Chefe do Departamento-Geral de Pessoal;', 'II – Assistente; 34', 'III – Seção de Planejamento de Ensino e Pesquisa; e', 'IV – Secretaria.'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 85',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XI — Departamento-Geral de Cultura, Educação e Pesquisa',
            'caput': 'Art.86. São órgãos subordinados ao DGCEP:',
            'dispositivos': ['I – Órgãos de Apoio:', 'a) Academia Bombeiro Militar;', 'b) Centro de Formação, Aperfeiçoamento e Especialização;', 'c) Centro de Capacitação Física e Desporto; e', 'd) Centro de Memória.', 'Parágrafo único. Os órgãos subordinados ao Departamento Geral de Cultura, Educação e Pesquisa estão descritos nos artigos 204, 212, 220 e 239 deste regimento. Das Competências Orgânicas Da Seção de Planejamento de Ensino e Pesquisa'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 86',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XI — Departamento-Geral de Cultura, Educação e Pesquisa',
            'caput': 'Art.87. Compete à Seção de Planejamento de Ensino e Pesquisa, diretamente subordinada ao Chefe do Departamento-Geral de Cultura, Educação e Pesquisa:',
            'dispositivos': ['I – coordenar e avaliar as atividades pedagógicas e curriculares;', 'II – propor metodologias, emitir parecer técnico e analisar processos educacionais, relatórios de cursos e estágios;', 'III – contribuir na elaboração do plano orçamentário das ações de ensino, visando à efetividade das ações pedagógicas e científicas;', 'IV – validar documentos pedagógicos;', 'V – supervisionar capacitações externas;', 'VI – analisar relatórios de ensino;', 'VII – manter o banco de dados acadêmico atualizado;', 'VIII – gerir pesquisas para difusão do conhecimento técnico no CBMPA; e', 'IX – gerenciar todos os cursos internos e externos ao CBMPA, instruindo documentos técnico - pedagógicos, fiscalizando as Unidades Acadêmicas e polos de ensino.', 'Parágrafo único. A seção de Planejamento de Ensino e Pesquisa é composta por 03 (três) subseções:', 'I – Subseção de Planejamento de Ensino – SS1;', 'II – Subseção de Pesquisa e Educação pública – SS2; e', 'III – Subseção de Capacitação profissional-SS3 Da Secretaria do DGCEP'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 87',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XI — Departamento-Geral de Cultura, Educação e Pesquisa',
            'caput': 'Art.88. Compete à secretaria do Departamento -Geral de Cultura, Educação e Pesquisa o previsto no art 10. Das Atribuições dos Dirigentes Do chefe do Departamento-Geral de Cultura, Educação e Pesquisa 35',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 88',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XI — Departamento-Geral de Cultura, Educação e Pesquisa',
            'caput': 'Art.89. Constituem atribuições básicas do assistente do chefe do do Departamento -Geral de de Cultura, Educação e Pesquisa, além das atribuições previstas no art. 61:',
            'dispositivos': ['I – promover a modernização administrativa e operacional, mediante a capacitação profissional, o desenvolvimento científico e tecnológico e o emprego de ferramentas da tecnologia de informação e comunicação;', 'II – firmar convênios, parcerias e cooperações técnicas para o aprimoramento da formação profissional;', 'III – homologar os editais de seleção aos cursos e estágios internos e externos;', 'IV – designar e dispensar instrutores e monitores dos órgãos do sistema de ensino;', 'V – determinar a quantidade de vagas em cursos e estágios a ser oferecidas a outras organizações militares;', 'VI – aprovar mecanismos de controle, avaliação, capacitação e regras de ensino;', 'VII – estabelecer padrões de qualidade para instrução e treinamento;', 'VIII – analisar a indicação de bombeiros militares para cursos de pós-graduação e estágios técnico-científicos;', 'IX – aprovar projetos pedagógicos de cursos de carreira, técnico-operacionais e estágios profissional;', 'X – presidir o Conselho de Ensino do CBMPA; e', 'XI – presidir o Conselho Editorial da Revista Científica da Corporação e indicar ao Comandante-Geral do CBMPA, mediante sugestão, os membros deste Conselho. Do Assistente do Departamento-Geral de Cultura, Educação e Pesquisa'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 89',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XI — Departamento-Geral de Cultura, Educação e Pesquisa',
            'caput': 'Art.90. Constituem atribuições básicas do assistente do DGCEP, diretamente subordinada ao chefe do Departamento-Geral de de Cultura, Educação e Pesquisa, além do previsto no Art. 62:',
            'dispositivos': ['I – autorizar nota para publicação em Boletim Geral de atividades referentes a cursos, estágios, treinamentos, capacitações bem como eventos acadêmicos e científicos, tais como QIS, editais e portarias;', 'II – propor em conjunto com as unidades de ensino, Centro de Capacitação Física e Desporto, Centro de Memória, BM3 do EMG e COP o programa de capacitação anual do CBMPA;', 'III – participar da elaboração dos projetos pedagógicos dos cursos de carreira do CBMPA;', 'IV – proferir despachos sobre o processo de contratação de docentes para os setores competentes e instruir o Chefe do Departamento a respeito; e', 'V – analisar requerimentos de diplomas, certificados e declaração de docência (SIGA) e providenciar publicação em boletim geral.'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 90',
            'match': 'exata',
        },
    ],
    ('organizacao-geral', 'pa'): [
        {
            'heading': 'TÍT. I, Cap. II — Competência e Estrutura Organizacional',
            'caput': 'Art.3º Compete ao Corpo de Bombeiros M ilitar do Pará (CBMPA), sem prejuízo de outras atribuições estabelecidas em lei:',
            'dispositivos': ['I – planejar, coordenar e executar atividades de proteção e defesa civil;', 'II – planejar, coordenar e dirigir as ações de prevenção, extinção de incêndios, de atendimento a emergências, de busca, salvamento e resgate terrestre, aquático e aéreo, de pessoas e bens;', 'III – exercer as atividades de polícia judiciária militar no âmbito de sua competência;', 'IV – executar ações de emergência em atendimento pré-hospitalar e socorros de urgência;', 'V – executar perícias de incêndios e explosões, relacionadas com sua competência;', 'VI – estabelecer, executar e fiscalizar a prevenção e proteção balneária;', 'VII – proteger e prevenir acidentes e incêndios na orla marítima e fluvial;', 'VIII – proteger o meio ambiente mediante a realização de atividades de prevenção, combate e extinção de incêndio florestal;', 'IX – realizar pesquisas técnico -científicas, com v istas à obtenção e ao desenvolvimento de produtos e processos voltados à segurança contra incêndios e emergências; - exercer a análise de projetos, realizar vistorias, licenciamento e a fiscalização de edificações, eventos e locais de reunião de público, al ém de áreas de risco, aplicando as medidas previstas na legislação, inclusive sanções administrativas e medidas acautelatórias, e, privativamente, exercer a segurança contra incêndio e emergências no Estado;', 'X – editar atos normativos de prevenção e segurança contra incêndios, catástrofes ou produtos perigosos para resguardar a vida das pessoas e reduzir riscos de danos ao meio ambiente e ao patrimônio;', 'XI – regulamentar, credenciar e fiscalizar as empresas de fabricação e comercialização de produtos, bem como as escolas formadoras e os profissionais na prestação de serviços relativos à segurança contra incêndio e emergências;', 'XII – desenvolver políticas de prevenção de caráter educativo e informativo, relativas à prevenção contra acidentes, à prevenção contra incêndio e emergência, a socorros de urgência e concernentes a ações em caso de sinistros, entre outras, na forma da lei;', 'XIII – exercer todas as prerrogativas inerentes ao poder de polícia para o cumprimento de suas missões e finalidades; 3', 'XIV – colaborar na formação, no acompanhamento e na supervisão dos agentes de defesa civil do município para o efetivo emprego operacional no Corpo de Bombeiros Militar do Pará (CBMPA) mediante convênio firmado entre o Município e o Estado;', 'XV – supervisionar e coordenar os profissionais e as instituições civis do município que atuarão nas atividades de competência do Corpo de Bombeiros Militar do Pará (CBMPA), nos termos da legislação em vigor; e', 'XVI – realizar atendimentos próprios de emergênci a em acidentes de trânsitos com vítimas, acidentes traumáticos pessoais e do trabalho, acidentes com lesões corporais traumáticas, afogamentos, tentativa de homicídio, lesão grave e tentativa de suicídio e acidentes envolvendo choque elétrico, queimaduras e partos de emergência.'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 3',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. II — Competência e Estrutura Organizacional',
            'caput': 'Art.4º Para desempenhar eficientemente sua missão institucional, o Corpo de Bombeiros Militar do Pará (CBMPA) tem a seguinte composição: 1. Órgãos de Direção: 1.1 Órgãos de Direção Geral: 1.1.1 Comandante-Geral; 1.1.2 Alto Comando; 1.1.3. Estado-Maior Geral; 1.1.4. Coordenadoria Estadual de Proteção e Defesa Civil; 1.1.5. Corregedoria-Geral; 1.1.5. Comando de Operações; 1.1.6 Departamento-Geral de Administração (DGA); 1.1.7 Departamento-Geral de Pessoal (DGP); 1.1.8 Departamento-Geral de Cultura, Educação e Pesquisa (DGCEP); 1.1.9 Departamento-Geral de Segurança Contra Incêndios e Emergências (DGSCI); 1.1.10 Comissão de Promoção de Oficiais; 1.1.11 Comissão de Promoção de Praças; 1.1.12 Gabinete do Comandante-Geral; 1.1.13 Ajudância Geral; 1.1.14 Controladoria Interna; 1.1.15 Consultoria Jurídica; e 1.1.16 Centro de Inteligência. 1.2 Órgãos de Direção Intermediária: 1.1.2 Comandos Operacionais Intermediários de Bombeiros. 1.3 Órgãos de Direção Setorial: 1.3.1 Diretoria de Apoio Logístico (DAL); 1.3.2 Diretoria de Finanças (DF); 1.3.3 Diretoria de Contratações e Aquisições (DCA); 1.3.4 Diretoria de Tecnologia da Informação e Comunicação (DTIC); e 1.3.5 Diretoria de Saúde. 2. Órgãos de Apoio: 2.1. Academia Bombeiro Militar; 2.2. Centro de Formação, Aperfeiçoamento e Especialização; 2.3. Centro de Capacitação Física e Desporto; 2.4. Centro de Suprimento e Manutenção de Viaturas e Materiais Operacional; 2.5. Centro de Patrimônio; 2.6. Centro de Memória; 2.7. Capelania; 4 2.8. Banda de Música; e 2.9. Colégio Militar. 3. Órgãos de Execução: 3.1 Unidades Multiemprego: 3.1.1 Grupamento Bombeiro Militar; 3.1.2 Subgrupamento Bombeiro Militar; 3.1.3 Seção Bombeiro Militar; e 3.1.4 Posto Avançado Bombeiro Militar. 3.2. Unidades Especializadas: 3.2.1. Grupamento Marítimo e Fluvial (GMAF); 3.2.2. Grupamento de Busca e Salvamento (GBS); 3.2.3. Grupamento de Socorro e Emergência (GSE); 3.2.4 Grupamento de Operações Aéreas (GOA); e 3.2.5 Núcleo de Ações com Cães (NAC).',
            'dispositivos': ['Parágrafo único. Lei específica tratará, no que couber, do colégio militar previsto no item 2.9, deste artigo.'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 4',
            'match': 'exata',
        },
    ],
    ('seguranca-contra-incendio', 'pa'): [
        {
            'heading': 'Cap. XII — Departamento-Geral de Segurança Contra Incêndios e Emergências',
            'caput': 'Art.91. Compete ao Departamento-Geral de Segurança contra Incêndios e Emergências (DGSCI), além do previsto no art. 60:',
            'dispositivos': ['I – realizar perícias em casos de incêndios e explosões, respeitadas as atribuições e competências de outros órgãos;', 'II – planejar, coordenar e executar as atividades de análise de projetos (na forma física ou eletrônica), vistoriar e fiscalizar as edificações e áreas de risco concernentes ao Serviço de Segurança Contra Incêndio e Emergências;', 'III – fiscalizar as edificações e áreas de risco por meio de seus vistoriadores, não se responsabilizando pela instalação, comissionamento, inspeção, ensaio, manutenção ou utilização indevida; 36', 'IV – expedir o licenciamento do Corpo de Bombeiros Militar do Estado do Pará;', 'V – anular, cassar ou revogar o licenciamento do Corpo de Bombeiros Militar do Estado do Pará;', 'VI – embargar ou interditar, total ou parcialmente, edificações ou áreas de risco;', 'VII – notificar o proprietário ou responsável pelo uso da edificação e áreas de risco para correção de irregularidades ou adoção de providências correlatas;', 'VIII – orientar, notificar, autuar e sancionar o proprietário ou responsável pelo uso da edificação e área de risco em caso de falta de regularização;', 'IX – comunicar o setor de fiscalização das prefeituras municipais a respeito das obras, serviços, habitações e locais de uso público ou privado que não atendam aos termos deste Regulamento;', 'X – expedir ordem de serviço de vistoria diária ou semanal informando o estabelecimento e visto riador que executará a vistoria; e', 'XI – realizar avaliação estrutural emergencial em edificaçõe s, instalações ou locais sujeitos a incêndios, explosões, colapso, ameaça de colapso, acidentes tecnológicos ou outras ocorrências críticas, nas seguintes hipósteses:', 'a) quando solicitada por órgãos públicos', 'b) em eventos de grande repercussão envolvendo vítimas ou risco grave à coletividade; e', 'c) de ofício, mediante deliberação do chefe do Departamento.', 'Parágrafo único. A avaliação estrutural emergencial será formaliz ada por meio de Parecer de Ins peção Estrutural – PIE. Da Organização'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 91',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XII — Departamento-Geral de Segurança Contra Incêndios e Emergências',
            'caput': 'Art.92. O Departamento-Geral de Segurança contra Incêndios e Emergências (DGSCI) possui a seguinte estrutura:',
            'dispositivos': ['I – Chefe do Departamento-Geral de Segurança contra Incêndios e Emergências;', 'II – Subchefe do Departamento-Geral de Segurança contra Incêndios e Emergências;', 'III – Seção de Fiscalização e Vistoria Técnica;', 'IV – Seção de Análise de Projetos;', 'V – Seção de Perícia de Incêndio;', 'VI – Seção de Credenciamento de Empresas e Profissionais; e', 'VII – Secretaria. Das Competências Orgânicas Da Seção de Fiscalização e Vistoria Técnica'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 92',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XII — Departamento-Geral de Segurança Contra Incêndios e Emergências',
            'caput': 'Art.93. Compete a Seção de Fiscalização e Vistoria Técnica:',
            'dispositivos': ['I – cumprir e fazer cumprir a legislação estadual sobre segurança contra incêndio e emergências e as normas técnicas do Corpo de Bombeiros Militar do Pará, tomando as iniciativas das providências de sua responsabilidade;', 'II – assessorar o chefe do Departamento de Segurança Contra Incêndio e Emergências em todos os assuntos relativos à fiscalização e vistoria técnica;', 'III – adotar medidas de organização e métodos que visem à racionalização e melhor eficiência dos trabalhos do Departamento;', 'IV – realizar vistoria técnica nas edificações onde foram solicitados os serviços;', 'V – cumprir os prazos estabelecidos para realização dos serviços; 37', 'VI – exercer poder de polícia para notificar, multar, embargar e interditar edificações, instalações e locais de risco permanentes ou temporários que não estiverem em conformidade com as exigências da legislação de segurança contra incêndio e emergências do Estado e normas técnicas do Corpo de Bombeiros Militar;', 'VII – fiscalizar locais, edificações e instalações permanentes ou temporárias onde houver risco de incêndio e a vida de pessoas mesmo quando o serviço não for solicitado;', 'VIII – expedir o Certificado de Licenciamento do Corpo de Bombeiros Militar quando for constatado conformidade das edificações, instalações e locais de risco permanentes ou temporários;', 'IX – emanar doutrina e jurisprudência sobre fiscalização para todas as seções de atividades técnicas;', 'X – orientar e coordenar as ações de fiscalização realizadas pelas seções de atividades técnicas; e', 'XI – propor a participação do DGSCIE em cursos, palestras, congressos, seminários relacionados com serviços técnicos.', 'Parágrafo único. A Seção de Fiscalização e Vistoria Técnica possui 03 (três) subseções:', 'I – Subseção de Multa e Interdição - SMI ;', 'II – Subseção de Atendimento ao Público - SAPB; e', 'III – Subseção de Controle de Qualidade e Desempenho - SCQD. Da Seção de Análise de Projetos'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 93',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XII — Departamento-Geral de Segurança Contra Incêndios e Emergências',
            'caput': 'Art.94. Compete a Seção de Análise de Projetos:',
            'dispositivos': ['I – analisar e aprovar projetos técnicos de edificações e áreas de risco, em meio físico ou eletrônico, de acordo com as normas do CBMPA;', 'II – emitir parecer técnico sobre projetos arquitetônicos, elétricos, hidráulicos e de segurança, no que se refere à prevenção contra incêndio;', 'III – avaliar projetos baseados em métodos alternativos de segurança, conforme critérios de desempenho admitidos em norma;', 'IV – orientar profissionais e empresas (engenheiros, arquitetos e responsáveis técnicos) sobre a correta elaboração de projetos de segurança contra incêndio;', 'V – revisar e atualizar procedimentos técnicos e instruções normativas relacionadas à análise de projetos;', 'VI – realizar vistorias técnicas complementares, quando necessário para esclarecer dúvidas durante a análise do projeto;', 'VII – coordenar com a Seção de Fiscalização o fluxo de processos de licenciamento;', 'VIII – participar de comissões técnicas e estudos normativos, contribuindo para o aprimoramento das normas de segurança contra incêndio da Corporação; e', 'IX – capacitar e atualizar o efetivo envolvido com análise de projetos, promovendo padronização e qualidade técnica. Da Seção de Perícia de Incêndio'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 94',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XII — Departamento-Geral de Segurança Contra Incêndios e Emergências',
            'caput': 'Art.95. Compete à Seção de Perícia de Incêndio:',
            'dispositivos': ['I – realizar perícias em locais de incêndio, explosão ou sinistro, determinando:', 'a) a origem do fogo (ponto inicial);', 'b) as causas prováveis (acidentais, naturais, criminosas, elétricas, etc.); e', 'c) as formas de propagação e os fatores contribuintes. 38', 'II – coletar, preservar e analisar vestígios encontrados no local do sinistro, utilizando métodos técnicos e científicos de investigação;', 'III – elaborar laudos periciais e relatórios técnicos, com descrição detalhada dos fatos, evidências observadas e conclusão fundamentada;', 'IV – apoiar autoridades policiais, judiciais e seguradoras, fornecendo informações técnicas sobre as causas e consequências de incêndios;', 'V – manter banco de dados estatísticos sobre as ocorrências periciadas, visando à prevenção e ao estudo de tendências e causas recorrentes;', 'VI – emitir pareceres técnicos sobre materiais, sistemas de prevenção, dispositivos de segurança e instalações elétricas, quando relacionados a incêndios;', 'VII – participar de vistorias técnicas e inspeções complementares em locais de risco, sempre que solicitado por outras seções ou órgãos públicos;', 'VIII – promover estudos e pesquisas sobre comportamento do fogo, materiais combustíveis e novas tecnologias em perícia de incêndio;', 'IX – capacitar e atualizar o efetivo perito-bombeiro, garantindo a padronização dos métodos de investigação e a qualidade técnica dos laudos;', 'X – apoiar o ensino e a formação técnica em cursos internos ou externos do Corpo de Bombeiros, ministrando instruções sobre perícia e investigação de incêndios; e', 'XI – cooperar com órgãos de segurança pública e defesa civil, em investigações conjuntas ou ações integradas.', 'Parágrafo único. A Seção de Perícia de Incêndio possui 01 (uma) subseção, denominada subseção de Estudos Técnicos e Pesquisas Científicas. Da Seção de Credenciamento de Empresas e Profissionais'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 95',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XII — Departamento-Geral de Segurança Contra Incêndios e Emergências',
            'caput': 'Art.96. Compete à Seção de Credenciamento de Empresas e Profissionais:',
            'dispositivos': ['I – analisar e processar pedidos de credenciamento de empresas e profissionais que executam serviços na área de competência do Corpo de Bombeiros (projetos, brigada de incêndios e bombeiros civis);', 'II – verificar a documentação técnica e legal exigida para o credenciamento;', 'III – emitir certificados de credenciamento e autorizações para atuação junto ao Corpo de Bombeiros, com prazos de validade definidos;', 'IV – manter e atualizar o cadastro de empresas e profissionais credenciados, assegurando a transparência e o controle das atividades;', 'V – fiscalizar a atuação dos credenciados, verificando se os serviços prestados seguem as normas de segurança e os padrões estabelecidos pela Corporação;', 'VI – aplicar sanções administrativas (advertência, suspensão ou cancelamento do credenciamento) em casos de irregularidades, conforme instruções técnicas;', 'VII – realizar auditorias e vistorias técnicas em empresas credenciadas, para confirmar a veracidade das informações apresentadas e a qualidade dos serviços;', 'VIII – emitir pareceres técnicos sobre situações específicas envolvendo credenciamento, renovação ou cancelamento de registro;', 'IX – acompanhar a execução de serviços realizados por credenciados, especialmente em casos de denúncias, falhas técnicas ou incidentes; e 39', 'X – fornecer orientações técnicas a profissionais e empresas sobre requisitos de credenciamento, normas vigentes e atualizações de legislação.', 'Parágrafo único. A Seção de Credenciamento de Empresas e Profissionais possui 0 2 (duas) subseções:', 'I – Subseção de Análise de Credenciamento de Pessoa Física - SACPF; e', 'II – Subseção de Análise de Credenciamento de Pessoa Jurídica – SACPJ. Da Secretaria do DGSCI'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 96',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XII — Departamento-Geral de Segurança Contra Incêndios e Emergências',
            'caput': 'Art.97. Compete à secretaria do Departamento -Geral de Segurança Contra Incêndio e Emergências o previsto no art. 10. Das atribuições dos Dirigentes Do Chefe do Departamento-Geral de Segurança contra Incêndios e Emergências',
            'dispositivos': [],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 97',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XII — Departamento-Geral de Segurança Contra Incêndios e Emergências',
            'caput': 'Art.98. Constituem atribuições básicas do Chefe do Departamento-Geral de Segurança contra Incêndios e Emergências, além do previsto no art 61:',
            'dispositivos': ['I – tratar questões de grande repercussão relativas à segurança contra incêndio e emergências;', 'II – homologar plano de ação de fiscalização conjunta com o Comando de Operações;', 'III – presidir a Comissão Técnica Especial (CTE) previsto inciso VI da lei 9.234 de 21 de março de 2021;', 'IV – habilitar militares capacitados, oficial ou praça, imbuídos de função fiscalizadora;', 'V – deliberar sobre casos técnicos complexos encaminhados pelas seções de atividades técnicas;', 'VI – homologar pareceres técnicos, laudos periciais e relatórios conclusivos emitidos pelas Seções subordinadas;', 'VII – submeter ao Comandante-Geral as propostas de convênios, parcerias e protocolos de cooperação com órgãos públicos ou entidades privadas;', 'VIII – determinar auditorias técnicas e inspeções internas para assegurar a padronização e a qualidade das atividades;', 'IX – submeter ao Comandante -Geral as propostas de atualização das instruções técnicas, normas internas e demais regulamentos; e', 'X – supervisionar a publicação de relatórios anuais de atividades e de transparência do serviço de segurança contra incêndio e emergências, conforme o Decreto nº 2.247/2022. Subchefe do Departamento-Geral de Segurança contra Incêndios e Emergências'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 98',
            'match': 'exata',
        },
        {
            'heading': 'Cap. XII — Departamento-Geral de Segurança Contra Incêndios e Emergências',
            'caput': 'Art.99. Constituem atribuições básicas do subc hefe do Departamento -Geral de Segurança contra Incêndios e Emergências, além do previsto no art 62:',
            'dispositivos': ['I – auxiliar o Chefe do DGSCI no planejamento, coordenação e supervisão das atividades do Departamento;', 'II – exercer a supervisão técnica e administrativa das Seções e das Seções de Atividades Técnicas (SATs) instaladas nas unidades bombeiro militar;', 'III – articular a integração entre as Seções, assegurando a uniformidade dos procedimentos técnicos; 40', 'IV – elaborar relatórios de desempenho técnico e administrativo para apreciação do Chefe;', 'V – promover reuniões técnicas periódicas co m os chefes das Seções e das Seções de Atividades Técnicas das unidades operacionais; e', 'VI – presidir a Comissão Técnica do Serviço de Segurança Contra Incêndio e Emergências do Departamento.'],
            'source': 'cf. CBMPA, MINUTA de RI (Decreto em tramitação, 2026), Art. 99',
            'match': 'exata',
        },
    ],
}
