# GERADO por scripts/extrair_regulamentos.py — NÃO editar à mão.
# Fonte: Rio Grande do Norte - Regulamento Geral (Decreto 31.139-2021).md (extração determinística; mapa nos de-paras).
ENRICHMENT = {
    ('competencias-apoio-assessoramento', 'rn'): [
        {
            'heading': 'TÍT. II, Cap. II — Assessoramento',
            'caput': 'Art. 19. O Gabinete do Comando Geral é o seu órgão de apoio administrativo e de representação social, competindo-lhe:',
            'dispositivos': ['I - redigir e preparar o expediente pessoal do Comandante Geral e do Subcomandante Geral e or ganizar suas agendas de despachos e de compromissos, assim como fornecer informações administrativas aos demais ór gãos do Corpo de Bombeiros Militar;', 'II - coordenar a recepção e o atendimento ao público;', 'III - assistir ao Comandante Geral e ao Subcomandante Geral nas suas atividades de relações internas e externas;', 'IV - promover, junto aos órgãos de imprensa, a divulgação de informações sobre a atuação e as atividades do Corpo de Bombeiros Militar;', 'V - exercer outras atividades que lhe forem cometidas pelo Comandante Geral e Subcomandante Geral. Da Assessoria Jurídica'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 19',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. II — Assessoramento',
            'caput': 'Art. 20. A Assessoria Jurídica é o ór gão que presta assessoramento direto ao Comandante Geral do Corpo de Bombeiros Militar , competindo-lhe o estudo de questões de direito compreendidas na política de administração geral da corporação, o exame dos aspectos de legalidade dos atos e normas que lhe forem submetidas à apreciação e demais atribuições que venham a ser previstas em regulamento. Da Assessoria Administrativa',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 20',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. II — Assessoramento',
            'caput': 'Art. 21. A Assessoria Administrativa é o ór gão de assessoramento administrativo da Corporação, diretamente subordinada ao Comandante Geral, competindo-lhe a emissão de informações técnicas, nas matérias que lhe for submetida. Da Ajudância Geral',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 21',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. II — Assessoramento',
            'caput': 'Art. 22. A Ajudância Geral é o órgão encarregado do expediente, da execução dos trabalhos de secretaria geral, incluindo a expedição e recebimento de corre - spondência, correios, redação e impressão do boletim diário do Comando Geral, do protocolo, do apoio em pessoal aos ór gãos que compõem o Comando Geral, dos serviços gerais e da segurança do Quartel do Comando do Corpo de Bombeiros Militar do Rio Grande do Norte, competindo-lhe ainda, elaborar e redigir as "Ordens do Dia" e discursos do Comandante Geral e preparar os processos de seleção e agraciamento das diversas comendas institucionais. ANO 89 EDIÇÃO Nº 15.069 Av. Câmara Cascudo, 355 - Ribeira - Natal - RN - Cep 59025-280 - Fax (84) 3232-6794 Fones: Diretor Geral (84)3232-6780 - Publicações: (84) 3232-6785- Atendimento ao Assinante: (84) 3232-6786 - E-mail: dei@rn.gov.br - Diário Oficial online: www.diariooficial.rn.gov.br Assessor de Comunicação Social - Daniel Cabral de Oliveira Diretor Geral - Flávia Celeste Martini Assaf Página: 26 x 29 cm Originais para publicação: Word corpo 8 (Times New Roman) PUBLICAÇÕES Colunas: 06 - Largura: 4,2 cm Diário Oficial: do@rn.gov.br cm/coluna ......R$ 32,00 Total cm/pág. 174 cm Horário: 08:00 às 17:00 horas. EXEMPLAR AVULSO Do dia ............ R$ 1,50 Atrasado ..........R$ 4,00 Ao DEI se reserva o direito de recusar a publicação de matérias em desacordo com suas normas técnicas e quando suas fontes de origem não forem devidamente identificadas. Coleção anual - R$ 900,00 Coleção mensal - R$ 80,00* *Pedidos a partir de seis meses não terão cobrada a taxa referente ao CD Rom Diário Oficial 303 DE DEZEMBRO DE 2021',
            'dispositivos': ['Parágrafo único. A função de Ajudante Geral recairá sobre Oficial Superior Bombeiro Militar de livre escolha do Comandante Geral, o qual acumulará com a função de Chefe de Gabinete do Comando Geral. Da Comissão Permanente de Ética e Disciplina'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 22',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. II — Assessoramento',
            'caput': 'Art. 24. A Unidade de Controle Interno (UCI) é o ór gão responsável pela análise dos processos de aquisição de materiais e equipamentos de qualquer natureza, con- tratação de serviços e despesas com pessoal no âmbito do CBMRN, competindo- lhe:',
            'dispositivos': ['I - controlar e fiscalizar todas as atividades relativas à compra e pagamento do CBMRN;', 'II - conferir cálculos e planilhas de toda compra do CBMRN;', 'III - conferir índices de reajustes ou de atualização aplicados nos contratos do CBMRN;', 'IV - exercer o controle contábil, financeiro, orçamentário, operacional e patrimoni- al, quanto à legalidade, legitimidade, economicidade e razoabilidade;', 'V - exercer o Controle Interno das operações de créditos, bem como da execução de convênios, contratos e licitações, relativos aos direitos e haveres do CBMRN;', 'VI - avaliar a correta aplicação das disposições contidas na legislação em vigor quanto aos limites de gastos e outras decorrentes, apresentando informações que auxiliem neste processo;', 'VII - monitorar e colaborar na implementação e no cumprimento de todas as dis - posições contidas nas deliberações expedidas pelos Ór gãos de Controle Externos;', 'VIII - supervisionar os processos de controles internos;', 'IX - outras atribuições definidas em lei. Da Comissão de Promoção de Oficiais'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 24',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. II — Assessoramento',
            'caput': 'Art. 25. A Comissão de Promoção de Oficiais do CBMRN (CPO/CBMRN) é o órgão de processamento das promoções dos Oficiais.',
            'dispositivos': ['Parágrafo único. A CPO/CBMRN desempenhará suas atribuições, as quais envolvem avaliação de mérito de oficial BM, conforme legislação específica, e a sua atuação com a respectiva documentação terão classificação sigilosa. Da Comissão de Promoção de Praças'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 25',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. II — Assessoramento',
            'caput': 'Art. 26. A Comissão de Promoção de Praças do Corpo de Bombeiros Militar do Rio Grande do Norte (CPP/CBMRN) é um órgão consultivo e deliberativo integrante da estrutura administrativa do CBMRN, competindo-lhe:',
            'dispositivos': ['I - assessorar , estudar e propor ao Comandante Geral as diretrizes que visem a garantir às Praças do CBMRN o direito à promoção de forma seletiva, gradual e sucessiva;', 'II - deliberar , no âmbito da sua competência, acerca da existência ou não do preenchimento dos requisitos objetivos ou subjetivos ensejadores da promoção das Praças do CBMRN;', 'III - desempenhar atividades correlatas determinadas pelo Comandante Geral, bem como outras funções definidas na legislação em vigor. Da Assessoria de Projetos, Processos e Convênios'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 26',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. II — Assessoramento',
            'caput': 'Art. 27. A Assessoria de Projetos, Processos e Convênios é o ór gão de assessora- mento do Comandante Geral, destinado a fazer a gestão, propor , elaborar e acom - panhar, bem como apresentar a prestação de contas dos convênios e projetos pactu- ados com outros órgãos públicos ou privados. Da Comissão de Planejamento Estratégico',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 27',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. II — Assessoramento',
            'caput': 'Art. 28. A Comissão de Planejamento Estratégico é o ór gão de assessoramento do comandante-geral destinado a implantar e controlar o plano estratégico e de ação da corporação, implantar a doutrina de planejamento, estabelecer as diretrizes de planejamento, estabelecer a métrica dos planos em conjunto com demais setores, bem como programas relativos à instituição, previstos em outras leis. Da Assessoria Parlamentar',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 28',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. II — Assessoramento',
            'caput': 'Art. 29. A atividade da Assessoria Parlamentar (ASPAR) destina-se ao acompan - hamento dos assuntos de interesse institucional junto ao Poder Legislativo Federal e Estadual, e tem como missão assessorar diretamente o Comando Geral do Corpo de Bombeiros Militar do Estado Rio Grande do Norte, com o propósito de subsidiar o processo decisório no âmbito do comando da corporação, mantendo-os informa - dos acerca dos temas tratados nas referidas sedes do poder legislativo, além de realizar ações de proteção e garantia dos interesses da instituição e de seus profis - sionais e outras missões correlatas designadas pelo Comandante Geral. Da Assessoria de Inteligência',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 29',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. II — Assessoramento',
            'caput': 'Art. 30. A Assessoria de Inteligência é o Ór gão de Assessoramento Superior incumbido de assessorar o Comandante Geral nos assuntos de controle interno, identificação e avaliação dos pontos críticos que possam ameaçar a comunidade potiguar. O Assessor de Inteligência tem a competência de produzir informações estratégicas com vistas ao preparo e emprego do Corpo de Bombeiros Militar .',
            'dispositivos': ['Parágrafo único. A Chefia da Assessoria de Inteligência será exercida por um Oficial Superior do Quadro de Oficiais Combatentes. Da Assessoria de Comunicação Social'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 30',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. II — Assessoramento',
            'caput': 'Art. 31. A Assessoria de Comunicação Social é o Ór gão de Assessoramento Superior incumbido de assessorar o Comandante Geral nos assuntos de devulgação da imagem, da missão, das ações e dos objetivos estratégicos da Corporação.',
            'dispositivos': ['Parágrafo único. AASSECOM está estruturada nas áreas de atendimento à impren- sa, publicidade, Cerimonial e Jornalismo. Do Comando Operacional Bombeiro Militar'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 31',
            'match': 'exata',
        },
    ],
    ('competencias-direcao', 'rn'): [
        {
            'heading': 'TÍT. II, Cap. I — Direção Superior',
            'caput': 'Art. 12. O Comandante Geral do Corpo de Bombeiros Militar do Estado do Rio Grande do Norte é o responsável pelo comando, coordenação, supervisão e orien - tação da execução das atividades da Corporação.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 12',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. I — Direção Superior',
            'caput': 'Art. 13. Compete ao Comandante Geral do Corpo de Bombeiros Militar do Estado do Rio Grande do Norte:',
            'dispositivos': ['I - assessorar o Governador do Estado e o Secretário de Estado da Segurança Pública e da Defesa Social nos assuntos relacionados às atividades de bombeiro militar, defesa civil e aguarda militar do meio ambiente;', 'II - dirigir, coordenar, supervisionar e orientar as atividades técnicas, operacionais e administrativas da Corporação;', 'III - fazer cumprir as leis, normas e regulamentos da Corporação;', 'IV - editar portarias e demais normas e diretrizes de serviço;', 'V - submeter ao Secretário de Estado da Segurança Pública e da Defesa Social, no início de cada exercício, o relatório das atividades desenvolvidas pelo Corpo de Bombeiros Militar durante o ano anterior, sugerindo a adoção de medidas legislati- vas e as providências adequadas ao seu aperfeiçoamento, como estudos, projetos, programas e propostas para a or ganização, o funcionamento e a atuação da Instituição, com vista ao desenvolvimento da segurança;', 'VI - determinar a instauração de sindicância e de processo administrativo discipli - nar, bem como aplicar as penalidades de sua competência;', 'VII - convocar e presidir as reuniões do Conselho Superior do Corpo de Bombeiros Militar;', 'VIII - celebrar convênios e ajustes com entidades públicas e privadas visando for - mar parcerias com vistas à otimização das funções institucionais do Corpo de Bombeiros Militar;', 'IX - presidir a elaboração da proposta orçamentária do Corpo de Bombeiros Militar, bem como praticar os atos necessários de gestão orçamentária e financeira;', 'X - determinar a realização de licitações, inexigi-las, dispensá-las, aprová-las, anulá-las ou revogá-las;', 'XI - presidir e designar os demais membros da Comissão Or ganizadora e Examinadora dos concursos para ingresso na carreira de oficiais e praças, bem como as condições necessárias à inscrição de candidato, atendendo previamente às normas estabelecidas pelo Conselho Superior do Corpo de Bombeiros Militar;', 'XII - antecipar ou prorrogar a jornada normal de trabalho, bem como definir nor - mas e critérios para o cumprimento do expediente regular do Corpo de Bombeiros Militar;', 'XIII - propor e conceder gratificações, na forma da legislação vigente;', 'XIV - designar ou dispensar os ocupantes de comando, diretorias, chefias, funções gratificadas ou de confiança, bem como os seus eventuais substitutos;', 'XV - disciplinar o uso dos uniformes militares, nos termos da legislação em vigor;', 'XVI - decidir nos processos relativos aos interesses do Corpo de Bombeiro Militar, inclusive os referentes a direitos e deveres dos oficiais e praças e dos servidores civis da Instituição;', 'XVII - determinar a publicação semestral da relação de antiguidade dos Oficiais e Praças da Corporação em Boletim Geral, até 31de janeiro e 31 de julho;', 'XVIII - determinar a realização de exame de sanidade para a verificação da inca - pacidade física ou mental de Praças e Oficiais, temporária ou definitiva, por inter - médio da Junta Médica da Instituição;', 'XIX - desempenhar outras atividades definidas em lei.'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 13',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. I — Direção Superior',
            'caput': 'Art. 14. O car go de Comandante Geral é privativo de oficial superior da ativa, do último posto do Quadro de Oficiais Combatentes (QOCBM), que haja concluído o Curso Superior de Bombeiro Militar , ou equivalente, sendo nomeado e exonerado por ato do Governador do Estado.',
            'dispositivos': ['Parágrafo único. Quando a escolha para o exercício do cargo de Comandante Geral não incidir sobre o Oficial mais antigo, o escolhido terá precedência funcional e hierárquica sobre os demais. Do Subcomandante Geral'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 14',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. I — Direção Superior',
            'caput': 'Art. 15. O Subcomandante Geral do Corpo de Bombeiros Militar do Estado do Rio Grande do Norte é o auxiliar direto do Comandante Geral da Corporação, substi - tuindo-o em seus eventuais impedimentos, desempenhando as atribuições previstas em Lei e regulamentos, competindo-lhe:',
            'dispositivos': ['I - substituir o Comandante Geral nas suas ausências ou impedimentos legais;', 'II - assessorar o Comandante Geral na gestão administrativa, técnica e operacional da corporação, por meio do controle das atividades dos ór gãos de direção geral e assessoramento;', 'III - coordenar a elaboração do planejamento estratégico da corporação, assim como aplicá-lo;', 'IV - assessorar o Comandante Geral na formulação da doutrina de preparo e emprego da tropa e na definição das políticas de comando;', 'V - assegurar a atuação convergente e dinâmica dos órgãos de direção geral, asses- soramento e execução;', 'VI - elaborar e estabelecer ordens, instruções, diretrizes, planos e orientações perti- nentes à implementação das políticas do Comandante Geral, visando à consecução dos objetivos e metas estabelecidas no planejamento estratégico ou planos de ação;', 'VII - supervisionar a execução das diretrizes, planos e ordens;', 'VIII - realizar inspeção periódica nas Or ganizações Bombeiro Militar (OBM);', 'IX - desempenhar outras atribuições delegadas pelo Comandante Geral;', 'X - presidir a Comissão de Promoção de Praças (CPP);', 'XI - encarregar-se pelo nível de disciplina dos militares da Corporação;', 'XII - presidir , como membro nato, as atividades desenvolvidas na Comissão Permanente de Ética e Disciplina (CPED); e', 'XIII - exercer demais atribuições definidas na legislação em vigor .'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 15',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. I — Direção Superior',
            'caput': 'Art. 16. O cargo em comissão de Subcomandante Geral é privativo de oficial supe- rior da ativa, do último posto do Quadro de Oficiais Combatentes, que haja con - cluído o Curso Superior de Bombeiro Militar , ou equivalente, sendo nomeado e exonerado por ato do Governador do Estado. Caso a escolha do Subcomandante Geral não recaia no oficial mais antigo, este terá precedência hierárquica e fun - cional sobre os demais oficiais, excetuando-se o Comandante Geral.',
            'dispositivos': ['Parágrafo único. O substituto eventual do Subcomandante Geral será o Oficial do Quadro de Oficiais Combatente mais antigo, em atividade na Corporação. Do Conselho Superior do Corpo de Bombeiros Militar'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 16',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. I — Direção Superior',
            'caput': 'Art. 17. O Conselho Superior do Corpo de Bombeiros Militar, órgão de deliberação coletiva, assessora o Comandante Geral na formulação e avaliação de políticas estratégicas e na fixação de diretrizes de gerenciamento administrativo e opera - cional do Corpo de Bombeiros Militar , além de exercer as seguintes atribuições institucionais:',
            'dispositivos': ['I - aprovar a proposta orçamentária do Corpo de Bombeiros Militar;', 'II - aprovar o relatório geral e anual do Corpo de Bombeiros Militar;', 'III - deliberar sobre qualquer matéria de interesse do Corpo de Bombeiros Militar , que lhe seja submetida por quaisquer de seus membros, com anuência do Comandante Geral;', 'IV - dirimir quaisquer dúvidas ou omissões atinentes à competência dos órgãos que integram o Corpo de Bombeiros Militar;', 'V - analisar regras, critérios e princípios para a realização de concurso público para ingresso nas carreiras de Oficiais e Praças da Instituição, propostas pelo Comandante Geral, observado o disposto em lei;', 'VI - estabelecer o padrão dos símbolos do Corpo de Bombeiros Militar;', 'VII - deliberar sobre os processos de promoção de Oficiais e Praças da Corporação;', 'VIII - estabelecer as diretrizes do Fundo de Reaparelhamento do Corpo de Bombeiros Militar (FUNREBOM);', 'IX - elaborar o seu regimento interno.'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 17',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. I — Direção Superior',
            'caput': 'Art. 18. Compõem o Conselho Superior do Corpo de Bombeiros Militar:',
            'dispositivos': ['I - Comandante Geral, que o presidirá;', 'II - Subcomandante Geral;', 'III - Comandante Operacional Bombeiro Militar;', 'IV - Diretor de Logística, Orçamento e Finanças;', 'V - Diretor de Gestão de Pessoas, Ensino e Instrução;', 'VI - Diretor de Atividades Técnicas;', 'VII - Ajudante Geral. Do Gabinete do Comando Geral'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 18',
            'match': 'exata',
        },
    ],
    ('competencias-execucao', 'rn'): [
        {
            'heading': 'TÍT. II, Cap. III — Execução (Cmdo Op BM, DLOF)',
            'caput': 'Art. 32. O Comando Operacional Bombeiro Militar (Cmdo Op BM) é o ór gão responsável pelo planejamento, orientação normativa, coordenação, fiscalização, controle e execução das atividades operacionais no campo de atuação da Corporação.',
            'dispositivos': ['Parágrafo único. O Comando Operacional Bombeiro Militar terá a seguinte or ga- nização:', 'I - Comandante;', 'II - Secretaria;', 'III - Estado-Maior Operacional (EM Op);', 'IV - Centro de Operações do CBMRN (COCB);', 'V - Comissão de Defesa Civil;', 'VI - 1º Grupamento de Bombeiros Militar - (1º GBM);', 'VII - 2º Grupamento de Bombeiros Militar - (2º GBM);', 'VIII - Grupamento de Bombeiros Marítimo - (GBMAR);', 'IX - Subgrupamento Independente de Bombeiros Militar de Atendimento Pré-hos- pitalar - (S.I.B.M -APH);', 'X - 1º Subrupamento Independente de Bombeiros Militar (1º S.I.B.M); e', 'XI - 2º Subrupamento Independente de Bombeiros Militar (2º S.I.B.M). Subseção Única Do Estado-Maior Operacional'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 32',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. III — Execução (Cmdo Op BM, DLOF)',
            'caput': 'Art. 33. O Estado-Maior Operacional (EM Op), subordinado ao comandante opera- cional, é a estrutura de assessoramento responsável pela coordenação setorial do Comando Operacional, atuando na supervisão das atividades de proteção e defesa civil, proteção do meio ambiente, combate a incêndio, resgate, busca e salvamento de vidas e bens em todo o Estado, tendo a seguinte composição:',
            'dispositivos': ['I - 1ª SEÇÃO - B/1;', 'II - 2ª SEÇÃO - B/2;', 'III - 3ª SEÇÃO - B/3;', 'IV - 4ª SEÇÃO - B/4.', '§ 1º O Subcomandante Operacional e Chefe do EM OP estabelece as normas para a coordenação dos trabalhos de EM e proporcionará rápida, eficiente e segura asses- soria ao Comandante Operacional, competindo-lhes as seguintes atribuições:', 'I - realizar estudos de situação;', 'II - apresentar propostas;', 'III - elaborar planos e ordens;', 'IV - supervisionar a execução dos planos e ordens previstos no inciso anterior;', 'V - substituir o Comandante Operacional; e', 'VI - desempenhar as atribuições previstas em lei e regulamentos.', '§ 2º A 1ª Seção é a responsável pela supervisão da or ganização e emprego de pes- soal, controle de efetivo e de seu recompletamento.', '§ 3º A 2ª Seção é a responsável pela coleta de dados e produção de informes, pela orientação e auxílio a outros Oficiais no trato da produção de conhecimentos de inteligência em suas OBMs, bem como pela realização de estudos de situações de inteligência e contrainteligência.', '§ 4º A 3ª Seção é a responsável pelo planejamento de operações, or ganização e instrução, pela mobilização e desmobilização, ativação e desativação de operações e pela elaboração e coordenação dos planos de operações futuras e revisão dos pro- cedimentos já existentes.', '§ 5º A 4ª Seção é a responsável pela orientação do planejamento das prioridades e da distribuição de apoio logístico para as diferentes atividades operacionais, por propor a distribuição de equipamentos, suprimentos e por determinar a prioridade das necessidades de manutenção de material de emprego operacional, bem como da adequação de material de pronto emprego.', '§ 6º Como orientação para elaboração de doutrina própria, o EM Op seguirá, a títu- lo de guia para funcionamento, com modificações apropriadas, a prescrição do manual C 101-5 - (EST ADO-MAIOR E ORDENS) do Exército Brasileiro, por descrever a or ganização e funcionamento das principais atividades e as respons - abilidades e deveres de seus oficiais, podendo adaptar a or ganização, em face da missão e dos recursos disponíveis.', '§ 7º O Centro de Operações do Corpo de Bombeiros (COCBM) tem por com - petência coordenar o atendimento e despachos de ocorrências bombeiro-militar e de proteção e defesa civil, bem como coordenar , orientar e disciplinar as telecomuni - cações operacionais no âmbito do CBMRN, tendo a seguinte composição:', 'I - Chefe do Centro de Operações;', 'II - Seção de Operações;', 'III - Seção de Comunicações;', 'IV - Seção de Apoio.', '§ 8º A Comissão de Defesa Civil (CODEC) tem por competência a coordenação de ações preventivas e de socorro emer gencial, com vistas a evitar ou minimizar os efeitos desastrosos de situações adversas que possam causar danos à sociedade, pro- movendo estudo em áreas de risco, organizando banco de dados em mapeamento de áreas críticas relacionadas com as ameaças e vulnerabilidade aos riscos naturais de maior prevalência no Estado, tendo a seguinte composição:', 'I - Presidente da CODEC;', 'II - Secretaria;', 'III - Subcomissão de ações preventivas;', 'IV - Subcomissão de ações de emergência;', 'V - Subcomissão de ações de apoio.', '§ 9º O Primeiro Grupamento de Bombeiros Militar (1º GBM) é a unidade opera - cional do Corpo de Bombeiros Militar , responsável pela operacionalização das atividades de prevenção e combate a incêndio, busca e resgate de pessoas e bens, compreendendo as atividades de salvamento terrestre, e em altura, bem como a defesa do meio ambiente, atuando com o órgão estadual encarregado da guarda mil- itar do patrimônio ambiental do Estado, de modo a zelar pela prevenção e combate a incêndios florestais, bem como pela fiscalização efetiva quanto ao cumprimento da legislação ambiental no que diz respeito à preservação da fauna e da flora e, ainda, à proteção contra as ações de degradação do solo, dos areados mananciais aquíferos na capital e região metropolitana do Estado, tendo a seguinte composição:', 'I - Comandante do 1º GBM;', 'II - Subcomandante;', 'III - Secretaria;', 'IV - Divisão Administrativa;', 'V - Divisão de Operações;', 'VI - 1º Subgrupamento de Bombeiros;', 'VII - 2º Subgrupamento de Bombeiros;', 'VIII - 3º Subgrupamento de Bombeiros;', '§ 10. O Segundo Grupamento de Bombeiros Militar (2º GBM) é a unidade opera - cional do Corpo de Bombeiros Militar , responsável pela operacionalização das atividades de prevenção e combate a incêndio, de busca e resgate de pessoas e bens, compreendendo as atividades de salvamento terrestre, em altura e aquático, e atendimento pré-hospitalar de urgência, compreendendo as ações de manutenção do suporte básico e avançado de vida, prestadas nos acidentes em via pública e rodovias, capaz de reduzir os casos de mortalidade por afecções causadas pelo trau- ma, bem como a defesa do meio ambiente, atuando com o ór gão estadual encar - regado da guarda militar do patrimônio ambiental do Estado, de modo a zelar pela prevenção e combate a incêndios florestais, bem como pela fiscalização efetiva quanto ao cumprimento da legislação ambiental no que diz respeito à preservação da fauna e da flora e, ainda, à proteção contra as ações de degradação do solo, do ar e dos mananciais aquíferos nos municípios localizados no interior do Estado do Rio Grande do Norte, tendo a seguinte composição:', 'I - Comandante do 2º GBM;', 'II - Subcomandante;', 'III - Secretaria;', 'IV - Divisão Administrativa;', 'V - Divisão de Operações;', 'VI - 1º Subgrupamento de Bombeiros (Mossoró/RN);', 'VII - 2º Subgrupamento de Bombeiros (Caicó/RN);', 'VIII - 3º Subgrupamento de Bombeiros (Pau dos Ferros/RN).', '§ 11. O Grupamento de Bombeiros Marítimo (GBMAR) é a unidade operacional do Corpo de Bombeiros Militar, responsável pela operacionalização das diretrizes e procedimentos referentes aos serviços e técnicas de salvamento aquático, procedi - mentos de primeiros socorros e noções básicas de marinharia, visando a busca e res- gate de pessoas e bens, compreendendo as atividades de salvamento aquático, a pre- venção contra afogamentos e a normalização e fiscalização de atividades esportivas e recreativas em áreas de risco em seu campo de atuação, tendo a seguinte com - posição:', 'I - Comandante do GBMAR;', 'II - Subcomandante;', 'III - Secretaria;', 'IV - Divisão Administrativa;', 'V - Divisão de Operações;', 'VI - 1º Subgrupamento Bombeiro Militar de Salvamento Aquático (1º SBMSA);', 'VII - 2º Subgrupamento Bombeiro Militar de Salvamento Aquático (2º SBMSA);', 'VIII - 3º Subgrupamento Bombeiro Militar de Salvamento Aquático (3º SBMSA).', '§ 12. Subgrupamento Independente de Bombeiros Militar de Atendimento Pré-hos- pitalar (S.I.B.M-APH) é a unidade operacional do Corpo de Bombeiros Militar do Estado responsável pelo serviço de atendimento pré-hospitalar de ur gência, com- preendendo as ações de manutenção do suporte básico e avançado de vida, prestadas nos acidentes em via pública e rodovias, capaz de reduzir os casos de mortalidade por afecções causadas pelo trauma, na capital e região metropolitana do Estado, tendo a seguinte composição:', 'I - Comandante do S.I.B.M-APH;', 'II - Subcomandante;', 'III - Secretaria;', 'IV - Divisão Administrativa;', 'V - Divisão de Operações;', 'VI - 1º Subseção de Bombeiros Militar de Atendimento Pré-hospitalar;', 'VII - 2º Subseção de Bombeiros Militar de Atendimento Pré-hospitalar;', 'VIII - 3º Subseção de Bombeiros Militar de Atendimento Pré-hospitalar.', '§ 13. O Primeiro Subgrupamento Independente de Bombeiros Militar (1º S.I.B.M) é a unidade operacional do Corpo de Bombeiros Militar , responsável pela opera - cionalização das atividades de prevenção e combate a incêndio, de busca e resgate de pessoas e bens, compreendendo as atividades de salvamento terrestre, em altura e aquático, e atendimento pré-hospitalar de ur gência, compreendendo as ações de manutenção do suporte básico e avançado de vida, prestadas nos acidentes em via pública e rodovias, capaz de reduzir os casos de mortalidade por afecções causadas pelo trauma, bem como é responsável pela defesa do meio ambiente, atuando com o órgão estadual encarregado da guarda militar do patrimônio ambiental do Estado, de modo a zelar pela prevenção e combate a incêndios florestais, bem como pela fiscalização efetiva quanto ao cumprimento da legislação ambiental no que diz respeito à preservação da fauna e da flora e, ainda, à proteção contra as ações de degradação do solo, do ar e dos mananciais aquíferos nos municípios localizados no interior do Estado do Rio Grande do Norte, tendo a seguinte composição:', 'I - Comandante do 1º S.I.B.M;', 'II - Subcomandante;', 'III - Secretaria;', 'IV - Divisão Administrativa;', 'V - Divisão de Operações', 'VI - 1º Grupo de Bombeiros Militar;', 'VII - 2º Grupo de Bombeiros Militar;', 'VIII - 3º Grupo de Bombeiros Militar.', '§ 14. O Segundo Subgrupamento Independente de Bombeiros Militar (2º S.I.B.M) é a unidade operacional do Corpo de Bombeiros Militar , responsável pela opera - cionalização das atividades de prevenção e combate a incêndio, de busca e resgate de pessoas e bens, compreendendo as atividades de salvamento terrestre, em altura e aquático, e atendimento pré-hospitalar de ur gência, compreendendo as ações de manutenção do suporte básico e avançado de vida, prestadas nos acidentes em via pública e rodovias, capaz de reduzir os casos de mortalidade por afecções causadas pelo trauma, bem como é responsável pela defesa do meio ambiente, atuando com o órgão estadual encarregado da guarda militar do patrimônio ambiental do Estado, de modo a zelar pela prevenção e combate a incêndios florestais, bem como pela fiscalização efetiva quanto ao cumprimento da legislação ambiental no que diz ANO 89 EDIÇÃO Nº 15.069 4 03 DE DEZEMBRO DE 2021Diário Oficial respeito à preservação da fauna e da flora e, ainda, à proteção contra as ações de degradação do solo, do ar e dos mananciais aquíferos nos municípios localizados no interior do Estado do Rio Grande do Norte, tendo a seguinte composição:', 'I - Comandante do 2º S.I.B.M;', 'II - Subcomandante;', 'III - Secretaria;', 'IV - Divisão Administrativa;', 'V - Divisão de Operações;', 'VI - 1º Grupo de Bombeiros Militar;', 'VII - 2º Grupo de Bombeiros Militar;', 'VIII - 3º Grupo de Bombeiros Militar. Da Diretoria de Logística, Orçamento e Finanças (DLOF)'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 33',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. III — Execução (Cmdo Op BM, DLOF)',
            'caput': 'Art. 34. A Diretoria de Logística, Orçamento e Finanças é responsável pela gestão das finanças da corporação, bem como pela gestão de logística da corporação, de modo a supervisionar, coordenar, controlar, fiscalizar e executar as atividades finan- ceiras, contábeis e orçamentárias e a aquisição, o suprimento, o armazenamento e a manutenção dos equipamentos, viaturas, bens móveis e imóveis, obras, instalações, transportes de matérias e pessoas, sendo ainda responsável por planejar, coordenar, executar e avaliar projetos e atividades relacionadas a investimentos, desenvolvi - mento, manutenção, inovação e segurança em tecnologia da informação, além de outras atividades correlatas.',
            'dispositivos': ['§ 1º O Subdiretor é o auxiliar direto do Diretor da DLOF e será o substituto even - tual do Diretor da DLOF, desempenhando as atribuições previstas em lei e regula - mentos.', '§ 2º O Subdiretor poderá acumular a função de Chefe da Secretaria Executiva da Diretoria de Logística, Orçamento e Finanças. Da Secretaria Executiva'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 34',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. III — Execução (Cmdo Op BM, DLOF)',
            'caput': 'Art. 35. A Secretaria Executiva é o ór gão responsável pelo assessoramento direto ao Diretor de Logística, Orçamento e Finanças, competindo-lhe ainda:',
            'dispositivos': ['I - acompanhar e coordenar as atividades desenvolvidas referentes aos processos administrativos e à gestão e fiscalização de contratos;', 'II - coordenar o recebimento e distribuição dos processos, partes e ofícios, encam - inhados à Diretoria;', 'III - elaborar as minutas de contrato, com base no termo de referência;', 'IV - coordenar os processos administrativos referentes a diárias de viagem e elabo- ração das propostas de concessão de diárias - PCD;', 'V - controlar os prazos de vigências dos contratos do CBMRN; e', 'VI - exercer outras atividades que lhe forem atribuídas pelo Diretor da DLOF .', '§ 1º O Centro de Planejamento e Instrução Processual de Contratações é incumbido de:', 'I - planejar , acompanhar e definir os critérios das contratações mediante a elabo - ração dos termos de referência e similares;', 'II - proceder com as análises de mercado, sendo responsável por instruir a abertura processual com os documentos necessários à contratualização;', 'III - acompanhar todos os processos de aquisição de bens e serviços até o até a assi- natura do instrumento contratual;', 'IV - organizar e manter atualizado o cadastro de fornecedores;', 'V - elaborar termos de referência e demais documentos necessários para as con - tratações, determinadas pelo Diretor da Diretoria de Logística, Orçamento e Finanças (DLOF);', 'VI - realizar pesquisa de preços, elaborando os mapas de pesquisas de preços e cal- cular os valores de referência para as contratações, utilizando como parâmetro a IN 05/2014 - SLTI/MPOG ou norma mais atual;', 'VII - elaborar banco de dados de termos de referência do CBMRN;', 'VIII - auxiliar no planejamento e execução das contratações realizadas pela Corporação;', 'IX - prestar assistência e assessoramento na criação, revisão e implantação de nor - mas e procedimentos relativos às contratações públicas;', 'X - elaborar o mapeamento dos processos de sua competência, criando os respec - tivos fluxogramas; e', 'XI - desempenhar outras atividades afins, por determinação do Diretor de Logística, Orçamento e Finanças.', '§ 2º O Centro de Gestão e Execução de Contratos é incumbido de:', 'I - gerenciar e executar os contratos firmados pelo CBMRN, devendo elaborar as minutas dos instrumentos de contratos, as assinaturas dos termos de contratos e dos instrumentos similares;', 'II - acompanhar o andamento de todos os processos de aquisição de bens e serviços a partir do momento em que estiverem prontos para a assinatura do instrumento contratual;', 'III - executar, auxiliado pelos fiscais, os contratos firmados pelo CBMRN;', 'IV - orientar e fiscalizar as atuações dos fiscais de contratos;', 'V - manter controle dos prazos de encerramentos dos contratos continuados, a fim de realizar os aditivos pertinentes nos prazos adequados;', 'VI - gerenciar o recebimento dos materiais, solicitando ao Diretor da Diretoria de Logística, Orçamento e Finanças (DLOF) a convocação da Comissão de Recebimento quando julgar necessário;', 'VII - gerenciar e elaborar os aditivos e apostilamentos contratuais necessários;', 'VIII - instruir os processos sancionatórios para apurar a materialidade e autoria de condutas das sociedades contratadas ou que participaram do processo licitatório, que tenham atuado de forma irregular;', 'IX - prestar assistência e assessoramento ao Diretor de Logística, Orçamento e Finanças na criação, revisão e implantação de normas e procedimentos relativos às contratações públicas;', 'X - elaborar o mapeamento dos processos de sua competência, criando os respec - tivos fluxogramas;', 'XI - desempenhar outras atividades afins por determinação do Diretor de Logística, Orçamento e Finanças.', '§ 3º A Seção de Expediente é responsável por:', 'I - efetuar o recebimento de processos e/ou documentos, separando e distribuindo aos setores ou autoridade competente;', 'II - redigir e preparar a agenda de despachos do expediente do Diretor de Logística, Orçamento e Finanças;', 'III - fornecer informações administrativas aos demais ór gãos do Corpo de Bombeiros Militar quando solicitado;', 'IV - conferir e solicitar informações necessárias à instrução de processos relaciona- dos às compras de materiais, equipamentos, contratação de serviços e obras;', 'V - minutar a correspondência oficial, portarias e demais atos administrativos de sua área de atuação;', 'VI - instruir e executar os processos administrativos referentes à diária de viagem e elaboração das propostas de concessão de diárias - PCD; e', 'VII - exercer outras atividades que lhe forem atribuídas pelo Diretor da DLOF ou pelo secretário Executivo. Da Comissão Permanente de Licitação'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 35',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. III — Execução (Cmdo Op BM, DLOF)',
            'caput': 'Art. 36. A Comissão Permanente de Licitação é o órgão responsável pelo processo de aquisição de material, cujo valor esteja compreendido entre os limites estabele - cidos em Lei, competindo-lhe:',
            'dispositivos': ['I - assessorar o Comando Geral na pesquisa mercadológica dos bens e serviços a serem licitados pelo CBMRN;', 'II - licitar todo o material acima do valor previsto em Lei;', 'III - desempenhar outras atividades correlatas. Do Centro de Logística'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 36',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. III — Execução (Cmdo Op BM, DLOF)',
            'caput': 'Art. 37. Centro de Logística é o ór gão que tem como finalidade o planejamento, coordenação, fiscalização e controle das necessidades de suprimento e manutenção de materiais, equipamentos e instalações, competindo-lhe:',
            'dispositivos': ['I - realizar o planejamento para aquisição de material e execução de serviços;', 'II - fiscalizar as atividades de manutenção de material, equipamentos e das insta - lações;', 'III - realizar a execução e controle das atividades de suprimento;', 'IV - outras atribuições determinadas pelo Comando Geral ou pelo Diretor de Gestão Logística, Financeira e Orçamentária. Do Centro de Tecnologia da Informação e Comunicações'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 37',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. III — Execução (Cmdo Op BM, DLOF)',
            'caput': 'Art. 38. O Centro de Tecnologia da Informação e Comunicações destina-se a asses- sorar o Comando Geral da Corporação na definição das políticas e diretrizes da Corporação na área de informática e processamento de dados, bem como a plane - jar, coordenar, executar e avaliar projetos e atividades relacionadas a investimentos, desenvolvimento, manutenção, inovação e segurança em tecnologia da informação, competindo-lhe ainda:',
            'dispositivos': ['I - atuar na execução e controle do sistema de informática e banco de dados do CBMRN;', 'II - assessorar o CRH na manutenção atualizada das informações referentes aos mil- itares e servidores do CBMRN;', 'III - assessorar os setores de compras, contratos e convênios do CBMRN na criação e manutenção de cadastro de todos fornecedores do CBMRN;', 'IV - realizar treinamentos com os usuários do sistema de informática do CBMRN;', 'V - realizar manutenção periódica dos equipamentos que compõem a rede de infor- mática do CBMRN;', 'VI - desempenhar outras atividades correlatas. Do Centro de Administração Financeira e Orçamentária'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 38',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. III — Execução (Cmdo Op BM, DLOF)',
            'caput': 'Art. 39. O Centro de Administração Financeira e Orçamentária é o ór gão respon- sável pelas atividades específicas da gestão orçamentário-financeira, pela super - visão destas atividades junto aos demais ór gãos da Corporação e pelo repasse de recursos orçamentários, de acordo com o planejamento estabelecido, competindo-lhe:',
            'dispositivos': ['I - elaborar programa de planejamento, controle e fiscalização das atividades rela - cionadas com a política de pessoal, de admissão, de capacitação técnica, de remu - neração do pessoal e de prevenção de acidentes do trabalho;', 'II - alocar recursos orçamentários e financeiros para os diferentes setores de ativi - dade do CBMRN;', 'III - controlar os custos com pessoal e manter atualizado o cadastro central de recur- sos humanos;', 'IV - realizar atividades específicas da gestão financeira, supervisão destas junto aos demais órgãos da corporação e o repasse de recursos orçamentários, de acordo com o planejamento estabelecido;', 'V - realizar atividades específicas da gestão financeira, supervisão destas junto aos demais órgãos da corporação e o repasse de recursos orçamentários, de acordo com o planejamento estabelecido;', 'VI - elaborar o planejamento orçamentário do CBMRN, da programação financeira, da captação de recursos financeiros e a confecção de convênios com ór gãos e enti- dades públicas e privadas;', 'VII - acompanhar , controlar e fiscalizar a execução orçamentária-financeira do CBMRN;', 'VIII - apropriar, analisar e controlar custos;', 'IX - empenhar, liquidar e pagar as despesas da respectiva unidade orçamentária;', 'X - promover o registro de atos orçamentários e financeiros, consignações e depósi- tos;', 'XI - manter atualizadas as informações sobre a posição dos saldos orçamentários e financeiros;', 'XII - elaborar balancetes e prestações de contas a serem encaminhados aos ór gãos internos e externos;', 'XIII - manter registrados e arquivados contratos e obrigações de responsabilidade do CBMRN;', 'XIV - assessorar na elaboração da proposta de Lei Orçamentaria Anual (LOA), na Lei de Diretrizes Orçamentárias (LDO), e ainda acompanhar e atualizar a execução do Plano Plurianual (PPA), alusivos ao CBMRN;', 'XV - realizar auditorias em todas as repartições do CBMRN nas passagens de comando ou por solicitação do Comandante Geral da Corporação;', 'XVI - desempenhar outras atividades correlatas. Da Diretoria de Gestão de Pessoas, Ensino e Instrução (DGPEI)'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 39',
            'match': 'exata',
        },
    ],
    ('disciplina-correicao', 'rn'): [
        {
            'heading': 'TÍT. II, Cap. II — Assessoramento',
            'caput': 'Art. 23. A Comissão Permanente de Ética e Disciplina será nomeada anualmente, por ato do Comandante Geral do CBMRN, podendo ser reconduzida por iguais e sucessivos períodos, limitado até 60 (sessenta) meses, e será presidida pelo Subcomandante Geral, competindo-lhe analisar o nível disciplinar da tropa, propor medidas de correção, acompanhamento e fiscalização dos processos e procedimen- tos administrativos disciplinares, examinar fatos, circunstâncias e consequências de atos que afetem o bom desempenho da atividade Bombeiro Militar ou decoro da Corporação. Da Unidade de Controle Interno',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 23',
            'match': 'parcial',
        },
    ],
    ('disposicoes-finais', 'rn'): [
        {
            'heading': 'TÍT. II, Cap. IV — Prescrições Diversas',
            'caput': 'Art. 45. Os cargos de Diretores serão ocupados por Coronel ou Tenente-Coronel do QOCBM, ficando a critério do Comandante Geral as respectivas designações.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 45',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. IV — Prescrições Diversas',
            'caput': 'Art. 46. Os membros de Comissões, Assessorias e da UCI, não ocuparão vaga no Quadro Or ganizacional de Distribuição (QOD) da Corporação, sendo designados por ato do Comandante Geral, que decidirá se as respectivas funções serão exercidas acumulativamente com outras funções.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 46',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. IV — Prescrições Diversas',
            'caput': 'Art. 47. Fica delegada competência ao Comandante Geral do CBMRN para criar , transformar, extinguir, denominar, localizar e estruturar os órgãos de direção, de assessoramento e de execução do Corpo de Bombeiros Militar, de acordo com as suas com- petências específicas e dentro do limite de efetivo estabelecido em lei.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 47',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. IV — Prescrições Diversas',
            'caput': 'Art. 48. Compete ao Comandante Geral do CBMRN editar atos definindo o quadro or ganizacional de distribuição (QOD) das Organizações Bombeiro Militar (OBM), detalhando a distribuição do seu efetivo, respeitando o limite de efetivo fixado em lei, bem como estabelecer a área de circunscrição das OBMs do Comando Operacional Bombeiro Militar e da Diretoria de Atividades Técnicas.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 48',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. II, Cap. IV — Prescrições Diversas',
            'caput': 'Art. 49. As Diretorias e o Comando Operacional Bombeiro Militar serão efetivados em até 30 (trinta) dias, período consider - ado como transição para passagem das atribuições da estrutura anterior para a atual, a contar da publicação deste Decreto em Diário Oficial do Estado.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 49',
            'match': 'exata',
        },
    ],
    ('disposicoes-preliminares', 'rn'): [
        {
            'heading': 'TÍT. I, Cap. I — Disposições Gerais',
            'caput': 'Art. 1º O Corpo de Bombeiros Militar do Estado, instituição permanente, força auxiliar e reserva do Exército Brasileiro, or ganizado com base na hierarquia e na disciplina, destina-se à execução das atividades de proteção e defesa civil e aos serviços específicos de bombeiros militares, bem como à participação, por intermé- dio de organismos especializados, na defesa do meio ambiente.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 1',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. I — Disposições Gerais',
            'caput': 'Art. 2º São funções institucionais do Corpo de Bombeiros Militar , dentre outras:',
            'dispositivos': ['I - atuar na execução das atividades de proteção e defesa civil;', 'II - realizar os serviços de prevenção e combate aos incêndios;', 'III - participar , por meio de ór gãos especializados, da defesa do meio ambiente, atuando como órgão estadual encarregado da guarda militar do patrimônio ambien- tal do Estado, de modo a zelar pela prevenção e combate a incêndios florestais, bem como pela fiscalização efetiva quanto ao cumprimento da legislação ambiental no que diz respeito à preservação da fauna e da flora e, ainda, à proteção contra as ações de degradação do solo, do ar e dos mananciais aquíferos;', 'IV - realizar atividades de resgate, busca e salvamento;', 'V - fiscalizar as atividades de segurança contra incêndio e pânico;', 'VI - realizar atividades auxiliares de socorros de ur gência e atendimento de emergência pré-hospitalar;', 'VII - desempenhar atividades educativas de defesa civil, prevenção e combate a incêndios, socorros de urgência e proteção ao meio ambiente;', 'VIII - normatizar e realizar perícias de incêndios e explosões relacionadas com a sua competência;', 'IX - notificar, isolar, embargar, multar e interditar, no âmbito de sua competência, as obras, habitações, serviços, locais de uso público e privado que não ofereçam condições de segurança, devendo aplicar aos responsáveis infratores as penalidades previstas em lei;', 'X - fiscalizar, no âmbito de sua competência, os serviços de armazenamento e trans- porte de produtos especiais e perigosos, visando à proteção das pessoas, do patrimônio público e privado e do meio ambiente;', 'XI - fiscalizar , controlar e prevenir , no âmbito de sua competência, a prática de atividades de esporte e recreação aquática, de excursões em florestas, matas e áreas de preservação ambiental, bem como escaladas e montanhismo, onde exista risco à integridade de pessoas;', 'XII - desenvolver pesquisa científica em seu campo de atuação funcional;', 'XIII - exercer outras atividades correlatas.'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 2',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. I — Disposições Gerais',
            'caput': 'Art. 3º O Corpo de Bombeiros Militar subordina-se administrativa e operacional - mente ao Governador do Estado, por intermédio da Secretaria de Estado da Segurança Pública e da Defesa Social (SESED), desenvolvendo suas atribuições, sempre que necessário, de modo integrado com os demais órgãos responsáveis pela segurança pública do Estado.',
            'dispositivos': ['Parágrafo único. O Corpo de Bombeiros Militar é comandado por oficial da ativa do último posto da Corporação do Quadro de Oficiais Combatentes, com com - petência para os atos de gestão orçamentária e financeira.'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 3',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. I — Disposições Gerais',
            'caput': 'Art. 4º No exercício de suas funções, os integrantes do Corpo de Bombeiros Militar exercerão o poder de polícia administrativa.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 4',
            'match': 'exata',
        },
    ],
    ('ensino-instrucao', 'rn'): [
        {
            'heading': 'TÍT. II, Cap. III — DGPEI (pessoas + ensino)',
            'caput': 'Art. 40. A Diretoria de Gestão de Pessoas, Ensino e Instrução é responsável pelo gerenciamento de pessoas da Corporação, incumbindo-se:',
            'dispositivos': ['I - da supervisão, coordenação, controle, fiscalização e execução das atividades relacionadas com o ingresso, identificação, classificação, movimentação, cadastros, avaliações, promoções, direitos e deveres;', 'II - do acompanhamento e controle de inativos e pensionistas;', 'III - das orientações e acompanhamento quanto a saúde do efetivo;', 'IV - pela gestão do ensino e instrução da corporação;', 'V - pela política de ensino, atuando na supervisão, na coordenação, na fiscalização, no controle e na execução das atividades de ensino, instrução e pesquisa rela - cionadas com a formação, o aperfeiçoamento e a especialização de oficiais e praças; e', 'VI - desempenhar outras atividades correlatas.', '§ 1º O Subdiretor é o auxiliar direto do Diretor da DGPEI, e será o substituto even- tual do Diretor, desempenhando as atribuições previstas em lei e regulamentos.', '§ 2º O Subdiretor poderá acumular a função de Chefe do Centro Superior de Formação e Aperfeiçoamento. Do Centro de Recursos Humanos'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 40',
            'match': 'parcial',
        },
        {
            'heading': 'TÍT. II, Cap. III — DGPEI (pessoas + ensino)',
            'caput': 'Art. 41. O Centro de Recursos Humanos é o órgão responsável pelo planejamento, controle e fiscalização das atividades relacionadas com a política de pessoal, com - petindo-lhe:',
            'dispositivos': ['I - manter atualizados os registros relativos aos direitos e deveres dos militares do CBMRN;', 'II - manter atualizadas as anotações devidas na ficha funcional dos militares do CBMRN;', 'III - planejar, coordenar e controlar todos os assuntos relacionados com o pessoal pensionistas e inativos;', 'IV - assessorar às Comissões de Promoção;', 'V - assessorar todo o recrutamento e seleção para ingresso ao CBMRN;', 'VI - coordenar e controlar todos os assuntos relacionados com a identificação do pessoal da corporação;', 'VII - coordenar e controlar o arquivo de toda documentação inerente ao efetivo ativo, inativo e de pensionistas do CBMRN;', 'VIII - desempenhar outras atividades correlatas. Do Centro Superior de Formação e Aperfeiçoamento'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 41',
            'match': 'parcial',
        },
        {
            'heading': 'TÍT. II, Cap. III — DGPEI (pessoas + ensino)',
            'caput': 'Art. 42. O Centro Superior de Formação e Aperfeiçoamento é o órgão responsável pelas atividades de formação, especialização e aperfeiçoamento de Oficiais e Praças da Corporação, competindo-lhe:',
            'dispositivos': ['I - realizar estudos para o planejamento do ensino do CBMRN;', 'II - realizar ações de planejamento no desenvolvimento das atividades físicas e de desportos no âmbito da corporação;', 'III - realizar ações inerentes à formação, especialização e aperfeiçoamento do pes - soal do CBMRN;', 'IV - planejar e promover eventos de artes e culturas do CBMRN;', 'V - desempenhar outras atividades correlatas. Do Serviço de Saúde'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 42',
            'match': 'parcial',
        },
        {
            'heading': 'TÍT. II, Cap. III — DGPEI (pessoas + ensino)',
            'caput': 'Art. 43. O Serviço de Saúde é o ór gão da Corporação responsável pelo planeja - mento, orientação normativa, coordenação, fiscalização, controle e execução das atividades relativas ao serviço de saúde física e mental, médico-odontológico, ambulatorial, prestado ao pessoal interno do CBMRN e seus dependentes, realizan- do ainda avaliações médicas, odontológicas, perícias, atestados periódicos e exam - es de sanidade física e mental de seus integrantes.',
            'dispositivos': ['§ 1º O Pronto Atendimento de Saúde (P AS) é o serviço médico-odontológico ambulatorial, prestado ao efetivo do CBMRN e estendido aos seus dependentes, podendo ser complementado por meio de convênios com planos de saúde, clínicas e hospitais da rede pública e privada.', '§ 2º A Junta Médica de Saúde é o ór gão responsável pelo assessoramento ao Comando Geral da Corporação nas avaliações médicas, perícias, atestados periódi - cos e exames de sanidade física e mental de seus integrantes, além de outras atribuições correlatas. Da Diretoria de Atividades Técnicas'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 43',
            'match': 'parcial',
        },
    ],
    ('organizacao-geral', 'rn'): [
        {
            'heading': 'TÍT. I, Cap. II — Estrutura Organizacional',
            'caput': 'Art. 5º O Corpo de Bombeiros Militar é estruturado em ór gãos de direção superi - or, de assessoramento e de execução.',
            'dispositivos': ['Parágrafo único. É dever de todos os ór gãos e de cada Bombeiro Militar que com - põe a estrutura operacional e administrativa do CBMRN realizar com prontidão, eficiência e proatividade as diligências necessárias ao eficiente andamento dos processos e resolução de suas respectivas demandas.'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 5',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. II — Estrutura Organizacional',
            'caput': 'Art. 6º Os órgãos de direção superior são os responsáveis pelo comando e a admin- istração da Corporação, incumbindo-se do planejamento geral.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 6',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. II — Estrutura Organizacional',
            'caput': 'Art. 7º Os órgãos de assessoramento prestam serviços afetos às áreas de consulto - ria e de assessoramento técnico.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 7',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. II — Estrutura Organizacional',
            'caput': 'Art. 8º Os órgãos de execução realizam as atividades fins e de apoio da Corporação, operacionalizando o emprego de pessoal e equipamentos no cumprimento das mis - sões institucionais. Órgãos de Direção Superior',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 8',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. II — Estrutura Organizacional',
            'caput': 'Art. 9º Os Órgãos de Direção Superior compreendem:',
            'dispositivos': ['I - o Comandante Geral;', 'II - o Subcomandante Geral;', 'III - o Conselho Superior do Corpo de Bombeiros Militar . Órgãos de Assessoramento'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 9',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. II — Estrutura Organizacional',
            'caput': 'Art. 10. Os Órgãos de Assessoramento compreendem:',
            'dispositivos': ['I - Gabinete do Comando Geral;', 'II - Assessoria Jurídica;', 'III - Assessoria Administrativa;', 'IV - Assessoria Parlamentar;', 'V - Ajudância Geral:', 'a) Secretaria Geral;', 'b) Seção de Administração;', 'c) Seção de Comando e Serviço;', 'd) Protocolo Geral;', 'VI - Comissão Permanente de Ética e Disciplina;', 'VII - Unidade de Controle Interno;', 'VIII - Comissão de Promoção de Oficiais;', 'IX - Comissão de Promoção de Praças;', 'X - Assessoria de Projetos, Processos e Convênios;', 'XI - Comissão de Planejamento Estratégico;', 'XII - Assessoria de Inteligência;', 'XIII - Assessoria de Comunicação Social. Órgãos de Execução'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 10',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. II — Estrutura Organizacional',
            'caput': 'Art. 11. Os Órgãos de Execução compreendem:',
            'dispositivos': ['I - Comando Operacional Bombeiro Militar (Cmdo Op BM);', 'a) Comandante;', 'b) Secretaria; 1. Estado-Maior Operacional (EM Op);', 'a) Chefe do EM Op (Subcomandante);', 'b) 1ª SEÇÃO - B/1;', 'c) 2ª SEÇÃO - B/2;', 'd) 3ª SEÇÃO - B/3;', 'e) 4ª SEÇÃO - B/4; 1.1. 1º Grupamento de Bombeiros Militar (1º GBM); 1.2. 2º Grupamento de Bombeiros Militar (2º GBM); 1.3. Grupamento de Bombeiros Marítimo (GBMAR); 1.4. Subgrupamento Independente de Bombeiros Militar de Atendimento Pré-hos- pitalar (S.I.B.M - APH); 1.5. 1º Subgrupamento Independente de Bombeiros Militar (1º S.I.B.M); Edição de hoje, 44 páginas, encerrada às 22h20 2 03 DE DEZEMBRO DE 2021Diário Oficial 1.6. 2º Subgrupamento Independente de Bombeiros Militar (2º S.I.B.M); 1.7. Centro de Operações do CBM, (COCBM); 1.8. Comissão de Defesa Civil;', 'II - Diretoria de Logística, Orçamento e Finanças (DLOF);', 'a) Diretor;', 'b) Subdiretor; 1. Secretaria Executiva (Sub Diretor): 1.1. Centro de Planejamento e Instrução Processual de Contratações (CPIPC); 1.2. Centro de Gestão e Execução de Contratos (CGEC); 1.3. Subseção de Expediente; 2. Comissão Permanente de Licitação (CPL); 3. Centro de Logística (CLOG):', 'a) Chefia;', 'b) Secretaria; 3.1. Seção de Manutenção e Transporte; 3.2. Seção de Suprimento e Patrimônio; 3.2.1. Subseção de Material Bélico; 4. Centro de Tecnologia da Informação e Comunicações (CTIC):', 'a) Chefia; 4.1. Seção de Suporte; 4.1.1. Subseção de Manutenção Técnica; 4.2. Seção de Apoio ao Usuário e Treinamento; 4.3. Seção de Desenvolvimento de Sistemas; 5. Centro de Administração Financeira e Orçamentária:', 'a) Chefia; 5.1. Tesouraria Geral; 5.2. Seção de Processos, Contabilidade e Auditoria;', 'III - Diretoria de Gestão de Pessoas, Ensino e Instrução (DGPEI):', 'a) Diretor;', 'b) Subdiretor;', 'c) Secretaria; 1. Centro de Recursos Humanos (CRH): 1.1. Chefia; 1.2. Seção de Identificação e Processo de Pessoal; 1.3. Seção de Pensionistas e Inativos; 1.4. Seção de Arquivo Geral; 2. Centro Superior de Formação e Aperfeiçoamento (CSFA):', 'a) Chefia;', 'b) Secretaria 2.1. Comissão de Estudos Superiores; 2.2. Corpo de Alunos; 2.3. Divisão de Ensino; 2.4. Divisão Administrativa 2.4.1. Subseção de Educação Física e Desporto; 2.4.2. Subseção Técnica de Ensino e Meios Auxiliares; 3. Serviço de Saúde: 3.1. Pronto Atendimento de Saúde; 3.2. Junta Médica de Saúde.', 'IV - Diretoria de Atividades Técnicas (DAT):', 'a) Diretor;', 'b) Subdiretor', 'c) Secretaria; 1. Centro de Análise de Risco de Incêndio e Pânico; 2. Centro de Apoio Técnico Administrativo; 2.1. Seção de Tecnologia da Informação; 3. Centro de Vistorias; 4. Centro de Fiscalização; 5. 1º Centro de Atividades Técnicas (1º CAT) (sede em Mossoró); 5.1. Seção de Atividades Técnicas (SAT/1º CAT) (sede em Pau dos Ferros); 6. 2º Centro de Atividades Técnicas (2º CAT) (sede em Caicó). Do Comandante Geral'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 11',
            'match': 'exata',
        },
    ],
    ('pessoal-quadros', 'rn'): [
        {
            'heading': 'TÍT. III — Do Pessoal (quadros e QOD)',
            'caput': 'Art. 50. Integram o Corpo de Bombeiros Militar:',
            'dispositivos': ['I - os bombeiros em atividade, compostos por:', 'a) Oficiais, distribuídos nos seguintes quadros de efetivos:', '1 - Quadro de Oficiais Combatentes Bombeiros Militares (QOCBM);', '2 - Quadro de Oficiais de Saúde Bombeiros Militar (QOSBM);', '3 - Quadro de Oficiais Administrativos Bombeiros Militares (QOABM);', 'b) Praças especiais, compreendendo:', '1 - Aspirantes a Oficiais Bombeiros Militares;', '2 - Alunos dos Cursos de Formação de Oficiais Bombeiros Militares;', 'c) Praças, integrantes do Quadro de Praças Bombeiros Militares (QPBM);', 'd) Alunos dos Cursos de Formação de Praças Bombeiros Militares;', 'II - os bombeiros em inatividade, compostos por:', 'a) pessoal da reserva, compreendendo Oficiais e Praças que passaram para a reserva remunerada ou não remunerada.', 'b) pessoal reformado, compreendendo Oficiais e Praças reformadas.'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 50',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. III — Do Pessoal (quadros e QOD)',
            'caput': 'Art. 51. O Quadro de Oficiais Bombeiros Militares Combatentes (QOCBM) é destinado ao exercício, dentre outras das funções de comando, de chefia, direção e administração dos diversos órgãos da instituição, integrado por oficiais possuidores do respec- tivo Curso de Formação de Oficiais, em nível de graduação, realizado em estabelecimento de ensino próprio do Corpo de Bombeiros Militar, ou de outra Unidade Federativa.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 51',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. III — Do Pessoal (quadros e QOD)',
            'caput': 'Art. 52. O Quadro de Oficiais de Saúde Bombeiros Militares (QOSBM) é constituído por Oficiais que, diplomados nas respec- tivas áreas de saúde, por instituições de ensino superior reconhecidas oficialmente, ingressaram na Corporação mediante con - curso público.',
            'dispositivos': ['Parágrafo único. Por ocasião do lançamento do edital do concurso público referente ao preenchimento de vagas do QOSBM, o Corpo de Bombeiros Militar especificará as áreas de saúde e respectivas especialidades de interesse da corporação.'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 52',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. III — Do Pessoal (quadros e QOD)',
            'caput': 'Art. 53. O Quadro de Oficiais Administrativos Bombeiros Militares (QOABM) é destinado ao exercício de atividades sub - sidiárias àquelas previstas para o Quadro de Oficiais Combatentes (QOCBM), sendo constituído por Oficiais oriundos do Quadro de Praças Bombeiros Militares (QPBM), tendo acesso ao primeiro posto do QOABM os primeiros- sar gentos e Subtenentes, aprovados em processo seletivo interno, e após conclusão com aproveitamento do respectivo Curso de Habilitação, conforme legislação específica.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 53',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. III — Do Pessoal (quadros e QOD)',
            'caput': 'Art. 54. O Quadro de Praças Bombeiros Militares (QPBM) é constituído por Praças com os respectivos cursos de formação bombeiro militar.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 54',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. III — Do Pessoal (quadros e QOD)',
            'caput': 'Art. 55. O quadro or ganizacional de distribuição (QOD) do efetivo do Corpo de Bombeiros Militar previsto no art. 48 será publicado em até 180 (cento e oitenta) dias a contar da data de publicação do decreto de aprovação deste Regulamento Geral.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 55',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. III — Do Pessoal (quadros e QOD)',
            'caput': 'Art. 56. O Corpo de Bombeiros Militar poderá dispor de servidores civis, regidos pelas disposições da legislação que estab - elece os direitos, vantagens, obrigações e deveres dos servidores públicos estaduais, cabendo ao Comandante Geral expedir reg- ulamento acerca do ingresso, tempo de serviço, funções e respectivas limitações a serem desempenhadas por esses servidores dentro do Corpo de Bombeiros Militar, nos termos da lei.',
            'dispositivos': [],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 56',
            'match': 'exata',
        },
    ],
    ('seguranca-contra-incendio', 'rn'): [
        {
            'heading': 'TÍT. II, Cap. III — DAT',
            'caput': 'Art. 44. A Diretoria de Atividades Técnicas (DAT) é o ór gão da Corporação que tem por finalidade desenvolver as atividades relacionadas à prevenção contra incên- dio e controle de pânico nas edificações e áreas de risco em todo Estado, conforme previsto na Lei Complementar Estadual Nº 601, de 07 de agosto de 2017, e demais normas e instruções técnicas.',
            'dispositivos': ['§ 1º O Subdiretor é o auxiliar direto do Diretor da DA T, e será o substituto even - tual do Diretor, desempenhando as atribuições previstas em lei e regulamentos.', '§ 2º A critério do Comandante Geral, o subdiretor poderá acumular função na estru- tura da DAT.', '§ 3º O Centro de Análise de Risco de Incêndio e Pânico tem por competência a análise técnica dos projetos de prevenção contra incêndio e pânico das edificações e áreas de risco, verificando o cumprimento das normas de segurança previstas no Código Estadual de Segurança Contra Incêndio e Pânico do Rio Grande do Norte (CESIP), bem com a realização de pesquisas sobre a atualização tecnológica dos materiais, dos equipamentos e das normas nacionais e estrangeiras relacionadas à proteção contra incêndio.', '§ 4º O Centro de Apoio Técnico Administrativo tem por competência o recebi - mento, protocolo, distribuição e arquivamento dos processos relativos aos projetos de proteção contra incêndio das edificações e áreas de risco, bem como o cadastra - mento de profissionais e empresas que prestam serviço de projetos, e instalações de proteção contra incêndio.', '§ 5º A Seção de Tecnologia da Informação é responsável por planejar , coordenar, executar e avaliar projetos e atividades relacionados a investimento, desenvolvi - mento, manutenção e segurança em tecnologia da informação (TI) e pela gestão de capacidade dos elementos de infraestrutura necessários ao funcionamento dos serviços e soluções de TI nos serviços realizados pela DAT, devendo atuar em con- sonância com as diretrizes do CTIC da corporação, com vistas a subsidiar o Diretor da DAT, assessorando no planejamento estratégico e operacional na definição das prioridades de gestão de tecnologia da informação.', '§ 6º O Centro de Vistorias e Perícias de Incêndio tem por competência realizar vis- torias em edificações e áreas de risco, públicas e privadas destinadas à reunião de público e demais natureza de ocupações, nos aspectos relacionados à proteção con- tra incêndio e pânico, bem como realizar perícias de incêndios e explosões em locais sinistrados para fins exclusivos de estudo e pesquisa. ANO 89 EDIÇÃO Nº 15.069 Diário Oficial 503 DE DEZEMBRO DE 2021', '§ 7º O Centro de Fiscalização tem por competência fiscalizar toda e qualquer edificação e área de risco existente no Estado e, quando necessário, expedir notificações e auto de infração, aplicar multas, proceder embargos e interdições e apreensão de bens e produtos, com o intuito de sanar as irregularidades verificadas.', '§ 8º O Primeiro Centro de Atividades Técnicas (1º CA T) é a unidade da Diretoria de Atividades Técnicas, sediada em Mossoró/RN, responsável pelas atividades relacionadas à prevenção contra incêndio e controle de pânico nas edificações e áreas de risco nos municípios localizados no interior do Estado do Rio Grande do Norte.', '§ 9º O Segundo Centro de Atividades Técnicas (2º CA T) é a unidade da Diretoria de Atividades Técnicas, sediada em Caicó/RN, responsável pelas atividades relacionadas à prevenção contra incêndio e controle de pânico nas edificações e áreas de risco nos municípios localizados no interior do Estado do Rio Grande do Norte.', '§ 10. A Seção de Atividades Técnicas, sediada em Pau dos Ferros/RN, é a subunidade do 1º CAT, responsável pelas atividades relacionadas à prevenção contra incêndio e controle de pânico nas edificações e áreas de risco nos municípios localizados no interior do Estado do Rio Grande do Norte.'],
            'source': 'cf. CBMRN, Regulamento Geral (Decreto nº 31.139/2021), Art. 44',
            'match': 'exata',
        },
    ],
}
