# GERADO por scripts/extrair_regulamentos.py — NÃO editar à mão.
# Fonte: Roraíma - Regulamento de Serviço.md (extração determinística; mapa nos de-paras).
ENRICHMENT = {
    ('atribuicoes-funcoes', 'rr'): [
        {
            'heading': 'Cap. II, Seção I — Superior de Dia',
            'caput': 'Art. 2º São atribuições do Superior de Dia, além das previstas em outras normas:',
            'dispositivos': ['I – supervisionar o serviço operacional no âmbito da capital e do interior;', 'II – manter o Comandante-Geral, Subcomandante-Geral e os Comandantes da Capital e do Interior informados sobre ocorrências de grande vulto ou repercussão;', 'III – acompanhar presencialmente ocorrências de grande vulto ou repercussão, devendo assumir a função de comandante do incidente e/ou da ocorrência, assim que tomar conhecimento e/ou for acionado, devidamente uniformizado;', 'IV – inteirar-se do cumprimento de ordens de operação, de atendimento e de serviço relacionadas ao serviço operacional;', 'V – representar o Comando-Geral, Subcomando-Geral e os Comandantes da Capital e do Interior em assuntos pertinentes ao serviço operacional, quando demandados;', 'VI – remanejar temporariamente os recursos operacionais das unidades, quando necessário, informando ao Comandante Operacional da Capital e do Interior; e', 'VII – atender a imprensa, sempre que possível, inerentes as ocorrências em que se fizer presente. Escalas de Serviço'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 2',
            'match': 'exata',
        },
        {
            'heading': 'Cap. II, Seção IV — Prescrições Gerais (Superior de Dia)',
            'caput': 'Art. 10 O Superior de Dia está subordinado diretamente ao COCI.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 10',
            'match': 'exata',
        },
        {
            'heading': 'Cap. II, Seção IV — Prescrições Gerais (Superior de Dia)',
            'caput': 'Art. 11 O Superior de Dia é empregado em ocorrências de grande vulto, podendo fazer o emprego da ferramenta SCI, bem como em outras situações oportunas que necessitem da coordenação ou intervenção de Oficial Superior. Atribuições',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 11',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção I — Coordenador de Dia',
            'caput': 'Art. 12 São atribuições do Coordenador de Dia, além das previstas em outras normas:',
            'dispositivos': ['I – permanecer nas dependências do CICC/RR integralmente à disposição do serviço operacional;', 'II – regular, controlar, fiscalizar e gerenciar as atividades operacionais do CBMRR;', 'III – dar ciência ao Superior de Dia das ordens de operações, de atendimento e de serviço, pertinentes ao serviço operacional e eventuais alterações, até às 09h00;', 'IV – fazer cumprir as normas, as ordens de operações, de atendimento e de serviço pertinentes ao serviço operacional;', 'V – fiscalizar o atendimento das chamadas para ocorrências na COCB;', 'VI – fiscalizar despacho de viaturas, conforme POP-COCB, com atenção especial nos horários de pico e em ocorrências de vulto e/ou repercussão;', 'VII – realizar contatos externos e/ou extraordinários, de modo a empenhar outras guarnições e/ou instituições para prestar primeiros socorros quando houver risco de morte ou integridade da vítima, nos casos de demanda reprimida para equipes de Unidade de Resgate (UR);', 'VIII – manter-se alcançável via rádio móvel e/ou telefone celular sempre que se ausentar da sala de despacho de ocorrências;', 'IX – encaminhar à Diretoria de Assuntos Civis e Relações Públicas (DACRP) solicitações da imprensa e as imagens das ocorrências coletadas pelas guarnições de serviço via canais de comunicação disponibilizados pela Diretoria, como: WhatsApp do telefone funcional, e-mail ou intranet;', 'X – ao tomar conhecimento da divulgação de imagens e/ou vídeos das ocorrências e outras ações do CBMRR em redes sociais ou qualquer outros meios de comunicação por parte das guarnições de serviço, informar à DACRP;', 'XI - atender a imprensa e, logo em seguida, informar à DACRP, desde que não haja impedimento por parte do serviço operacional, prestando informações referentes a dados das ocorrências;', 'XII – despachar o Trem de Socorro em caráter preventivo nas ocorrências de incêndios residenciais, comerciais e/ou industriais, ou quando julgar necessário;', 'XIII – evitar o deslocamento das viaturas de UR para remoções intermunicipais, em especial às do 2º BPABM, conforme maneada pela Portaria nº 2048 de 5 de novembro de 2002 (Regulamento Técnico dos Sistemas Estaduais de Urgência e Emergência) do Ministério da Saúde, o qual rege que as viaturas de UR são do Tipo C, composta por 3 (três) bombeiros militares e/ou outros profissionais reconhecidos pelo gestor público, sendo um motorista e os outros dois profissionais com capacitação e certificação em salvamento e suporte básico de vida;', 'XIV – acionar os oficiais escalados de sobreaviso, quando necessário;', 'XV – acionar o Oficial de Dia/Comandante do Socorro e órgão de perícia oficial no caso de ocorrências que envolvam acidente com viaturas do CBMRR, para adoção de procedimentos legais cabíveis, bem como providenciar as documentações necessárias;', 'XVI – acionar o Oficial de Dia/Comandante do Socorro em situações de indícios de crimes, ocorrência policial e/ou outras ocorrências pertinentes envolvendo militares do CBMRR;', 'XVII – acionar o Oficial de Correições e Disciplina da Corregedoria-Geral do CBMRR em situações que envolvam bombeiro militar, constante no item XVI, caso seja necessário;', 'XVIII – fiscalizar atividades internas do serviço de dia na COCB/CICC, bem como o treinamento diário do POP da COCB com a guarnição de serviço;', 'XIX – lançar a escala do serviço diário em sua Documentação Diária, as horas de ISV aos militares escalados, bem como, as demais alterações de pessoal (faltas e atestados médicos);', 'XX – acionar o Oficial de Saúde para assistência médica e/ou assistência social em caso de óbito do(a) cônjuge ou companheiro(a) e dependente(s) legal(s)[1];', 'XXI – solicitar apoio da Polícia Militar in loco em ocorrências que envolvam violência contra a pessoa (vítimas de agressão, ferimento por armas etc.), visando a proteção da integridade física de vítimas, bombeiros militares e terceiros que porventura estejam no local, assim como salvaguardar bens materiais e patrimônio público;', 'XXII – informar imediatamente o Comandante-Geral, Subcomandante-Geral, Comandante do COCI, Superior de Dia e Comandantes de Batalhões da Unidade, quando houver ocorrências de vulto e/ou repercussão;', 'XXIII – encaminhar mensagens de texto via aplicativo de mensagens, ou na impossibilidade, via telefones funcionais ao Superior de Dia contendo resumo das ocorrências atendidas, bem como de ocorrências em destaque durante o serviço;', 'XXIV – revezar intervalo de descanso com o Oficial de Comunicação, ficando alcançável por telefone, devendo orientá-lo que lhe informe, caso haja, alteração ou ocorrência de vulto e/ou repercussão durante o período;', 'XXV – conferir, ao assumir o serviço, o material, equipamentos e pessoal sob a responsabilidade da função, bem como verificar se o Oficial de Comunicação realizou as conferências de responsabilidade da sua função. Poder de Pronto Emprego - PPE'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 12',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção VI — Prescrições Gerais (Coordenador de Dia)',
            'caput': 'Art. 29 O celular funcional do Coordenador de Dia é de uso exclusivo para o serviço operacional.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 29',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção VI — Prescrições Gerais (Coordenador de Dia)',
            'caput': 'Art. 30 A viatura administrativa da COCB pode ser empregada pelo Coordenador de Dia, exclusivamente em apoio ao serviço operacional (incluindo a aquisição de alimentação aos militares de plantão no CICC).',
            'dispositivos': ['Parágrafo único. Durante o horário de expediente administrativo, a viatura fica a cargo da COCB e os deslocamentos devem ser solicitadas ao Comandante da COCB.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 30',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção VI — Prescrições Gerais (Coordenador de Dia)',
            'caput': 'Art. 31 O Coordenador de Dia deve fiscalizar para que os ramais de emergência 193 sejam utilizados somente para atendimento às ocorrências.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 31',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção VI — Prescrições Gerais (Coordenador de Dia)',
            'caput': 'Art. 32 Fica vedado ao Coordenador de Dia autorizar trocas de serviço e/ou dispensa de militares escalados para o serviço operacional (exceto as legais como: luto, dispensa médica, paternidade etc.), devendo ser cientificadas ao Superior de Dia.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 32',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção VI — Prescrições Gerais (Coordenador de Dia)',
            'caput': 'Art. 33 É dever do Coordenador de Dia conhecer as normas legais e administrativas, protocolos do CBMRR, ABIQUIM e outros protocolos de interesse do serviço operacional. Atribuições',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 33',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IV, Seção I — Oficial de Dia/Comandante do Socorro',
            'caput': 'Art. 34 São atribuições do Oficial de Dia/Comandante do Socorro:',
            'dispositivos': ['I – fiscalizar presencialmente a passagem de serviço, acompanhando a conferência dos recursos operacionais da PO, apurando eventuais alterações, conforme disposto em normativas;', 'II – realizar o briefing operacional e o debriefing operacional com as guarnições da sua PO, podendo se estender às demais PO;', 'III – contatar os Oficiais de incêndio, Salvamento e de Emergência Hospitalar da PO da área de atuação, após realização da passagem de serviço, e verificar se há alterações de pessoal, viaturas e material entre outras informações pertinentes ao serviço;', 'IV – reportar ao Coordenador de Dia após ter conhecimento da situação e alterações existentes no serviço operacional das unidades da área de atuação, informando-o, até às 8h30min, sobre o constatado e para que receba as instruções necessárias;', 'V – apresentar-se aos comandantes das OBM em que se fizer presente, prestando as informações relativas ao serviço operacional;', 'VI – manter-se informado sobre alterações existentes relativas aos recursos operacionais das unidades da área de atuação;', 'VII – remanejar as funções de militares escalados no âmbito de mesma unidade em caso de necessidade do serviço, devendo informar na Documentação Diária;', 'VIII – na ocorrência do previsto no inciso VII em horário de expediente, a alteração deverá ser solicitada à seção responsável pela escala;', 'IX – solicitar autorização ao Coordenador de Dia para realização de deslocamentos;', 'X – fiscalizar o serviço operacional das unidades da área de atuação por meio de inspeções, em que deverá ser observado se há alterações de recursos operacionais;', 'XI – dispensar militares da área de atuação quando se tratar de afastamentos legais, devendo informar na Documentação Diária e ao Coordenador de Dia;', 'XII – acompanhar as rotinas diárias do serviço operacional, tais como: hasteamento e/ou arriamento do Pavilhão Nacional, as instruções diárias, atividade física e o teste de prontidão, dentre outras que surjam para o bom andamento do serviço diário;', 'XIII – fiscalizar a saída das guarnições da unidade quando acionadas para as ocorrências, objetivando a redução do tempo-resposta;', 'XIV – comandar as atividades operacionais no local da ocorrência, otimizando o emprego dos recursos operacionais disponíveis de maneira coordenada, evitando ações isoladas;', 'XV – informar ao Coordenador de Dia acerca da situação do cenário da ocorrência, no caso de ocorrências de vulto ou que julgar necessário;', 'XVI – priorizar a segurança de militares e de terceiros durante o atendimento de ocorrências;', 'XVII – fiscalizar o uso de equipamentos de proteção individuais (EPI), posicionamento correto das viaturas, sinalização e isolamento do local, bem como o emprego correto das técnicas e táticas operacionais nas ocorrências;', 'XVIII – encaminhar ao Coordenador de Dia e à DACRP solicitações da imprensa e as imagens das ocorrências coletadas pelas guarnições de serviço;', 'XIX – ao tomar conhecimento da divulgação de imagens e/ou vídeos das ocorrências, e outras ações do CBMRR, em redes sociais ou qualquer outros meios de comunicação por parte das guarnições de serviço, informar à DACRP;', 'XX – atender à imprensa no local de ocorrências, após a devida autorização do Coordenador de Dia, prestando os esclarecimentos pertinentes ao sinistro, abstendo-se de emitir opinião de cunho pessoal sobre fatos, causas e circunstâncias;', 'XXI – fiscalizar a desmobilização, e suas alterações, dos recursos operacionais empregados na ocorrência, apurando e sanando as alterações identificadas e comunicando as irregularidades na Documentação Diária;', 'XXII – manter-se disponível no telefone móvel funcional e handie-talkie (HT);', 'XXIII – permanecer na PO quando não estiver empenhado em ocorrências, ordens de serviço ou outras determinações do Coordenador de Dia.', 'XXIV – providenciar montagem da ferramenta do SCI em ocorrências de vulto e/ou repercussão e a comandar até a passagem do Posto de Comando ao seu substituto;', 'XXV – requerer à COCB o acionamento de outros órgãos em apoio, sempre que necessário;', 'XXVI – apoiar e assessorar o Superior de Dia em ocorrências de grande vulto, mantendo-o informado de quaisquer alterações e disponibilidade dos recursos operacionais;', 'XXVII – cumprir as determinações estabelecidas pelo Superior de Dia e o apoiar na supervisão do SCI e no controle do deslocamento de efetivo ou guarnições dentro da Capital e do Interior;', 'XXVIII – assessorar o Coordenador de Dia na movimentação de recursos operacionais entre as PO do serviço operacional durante o turno de trabalho;', 'XXIX – averiguar junto à COCB sobre o atendimento às ocorrências, ordens de operação, de atendimento e de serviço;', 'XXX – zelar pelo fiel cumprimento das ordens, normas e diretrizes durante o atendimento às ocorrências operacionais;', 'XXXI – relatar ao Coordenador de Dia as sugestões, dificuldades, reclamações e alterações ocorridas no turno de serviço;', 'XXXII – elaborar o Estudo de Caso, quando demandado pelo COCI, das ocorrências de grande vulto e/ou repercussão.', 'XXXIII - esta INOp não exclui a emissão de outras normas complementares. Emprego'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 34',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IV, Seção V — Prescrições Gerais',
            'caput': 'Art. 41 O Oficial de Dia/Comandante do Socorro se subordina operacionalmente ao Coordenador de Dia, devendo repassar a este todas as informações pertinentes ao serviço operacional.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 41',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IV, Seção V — Prescrições Gerais',
            'caput': 'Art. 42 O Oficial de Dia/Comandante do Socorro deverá solicitar autorização do Coordenador de Dia para deslocamentos de militares a estabelecimento comercial a fim de adquirirem refeição para os demais militares da unidade quando necessário.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 42',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IV, Seção V — Prescrições Gerais',
            'caput': 'Art. 43 O Oficial de Dia/Comandante do Socorro não tem competência para autorizar permutas de serviço entre militares que não constam na escala de serviço.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 43',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IV, Seção V — Prescrições Gerais',
            'caput': 'Art. 44 O Oficial de Dia/Comandante do Socorro será empregado em ocorrências despachadas pelo COCB, bem como em outras situações que necessitem da coordenação ou intervenção de oficial intermediário ou subalterno.',
            'dispositivos': ['Parágrafo único. No cumprimento de ordens de atendimento e de serviço, caso haja necessidade de alteração na execução, pertinentes a horário, local, viatura, equipamentos, recursos humanos e outros, os Oficiais de Dia deverão informar o Coordenador de Dia sobre alterações constatadas e lhe sugerir as ações adequadas para solução da situação. Atribuições'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 44',
            'match': 'exata',
        },
        {
            'heading': 'Cap. V, Seção I — Oficial de Incêndio/Salvamento/EPH',
            'caput': 'Art. 45 São atribuições do Oficial de Incêndio, de Salvamento e de Emergência Pré- Hospitalar, além das previstas em outras normas:',
            'dispositivos': ['I – cumprir e fiscalizar a execução da norma pertinente à passagem de serviço, acompanhando a conferência dos materiais e equipamentos das viaturas sob sua responsabilidade, bem como dos recursos operacionais da sua PO, comunicando eventuais alterações;', 'II – realizar o hasteamento e arriação do Pavilhão Nacional na sua PO;', 'III – informar à COCB a assunção do serviço com as seguintes informações: QRA, função, composição da guarnição, viatura (prefixo, placa e KMI) e PO de atuação;', 'IV – realizar o briefing operacional e o debriefing operacional com as guarnições da sua PO;', 'V – apresentar-se aos comandantes das OBM, Superior de Dia, Coordenador de Dia e ao Oficial de Dia/Comandante do Socorro quando da presença destes na sua PO, passando-lhes todas as alterações e as informações de recursos operacionais daquele setor;', 'VI – fiscalizar e informar ao Coordenador de Dia e ao Oficial de Dia/Comandante do Socorro as alterações do serviço na sua PO, fazendo constar na Documentação Diária;', 'VII – auxiliar o Oficial de Dia/Comandante do Socorro nas ocorrências e ordens de serviço em que se fizer presente, bem como outras determinações emanadas dos comandos, unidades operacionais e/ou seções;', 'VIII – manter-se informado sobre alterações dos recursos operacionais existentes relativos a sua PO;', 'IX – fiscalizar e reforçar as orientações sobre a segurança interna da PO, bem como elaborar e registrar na Documentação Diária a escala de emprego/descanso dos permanências;', 'X – solicitar autorização ao Coordenador de Dia para realização de deslocamentos, salvo das ocorrências demandadas pela COCB;', 'XI – contatar o Oficial de Dia/Comandante do Socorro sobre dispensa de militares da sua guarnição ou PO, quando se tratar de afastamentos legais, devendo informar tal evento na Documentação Diária;', 'XII – fazer cumprir e participar das rotinas diárias do serviço operacional, tais como: hasteamento e/ou arriamento do Pavilhão Nacional, as instruções diárias, atividade física e o teste de prontidão, dentre outras que surjam durante o serviço;', 'XIII – comandar a saída das guarnições sob seu comando quando acionadas para as ocorrências, objetivando a redução do tempo-resposta;', 'XIV – comandar as atividades operacionais das guarnições sob seu comando no local da ocorrência, otimizando o emprego dos recursos operacionais disponíveis de maneira coordenada, evitando ações isoladas;', 'XV – informar o Oficial de Dia/Comandante do Socorro, na ausência deste o Coordenador de Dia, acerca da situação do local em ocorrências de vulto ou que julgar necessário;', 'XVI – priorizar a segurança de militares e de terceiros durante o atendimento de ocorrências;', 'XVII – fiscalizar o uso de equipamentos de proteção individuais (EPI), posicionamento correto das viaturas, sinalização e isolamento do local, bem como o emprego correto das técnicas e táticas operacionais nas ocorrências;', 'XVIII – comandar a desmobilização, verificar possíveis alterações dos recursos operacionais empregados na ocorrência de sua responsabilidade, apurar e sanar as alterações identificadas e relatar o que não foi possível sanar durante seu plantão, na Documentação Diária e ao Oficial de Dia/Comandante do Socorro;', 'XIX – apoiar e auxiliar o Oficial de Dia/Comandante do Socorro, caso seja possível, na montagem do SCI em ocorrências de vulto e/ou repercussão;', 'XX – informar o Oficial de Dia/Comandante do Socorro sobre demandas da imprensa no local de ocorrências, subsidiando-o com as informações da ocorrência;', 'XXI – manter-se disponível no telefone móvel funcional e no HT;', 'XXII – permanecer na PO quando não estiver empenhado em ocorrências, ordens de serviço ou outras determinações do Coordenador de Dia;', 'XXIII – requerer à COCB o acionamento de outros órgãos em apoio as ocorrências, sempre que necessário;', 'XXIV – cumprir as determinações estabelecidas pelo Coordenador de Dia ou Oficial de Dia/Comandante do Socorro na movimentação de recursos operacionais entre as PO a bem do serviço operacional durante o turno de trabalho, alertando-os sobre possíveis problemas nessa movimentação;', 'XXV – verificar junto à COCB sobre o atendimento às ocorrências, ordens de operação, de atendimento e de serviço de sua responsabilidade;', 'XXVI – zelar pelo fiel cumprimento das ordens, normas e diretrizes durante o atendimento às ocorrências operacionais e em sua PO;', 'XXVII – encaminhar ao Oficial de Dia ou Coordenador de Dia solicitações da imprensa e as imagens das ocorrências coletadas pelas guarnições de serviço;', 'XXVIII – ao tomar conhecimento da divulgação de imagens e/ou vídeos das ocorrências, e outras ações do CBMRR, em redes sociais ou qualquer outros meios de comunicação por parte das vossas guarnições de serviço, informar à DACRP;', 'XXIX – primar pela padronização de uniforme a ser utilizado na sua PO, conforme norma vigente;', 'XXX – relatar ao Oficial de Dia/Comandante do Socorro as sugestões, dificuldades, reclamações e alterações ocorridas no turno de serviço, as quais não tenha conseguido resolver. Escalas de Serviço'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 45',
            'match': 'exata',
        },
        {
            'heading': 'Cap. V, Seção IV — Prescrições Gerais',
            'caput': 'Art. 51 O Oficial de Incêndio, de Salvamento e de Emergência Pré-Hospitalar se subordinam operacionalmente ao Oficial de Dia/Comandante do Socorro, a quem devem repassar todas as informações pertinentes ao serviço operacional.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 51',
            'match': 'exata',
        },
        {
            'heading': 'Cap. V, Seção IV — Prescrições Gerais',
            'caput': 'Art. 52 O Oficial de Incêndio, de Salvamento e de Emergência Pré-Hospitalar solicitarão ao Coordenador de Dia autorização para deslocamentos de militares a estabelecimento comercial a fim de adquirirem refeição para os demais militares da unidade.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 52',
            'match': 'exata',
        },
        {
            'heading': 'Cap. V, Seção IV — Prescrições Gerais',
            'caput': 'Art. 53 O Oficial de Incêndio, de Salvamento e de Emergência Pré-Hospitalar são mais um integrante da respectiva guarnição a qual estão escalados.',
            'dispositivos': ['Parágrafo único. É de sua responsabilidade o preenchimento e a assinatura dos relatórios e documentações das ocorrências e do serviço, podendo delegar o seu preenchimento ao Comandante da Guarnição ou à Praça mais antiga da sua guarnição, exceto ao motorista. Atribuições'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 53',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VI, Seção I — Oficial de Comunicação',
            'caput': 'Art. 54 São atribuições do Oficial de Comunicação, além das previstas em outras normas:',
            'dispositivos': ['I – apresentar o efetivo da COCB escalado no CICC/RR ao Coordenador de Dia e o manter informado sobre as alterações do serviço;', 'II – auxiliar o Coordenador de Dia e fazer cumprir o POP da COCB, as ordens de atendimento e de serviço, bem como outras determinações emanadas dos comandos, unidades operacionais e/ou seções;', 'III – fiscalizar e acompanhar o trabalho dos Atendentes, conforme o POP da COCB;', 'IV – fiscalizar e acompanhar o despacho das viaturas, conforme POP da COCB;', 'V – gerenciar a distribuição do efetivo da COCB, priorizando os militares mais antigos na função de Despachante;', 'VI – gerenciar a saída das viaturas na realização das refeições, distribuindo os horários de forma equitativa e eficiente para o serviço operacional;', 'VII – empenhar, em casos de demandas reprimidas de UR, outras guarnições, em havendo risco de morte ou integridade da vítima, para prestarem os primeiros socorros na cena até a chegada da UR ou apoio do SAMU;', 'VIII – empenhar equipes nas ocorrências que requeiram ações preventivas, para isolamento até a chegada do órgão competente;', 'IX – receber as informações das unidades operacionais até às 08h30min, para elaborar o PPE até às 09h00;', 'X – conferir o material-carga de responsabilidade da função;', 'XI – conferir diariamente o funcionamento dos sistemas operacionais da COCB e dos ramais do serviço de atendimento 193, e reportar imediatamente ao plantonista de Tecnologia da Informação do CICC ou Comandante da COCB casos de mau funcionamento;', 'XII – elaborar e registrar em seu livro diário a escala de descanso dos Atendentes e Despachantes, fiscalizando o seu cumprimento, podendo compor essa escala em caso de efetivo reduzido;', 'XIII – revezar intervalos de descanso com o Coordenador de Dia, respondendo pela coordenação durante o afastamento desse, devendo informá-lo de ocorrência de vulto e/ou repercussão;', 'XIV – permanecer nas dependências do CICC/RR, devendo estar integralmente à disposição do serviço operacional;', 'XV – realizar o treinamento diário do POP da COCB com a guarnição de serviço; e', 'XVI – fiscalizar para que as linhas 193 sejam utilizados somente para atendimento a ocorrências. Escalas de Serviço'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 54',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VI, Seção IV — Prescrições Gerais',
            'caput': 'Art. 60 O Oficial de Comunicação se subordina operacionalmente ao Coordenador de Dia, a quem deve repassar todas as informações pertinentes ao serviço operacional.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 60',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VI, Seção IV — Prescrições Gerais',
            'caput': 'Art. 61 O Oficial de Comunicação solicitará ao Coordenador de Dia autorização para deslocamentos de militares a estabelecimento comercial a fim de adquirirem refeição para os demais militares da unidade, caso a refeição não seja feita nas próprias instalações.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 61',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VI, Seção IV — Prescrições Gerais',
            'caput': 'Art. 62 O Oficial de Comunicação é mais um integrante da guarnição a qual está escalado. Atribuições',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 62',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VII, Seção I — Oficial de Saúde',
            'caput': 'Art. 63 São atribuições do Oficial de Saúde, além das previstas em outras normas:',
            'dispositivos': ['I – providenciar as ações de apoio e acompanhamento dos militares do CBMRR e seus dependentes legais atendidos em unidades hospitalares, de forma presencial e/ou remota;', 'II – permanecer disponível para possíveis acionamentos, principalmente, após o término do expediente;', 'III – auxiliar o Coordenador de Dia nas ocorrências atinentes a suas atividades;', 'IV – apresentar-se o mais breve possível no local determinado pelo Coordenador de Dia, a qualquer momento, devidamente fardado, para o desempenho das atividades de sua competência;', 'V – apresentar-se ao comandante do incidente em ocorrência de vulto e/ou repercussão que se fizer presente, devendo subordinação a este até o término da ocorrência;', 'VI – orientar e auxiliar nas demandas relacionadas ao preenchimento de Atestado de Origem, presencialmente', 'VII – informar ao Coordenador de Dia quando do término da atividade que motivou seu acionamento, fornecendo todas as ações de apoio e acompanhamento realizadas aos militares e/ou a seus dependentes, para controle; e', 'VIII – lançar na Documentação Diária as ações tomadas no atendimento e enviar ao Coordenador de Dia, de forma a resguardar às informações pessoais dos atendidos. Escalas de Serviço'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 63',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VII, Seção IV — Prescrições Gerais',
            'caput': 'Art. 70 Os militares deverão cumprir as normas e determinações vigentes dentro de suas respectivas funções.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 70',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VII, Seção IV — Prescrições Gerais',
            'caput': 'Art. 71 Em caso de acionamento, atender com eficiência e presteza, sempre primando pelo bom relacionamento com as equipes médicas, hospitalares e afins. Atribuições',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 71',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IX, Seção I — Oficial de Sobreaviso',
            'caput': 'Art. 79 São atribuições do Oficial de Sobreaviso, além das previstas em outras normas:',
            'dispositivos': ['I – inteirar-se do serviço de sobreaviso ao qual está escalado;', 'II – permanecer disponível para possíveis acionamentos, principalmente, após o término do expediente;', 'III – auxiliar o Coordenador de Dia nas ocorrências atinentes a suas atividades;', 'IV – apresentar-se, de imediato, no local determinado pelo Coordenador de Dia ou Oficial de Comunicação, a qualquer momento, devidamente fardado, para o desempenho da atividade operacional de sua competência;', 'V – apresentar-se ao comandante do incidente em ocorrência de vulto e/ou repercussão que se fizer presente, devendo subordinação a esse até o término da ocorrência;', 'VI – informar o Coordenador de Dia quando do término da ocorrência a qual se fez presente, passando todas as providências tomadas e a situação final da ocorrência;', 'VII – lançar na Documentação Diária o resumo da ocorrência que foi acionado e enviar ao Coordenador de Dia, exceto os militares do CeSau; e', 'VIII – realizar o "pronto" com os demais militares de sua guarnição, caso tenha outros militares escalados, passando-lhes todas as orientações em caso de acionamento. Escalas de Serviço'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 79',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IX, Seção IV — Prescrições Gerais',
            'caput': 'Art. 85 O militares deverão cumprir as normas e determinações vigentes dentro de suas respectivas funções.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 85',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IX, Seção IV — Prescrições Gerais',
            'caput': 'Art. 86 Em caso de acionamento, atender com eficiência e presteza as ocorrências.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 86',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IX, Seção IV — Prescrições Gerais',
            'caput': 'Art. 87 As unidades operacionais no interior do Estado que tenham o Oficial Dia/Comandante do Socorro em sobreaviso, este deverá preencher e finalizar a sua Documentação Diária até às 07h30, remetendo-a ao Coordenador de Dia.',
            'dispositivos': ['Parágrafo único. Deverá dar o visto no livro do comandante de guarnição de serviço daquela unidade operacional.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 87',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IX, Seção IV — Prescrições Gerais',
            'caput': 'Art. 88 Em caso de acionamento, o militar faz jus ao recebimento da ISV, quando acionado fora do expediente administrativo, conforme disciplinado pela norma vigente.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 88',
            'match': 'exata',
        },
    ],
    ('disciplina-correicao', 'rr'): [
        {
            'heading': 'Cap. VIII, Seção I — Oficial de Correições e Disciplina',
            'caput': 'Art. 72 São atribuições do Oficial de Correições e Disciplina, além das previstas em outras normas:',
            'dispositivos': ['I – permanecer disponível para possíveis acionamentos, principalmente, após o término do expediente;', 'II – comparecer em todas as situações em que militar do CBMRR deva ser recolhido ou preso, providenciando a lavratura dos documentos necessários, tanto em procedimento disciplinar como criminal, bem como cuidar do devido encaminhamento na forma da legislação em vigor;', 'III – auxiliar o Coordenador de Dia nas demandas atinentes a suas atividades;', 'IV – apresentar-se, de imediato, no local determinado pelo Coordenador de Dia nas demandas atinentes a suas atividades;', 'V – resguardar a integridade física de militares do CBMRR durante a lavratura dos procedimentos disciplinares ou criminais;', 'VI – informar o Coordenador de Dia quando do término da ocorrência a qual se fez presente, passando todas as providências tomadas e a situação final dessa;', 'VII – assessorar o Oficial de Dia/Comandante do Socorro no preenchimento da Documentação Diária com as informações necessárias do caso e dos envolvidos;', 'VIII – providenciar local para o encaminhamento de militares custodiados; e', 'IX – cumprir outras determinações do Comando-Geral ou do Superior de Dia, pertinentes ao serviço. Escalas de Serviço'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 72',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VIII, Seção IV — Prescrições Gerais',
            'caput': 'Art. 77 O Oficial de Correições e Disciplina é subordinado diretamente, dentro da escala hierárquica, ao Comandante-Geral, Subcomandante-Geral e ao Diretor da Corregedoria-Geral.',
            'dispositivos': ['Parágrafo único. Em casos de acionamentos, deve assessorar o Superior de Dia, Coordenador de Dia e/ou Oficial demandante.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 77',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VIII, Seção IV — Prescrições Gerais',
            'caput': 'Art. 78 Em caso de acionamento, atender com eficiência e presteza as ocorrências. Atribuições',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 78',
            'match': 'exata',
        },
    ],
    ('disposicoes-finais', 'rr'): [
        {
            'heading': 'Cap. X — Disposições Finais (deveres, competência do COCI)',
            'caput': 'Art. 89 Os Oficiais que concorrem às escalas de Serviço Operacional e de Sobreaviso deverão:',
            'dispositivos': ['I – cumprir e fazer cumprir esta norma e outras existentes que visem a melhor qualidade na execução das atividades operacionais;', 'II – atentar para a regulamentação da DACRP quando do repasse de informações, publicações em redes sociais e concessão de entrevistas à imprensa;', 'III – informar formalmente ao COCI, até o 20º dia do mês anterior ao mês programado, os afastamentos regulares (férias, licença especial, cursos, núpcias, etc.);', 'IV – informar, em tempo hábil, formalmente ao COCI, quaisquer impedimentos legais que o impeçam de tirar o serviço para o qual estava escalado, salvo os casos fortuitos e de força maior;', 'V – em caso de cancelamento de afastamento regular, o Oficial deverá informar, de imediato, a seu comandante de unidade para que este comunique ao COCI a disponibilidade de emprego na escala de serviço.', 'Parágrafo único. Caso os afastamentos não sejam informados de acordo com os incisos III e IV, o cumprimento do serviço será de responsabilidade do escalado.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 89',
            'match': 'exata',
        },
        {
            'heading': 'Cap. X — Disposições Finais (deveres, competência do COCI)',
            'caput': 'Art. 90 Compete ao COCI:',
            'dispositivos': ['I – a distribuição equitativamente de todo o efetivo de oficiais da corporação para composição das escalas operacionais;', 'II – confeccionar a escala de serviço diário da corporação e dar publicidade;', 'III – definir os critérios de regime de escala, podendo ser preta e vermelha ou corrida, atentando para as normas vigentes de folgas regulamentares;', 'IV – não permitir que a escala fique repetitiva (viciada), onde os militares tiram seus serviços sempre no mesmo dia da semana;', 'V – observar para que os militares lotados em um mesmo setor, tenham um intervalo mínimo de 48h entre suas escalas, salvo a extrema necessidade do serviço operacional;', 'VI – cumprir fielmente todas as normas vigentes relacionadas a ISV;', 'VII – não escalar militares em Serviço Extraordinário, com pagamento de ISV, antes que cumpram, ao menos, uma escala de Serviço Ordinário; e', 'VIII – escalar um oficial para compor as guarnições em todas as missões, escalas extraordinárias, eventos comemorativos e outros que sejam requisitados para os serviços do CBMRR.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 90',
            'match': 'exata',
        },
        {
            'heading': 'Cap. X — Disposições Finais (deveres, competência do COCI)',
            'caput': 'Art. 91 Compete a todos os oficiais que concorrem às escalas:',
            'dispositivos': ['I – cuidar de seu condicionamento físico, profissional e pessoal;', 'II – utilizar os equipamentos de proteção individual;', 'III – cuidar pela disciplina de comunicação via rádio, informática e outros meios de telecomunicações;', 'IV – primar pelo bom atendimento às vítimas, público em geral, autoridades e profissionais que participam direta ou indiretamente das ocorrências, serviços ou qualquer outra atividade;', 'V – atender com presteza as ocorrências;', 'VI – atuar de acordo com os procedimentos operacionais da Corporação;', 'VII – operar com eficiência os equipamentos e instrumentos pertinentes ao serviço.', 'Parágrafo único. Todos os militares deverão informar o "pronto" das missões recebidas a seu superior imediato.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 91',
            'match': 'exata',
        },
        {
            'heading': 'Cap. X — Disposições Finais (deveres, competência do COCI)',
            'caput': 'Art. 92 O Oficial só poderá ser escalado no Serviço Operacional ou de Sobreaviso no 2º dia útil quando do retorno de fruição de férias, exceto se o retorno ocorrer em dias não úteis.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 92',
            'match': 'exata',
        },
        {
            'heading': 'Cap. X — Disposições Finais (deveres, competência do COCI)',
            'caput': 'Art. 93 Todas as atividades executadas pelo COCI, Batalhões e Companhias compõem a atividade-fim da corporação.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 93',
            'match': 'exata',
        },
        {
            'heading': 'Casos omissos, revogação, vigência',
            'caput': 'Art. 94 Os casos omissos constantes nesta INOp serão solucionados pelo Comando-Geral.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 94',
            'match': 'exata',
        },
        {
            'heading': 'Casos omissos, revogação, vigência',
            'caput': 'Art. 95 Revogam-se as ordens ou determinações em contrário após a publicação desta Instrução Normativa Operacional.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 95',
            'match': 'exata',
        },
        {
            'heading': 'Casos omissos, revogação, vigência',
            'caput': 'Art. 96 Esta INOP entra em vigor na data de sua publicação.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 96',
            'match': 'exata',
        },
        {
            'heading': 'Casos omissos, revogação, vigência',
            'caput': 'Art. 97 Publique-se. Registre-se. Cumpra-se. Quartel do Comando-Geral Coronel Jean Cláudio de Souza Hermógenes, Boa Vista/RR. (Assinado eletronicamente) Subcomandante-Geral do CBMRR Decreto 1331-P de 24/09/2021 (DOE nº 4051/2021) Respondendo pelo Comando-Geral',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 97',
            'match': 'exata',
        },
    ],
    ('disposicoes-preliminares', 'rr'): [
        {
            'heading': 'Cap. I — Conceituação Básica',
            'caput': 'Art. 1º Para fins de normatização dos serviços diários dos oficiais da Corporação, ficam estabelecidas as seguintes definições:',
            'dispositivos': ['I – Área de Espera: ponto ou local estabelecido para recebimento, controle e disponibilização de pessoal, materiais e viaturas no atendimento às ocorrências de vulto (grandes proporções ou alta complexidade);', 'II – Assistência Médica: é o tratamento de doenças e a preservação da saúde através de serviços médicos, farmacêuticos, enfermagem e outras profissões relacionadas;', 'III – Briefing Operacional: reunião operacional, realizada após a assunção do serviço, sobre as atividades diversas com a finalidade de estabelecer e dar conhecimento aos envolvidos sobre o objetivo da missão e/ou do serviço a ser executado, bem como, do serviço diário;', 'VI – Coordenador de Dia: Major ou Capitão, responsável por coordenar o serviço operacional do CBMRR, dentro do CICC/RR, subordinado ao Superior de Dia;', 'V – Debriefing Operacional: reunião operacional, realizada após o término de ocorrências, vislumbrando avaliar se o objetivo foi atingido, análise das implicações e o desempenho das ações desenvolvidas, apontamentos de pontos positivos e negativos, priorizando sedimentação de procedimentos corretos e aprendizado com erros, desvios e/ou situação nova apresentada ou ocorrida antes, durante ou após a ocorrência;', 'VI – Demanda Reprimida: consiste na atividade a qual a unidade não conseguiu atender e/ou resolver de forma integral ou parcial, por alguma razão e ainda precisa ser executada, ficando em espera;', 'VII – Documentação Diária: documentos, relatórios, livros, extratos de controle operacional, dentre outros, elaborados pelos Oficiais escalados, que expressam os atendimentos, o pessoal e materiais disponíveis para pronto emprego do serviço diário, bem como suas alterações no decorrer do serviço diário e/ou qualquer outro documento necessário para o serviço diário;', 'VIII – Estudo de Caso: apresentação elaborada pelo Oficial de Dia/Comandante do Socorro - juntamente com os demais oficiais que estavam na ocorrência, a ser apresentada aos demais oficiais que concorrem as escalas de serviço, da ocorrência de grande vulto, onde deverá fazer constar o apontamento de pontos positivos e negativos, os procedimentos corretos e aprendizado com erros, desvios e/ou situação nova que ocorreu durante a execução do serviço;', 'IX– Ocorrência: reunião de acontecimentos, num dado momento;', 'X – Ocorrência de Grande Vulto: reunião de acontecimentos mais complexos ou que causam maior repercussão na sociedade, que exigem uma mobilização intensiva de recursos e esforços para lidar com as suas consequências;', 'XI – Oficial de Dia/Comandante do Socorro: Oficial Intermediário ou Subalterno, responsável por supervisionar, fiscalizar e comandar in loco as ocorrências, subordinado ao Coordenador de Dia;', 'XII – Oficial de Comunicação: Oficial Subalterno, preferencialmente 1º Tenente, responsável por fiscalizar e supervisionar ligações de emergência 193 e despacho do serviço operacional na COCB, dentro do CICC/RR, subordinado ao Coordenador de Dia;', 'XIII – Oficial de Correições e Disciplina: Oficial da Corregedoria-Geral responsável por assessorar e providenciar todos os documentos necessários em procedimento disciplinar ou criminal envolvendo militares do CBMRR;', 'XIV – Oficial de Emergência Pré-Hospitalar: Oficial Subalterno, Aspirante a Oficial ou Subtenente habilitado ao oficialato e nomeado em função de oficial, responsável por comandar a guarnição de Emergência Pré-Hospitalar, subordinado ao Oficial de Dia/Comandante do Socorro;', 'XV – Oficial de Incêndio: Oficial Subalterno, Aspirante a Oficial ou Subtenente habilitado ao oficialato e nomeado em função de oficial, responsável por comandar a guarnição de combate a incêndio, subordinado ao Oficial de Dia/Comandante do Socorro;', 'XVI – Oficial de Salvamento: Oficial Subalterno, Aspirante a Oficial ou Subtenente habilitado e nomeado em função de oficial, responsável por comandar a guarnição de busca e salvamento, subordinado ao Oficial de Dia/Comandante do Socorro;', 'XVII – Oficial de Saúde: Oficial do CeSau responsável pela assistência médica e/ou assistência social de apoio e acompanhamento dos militares do CBMRR, e seus dependentes legais, conforme norma vigente;', 'XVIII – Oficial de Sobreaviso: Oficiais escalados como reserva ou pronto-emprego em serviços, que devem assumir suas funções, em caso de acionamento;', 'XIX – Perito de Incêndio: Oficial formado em Curso de Perícia de Incêndio, responsável por realizar as perícias em locais de incêndio;', 'XX – Poder de Pronto Emprego (PPE): extrato de controle operacional, elaborado pelo Coordenador de Dia, com a disponibilidade de recursos operacionais das unidades da Capital e do interior, que expressa toda a disponibilidade de recursos disponíveis para pronto emprego no serviço diário;', 'XXI – Prontidão Operacional (PO): local de referência em que o oficial ou guarnição realiza passagem de serviço, podendo ser fixo ou móvel, servindo como ponto de apoio durante o turno de serviço;', 'XXII – Recursos Operacionais: pessoal, equipamentos, materiais, viaturas, suprimentos e instalações disponíveis ou potencialmente disponíveis para serem utilizadas no apoio ao atendimento das atividades operacionais de resposta;', 'XXIII – Serviço Extraordinário: é aquele serviço que exige a mobilização extraordinária de pessoal, em decorrência de seu acionamento, podendo ser remunerado com a Indenização de Serviço Voluntário (ISV);', 'XXIV – Serviço Ordinário: é aquele serviço obrigatório, executado regularmente no intuito de suprir as necessidades operacionais da instituição;', 'XXV – Superior de Dia: Tenente-Coronel ou Major, responsável pela supervisão geral do serviço operacional do CBMRR;', 'XXVI – Trem de Socorro: é o deslocamento realizado simultaneamente por um conjunto específico de viaturas, de características diferentes, quando em situações de emergência ou urgência. Outras viaturas podem ser empenhadas posteriormente, considerando a necessidade no cenário. Atribuições'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 1',
            'match': 'exata',
        },
    ],
    ('pessoal-quadros', 'rr'): [
        {
            'heading': 'Cap. II, Seção II — Escalas (Superior de Dia)',
            'caput': 'Art. 3º A escala de serviço do Superior de Dia será executada em regime de plantão, no decorrer do expediente administrativo, mantendo-se disponível após este período, bem como finais de semana e feriados.',
            'dispositivos': ['§ 1º O Superior de Dia faz jus ao recebimento da ISV quando acionado fora do expediente administrativo, conforme disciplinado pela norma vigente.', '§ 2º A elaboração da escala segue a padronização estabelecida pelo COCI, conforme a necessidade do serviço.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 3',
            'match': 'exata',
        },
        {
            'heading': 'Cap. II, Seção II — Escalas (Superior de Dia)',
            'caput': 'Art. 4º As escalas de serviço serão elaboradas pelo COCI e submetidas à homologação do Subcomandante-Geral.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 4',
            'match': 'exata',
        },
        {
            'heading': 'Cap. II, Seção II — Escalas (Superior de Dia)',
            'caput': 'Art. 5º Quando houver impossibilidade do cumprimento da escala de serviço por parte do oficial escalado, ou impossibilidade de continuar a cumprir o referido serviço, o COCI deverá ser comunicado, e este providenciará a devida substituição.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 5',
            'match': 'exata',
        },
        {
            'heading': 'Cap. II, Seção II — Escalas (Superior de Dia)',
            'caput': 'Art. 6º As permutas de serviço somente são autorizadas pelo COCI. Assunção e Passagem do Serviço',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 6',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção IV — Escalas (Coordenador de Dia)',
            'caput': 'Art. 23 A escala do serviço de Coordenador de Dia, elaborada pelo COCI, é no regime de 24 horas de trabalho, salvo determinação em contrário.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 23',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção IV — Escalas (Coordenador de Dia)',
            'caput': 'Art. 24 As permutas de serviço somente serão permitidas com autorização do Comandante do COCI ou seu substituto imediato, devendo ser lançadas na Documentação Diária. Assunção e Passagem do Serviço',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 24',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IV, Seção III — Escalas (Oficial de Dia)',
            'caput': 'Art. 36 A escala de serviço do Oficial de Dia/Comandante do Socorro, elaborada pelo COCI, é em regime de 24 horas, salvo determinação em contrário.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 36',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IV, Seção III — Escalas (Oficial de Dia)',
            'caput': 'Art. 37 As permutas de serviço somente serão autorizadas pelo Comandante do COCI ou seu substituto imediato, devendo informar ao Coordenador de Dia para que conste a devida autorização em sua Documentação Diária. Assunção e Passagem do Serviço',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 37',
            'match': 'exata',
        },
        {
            'heading': 'Cap. V, Seção II — Escalas',
            'caput': 'Art. 46 A escala do serviço dos Oficiais de Incêndio, de Salvamento e de Emergência Pré- Hospitalar, elaborada pelo COCI, é no regime de 24 horas, salvo determinação em contrário.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 46',
            'match': 'exata',
        },
        {
            'heading': 'Cap. V, Seção II — Escalas',
            'caput': 'Art. 47 As permutas de serviço somente serão autorizadas pelo Comandante Operacional da Capital e do Interior ou seu substituto imediato. Assunção e Passagem do Serviço',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 47',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VI, Seção II — Escalas',
            'caput': 'Art. 55 A escala do serviço de Oficial de Comunicação, elaborada pelo COCI, é no regime de 24 horas, salvo determinação em contrário.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 55',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VI, Seção II — Escalas',
            'caput': 'Art. 56 As permutas de serviço somente serão autorizadas pelo Comandante Operacional da Capital e do Interior ou seu substituto imediato. Assunção e Passagem do Serviço',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 56',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VII, Seção II — Escalas',
            'caput': 'Art. 64 A escala do serviço do Oficial de Saúde é de 24 horas, em regime de Sobreaviso, salvo determinação em contrário.',
            'dispositivos': ['§ 1º A elaboração da escala será de responsabilidade do CeSau.', '§ 2º A escala deverá ser enviada ao COCI, formalmente, até o 20º dia do mês anterior ao mês programado.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 64',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VII, Seção II — Escalas',
            'caput': 'Art. 65 O militar poderá tirar, no máximo, 3 (três) serviços consecutivos como sobreaviso, salvo determinação em contrário.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 65',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VII, Seção II — Escalas',
            'caput': 'Art. 66 As permutas de serviço somente serão permitidas com autorização do COCI. Assunção e Passagem do Serviço',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 66',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VIII, Seção II — Escalas',
            'caput': 'Art. 73 A escala do serviço do Oficial de Correições e Disciplina é de 24 horas, no regime de sobreaviso, salvo determinação em contrário.',
            'dispositivos': ['§ 1º A elaboração da escala será de responsabilidade da Diretoria da Corregedoria-Geral.', '§ 2º A escala deverá ser enviada ao COCI, formalmente, até o 20º dia do mês anterior ao mês programado.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 73',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VIII, Seção II — Escalas',
            'caput': 'Art. 74 As permutas de serviço, somente serão permitidas com autorização do COCI. Assunção e Passagem do Serviço',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 74',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IX, Seção II — Escalas',
            'caput': 'Art. 80 A escala do serviço de Oficial de Sobreaviso é no regime de 24 horas, podendo ser na modalidade preta e vermelha, salvo determinação em contrário.',
            'dispositivos': ['§ 1º A elaboração da escala será de responsabilidade do COCI.', '§ 2º As escalas que não são de cunho operacional é de responsabilidade de cada Comandante, Diretor ou Chefe setorial, devendo informar formalmente ao escalante, até o 20º dia do mês anterior ao mês programado.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 80',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IX, Seção II — Escalas',
            'caput': 'Art. 81 O militar poderá tirar, no máximo, 3 (três) serviços consecutivos como sobreaviso, salvo determinação em contrário.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 81',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IX, Seção II — Escalas',
            'caput': 'Art. 82 As permutas de serviço, somente serão permitidas com autorização do COCI. Assunção e Passagem do Serviço',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 82',
            'match': 'exata',
        },
    ],
    ('servico-interno-dia', 'rr'): [
        {
            'heading': 'Cap. II, Seção III — Passagem de Serviço (Superior de Dia)',
            'caput': 'Art. 7º O Superior de Dia deve assumir o serviço no Quartel do Comando-Geral diariamente às 07h30.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 7',
            'match': 'exata',
        },
        {
            'heading': 'Cap. II, Seção III — Passagem de Serviço (Superior de Dia)',
            'caput': 'Art. 8º Após assunção do serviço, o Superior de Dia, assim que possível, deve tomar ciência das ordens e alterações do serviço operacional.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 8',
            'match': 'exata',
        },
        {
            'heading': 'Cap. II, Seção III — Passagem de Serviço (Superior de Dia)',
            'caput': 'Art. 9º Das documentações:',
            'dispositivos': ['I – dar ciência no livro do Coordenador de Dia;', 'II – confeccionar o Extrato Diário do Superior de Dia e o encaminhar ao Comandante do COCI até às 09h30 do término do serviço, salvo em casos fortuitos e/ou força maior, devidamente fundamentados (formalmente) em seu Extrato Diário. Prescrições Gerais'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 9',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção V — Passagem de Serviço (Coordenador de Dia)',
            'caput': 'Art. 25 A passagem de serviço do Coordenador de Dia é realizada diariamente às 07h30.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 25',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção V — Passagem de Serviço (Coordenador de Dia)',
            'caput': 'Art. 26 O Coordenador de Dia, após a assunção do serviço, deve receber todas as alterações das PO da Capital e do Interior, inerentes aos Recursos Operacionais de suas áreas operacionais.',
            'dispositivos': ['Parágrafo único. Poderá enviar o Oficial de Dia/Comandante do Socorro na PO para dirimir quaisquer dúvidas relacionadas aos Recursos Operacionais empregados naquela base operacional.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 26',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção V — Passagem de Serviço (Coordenador de Dia)',
            'caput': 'Art. 27 Os Coordenadores de Dia envolvidos na passagem de serviço devem conferir conjuntamente a relação de material de responsabilidade da função.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 27',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção V — Passagem de Serviço (Coordenador de Dia)',
            'caput': 'Art. 28 Das documentações:',
            'dispositivos': ['I – dar ciência no livro do Oficial de Dia/Comandante do Socorro da Capital e do Interior;', 'II – confeccionar o Livro Diário do Coordenador de Dia e o encaminhar ao Comandante do COCI, concluso, até às 08h30 do término do serviço, salvo em casos fortuitos e/ou força maior, legalmente fundamentado e devidamente documentado em Livro Diário, com prazo limite até a passagem do serviço do dia seguinte;', 'III – solicitar a ciência do Superior de Dia no Livro Diário do Coordenador. Prescrições Gerais'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 28',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IV, Seção IV — Passagem de Serviço',
            'caput': 'Art. 38 O Oficial de Dia/Comandante do Socorro deve assumir o serviço na PO da área de atuação diariamente às 07h30.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 38',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IV, Seção IV — Passagem de Serviço',
            'caput': 'Art. 39 Na assunção ao serviço e/ou passagem do serviço, o Oficial de Dia/Comandante do Socorro deverá:',
            'dispositivos': ['I - conferir o material-carga sob responsabilidade da função;', 'II - verificar com os comandantes das guarnições das PO as condições das viaturas, equipamentos e materiais;', 'III - cientificar-se das alterações de pessoal, bem como das trocas de serviço e possíveis limitações de militares;', 'IV – verificar se o pavilhão foi hasteado e/ou recolhido, bem como se foram cumpridas quaisquer ações relacionadas ao pavilhão.;', 'V - verificar a faxina diária das guarnições nas instalações internas e externas da PO, conforme norma vigente.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 39',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IV, Seção IV — Passagem de Serviço',
            'caput': 'Art. 40 Das documentações:',
            'dispositivos': ['I – dar ciência no Livro Diário das PO sob sua responsabilidade;', 'II – confeccionar o Livro Diário do Oficial de Dia/Comandante do Socorro e o encaminhar ao Comandante do COCI, concluso até às 07h30 do término do serviço, salvo em casos fortuitos e força maior, legalmente fundamentado e devidamente documentado em Livro Diário, com prazo limite até a passagem do serviço do dia seguinte;', 'III – solicitar a ciência do Coordenador Dia no Livro Diário do Oficial de Dia/Comandante do Socorro. Prescrições Gerais'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 40',
            'match': 'exata',
        },
        {
            'heading': 'Cap. V, Seção III — Passagem de Serviço',
            'caput': 'Art. 48 O Oficial de Incêndio, de Salvamento e de Emergência Pré-Hospitalar deve assumir o serviço na PO a qual está escalado, diariamente às 07h30min.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 48',
            'match': 'exata',
        },
        {
            'heading': 'Cap. V, Seção III — Passagem de Serviço',
            'caput': 'Art. 49 Na assunção ao serviço, o Oficial de Incêndio, de Salvamento e de Emergência Pré- Hospitalar deverá:',
            'dispositivos': ['I - conferir o material-carga sob responsabilidade da função;', 'II - verificar as condições de pessoal, das viaturas, equipamentos e materiais;', 'III - escalar e verificar se a faina diária foi realizada nas instalações internas e externas da PO, conforme norma da OBM;', 'IV - conferir conjuntamente (Oficiais de Incêndio, de Salvamento e de Emergência Pré- Hospitalar envolvidos na passagem e/ou recebimento do serviço) a relação de material sob responsabilidade da função.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 49',
            'match': 'exata',
        },
        {
            'heading': 'Cap. V, Seção III — Passagem de Serviço',
            'caput': 'Art. 50 Das documentações:',
            'dispositivos': ['I – elaborar toda a Documentação Diária da PO;', 'II – encaminhar a documentação ao Oficial de Dia/Comandante do Socorro e solicitar desse a ciência no Livro Diário. Prescrições Gerais'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 50',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VI, Seção III — Passagem de Serviço',
            'caput': 'Art. 57 A passagem de serviço do Oficial de Comunicação será realizada diariamente às 07h30.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 57',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VI, Seção III — Passagem de Serviço',
            'caput': 'Art. 58 Ao assumir o serviço, o Oficial de Comunicação deverá tomar conhecimento da situação atual (efetivo e viaturas), missões e ocorrências em andamento.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 58',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VI, Seção III — Passagem de Serviço',
            'caput': 'Art. 59 Os Oficiais de Comunicação envolvidos na passagem do serviço deverão conferir conjuntamente a relação de material sob responsabilidade da função. Prescrições Gerais',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 59',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VII, Seção III — Passagem de Serviço',
            'caput': 'Art. 67 A passagem de serviço do Oficial de Saúde será realizada diariamente às 07h30.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 67',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VII, Seção III — Passagem de Serviço',
            'caput': 'Art. 68 Ao assumir o serviço, o Oficial de Saúde deverá inteirar-se da situação atual de sua atividade e das ocorrências em andamento.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 68',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VII, Seção III — Passagem de Serviço',
            'caput': 'Art. 69 Deve informar ao Coordenador de Dia a disponibilidade para suas atividades, diariamente, até 08h00. Prescrições Gerais',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 69',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VIII, Seção III — Passagem de Serviço',
            'caput': 'Art. 75 A passagem de serviço do Oficial de Correições e Disciplina será realizada diariamente às 07h30.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 75',
            'match': 'exata',
        },
        {
            'heading': 'Cap. VIII, Seção III — Passagem de Serviço',
            'caput': 'Art. 76 Ao assumir o serviço, deverá inteirar-se da situação atual de sua atividade e das ocorrências em andamento. Paragrafo único. Informar ao Coordenador de Dia a disponibilidade para o serviço de sobreaviso, diariamente, até 08h00; Prescrições Gerais',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 76',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IX, Seção III — Passagem de Serviço',
            'caput': 'Art. 83 O serviço do Oficial de Sobreaviso será finalizado às 07h30 ao dia posterior à sua escala de serviço, desde que não esteja empenhado em ocorrência.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 83',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IX, Seção III — Passagem de Serviço',
            'caput': 'Art. 84 Ao assumir o serviço, o Oficial de Sobreaviso deverá inteirar-se da situação atual de sua atividade e das ocorrências em andamento. Paragrafo único. Informar ao Coordenador de Dia a disponibilidade para o serviço de sobreaviso, diariamente, até 08h00. Prescrições Gerais',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 84',
            'match': 'exata',
        },
    ],
    ('servico-operacional', 'rr'): [
        {
            'heading': 'Cap. III, Seção II — Poder de Pronto Emprego',
            'caput': 'Art. 13 Estão subordinados operacionalmente ao Coordenador de Dia, para pronto emprego, todo efetivo operacional escalado nas unidades da Capital e do interior do Estado, para fins de gestão, controle e despacho.',
            'dispositivos': ['§ 1º As Companhias, Pelotões e assemelhados do interior do Estado têm autonomia para atendimento, despacho, gestão de escalas e rotinas.', '§ 2º Compete ao Oficial de Dia/Comandante do Socorro e ao Atendente/Despachante de dia das unidades do interior do Estado manter o Coordenador de Dia informado acerca do PPE e das ocorrências de vulto e/ou repercussão.', '§ 3º Compete aos Comandantes de Companhias da Capital e do Interior manter o Coordenador de Dia informado sobre os seus recursos operacionais disponíveis diariamente.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 13',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção II — Poder de Pronto Emprego',
            'caput': 'Art. 14 O Oficial de Dia/Comandante do Socorro é empregado nas ocorrências, bem como em outras situações oportunas que necessitem da coordenação ou intervenção de oficial, sendo acionado pelo Coordenador de Dia ou conforme determinação superior.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 14',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção II — Poder de Pronto Emprego',
            'caput': 'Art. 15 Os recursos operacionais poderão ser reposicionados em outra PO, para facilitar a mobilização de reforço e/ou cobertura da região, em caso de ausência ou déficit em determinada área por motivos diversos, mediante autorização do Coordenador de Dia.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 15',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção II — Poder de Pronto Emprego',
            'caput': 'Art. 16 Nos casos em que houver necessidade de remanejamento de recursos operacionais requisitados pelas unidades do Interior, e depois de esgotados os recursos de sua unidade, o Coordenador de Dia deverá solicitar autorização para mobilizar recursos necessários ao Superior de Dia.',
            'dispositivos': ['Parágrafo único. Quando a solicitação de apoio resultar de ocorrência de urgência e emergência, o Coordenador de Dia deve despachar as guarnições e comunicar de imediato ao Superior de Dia.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 16',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção II — Poder de Pronto Emprego',
            'caput': 'Art. 17 Quando houver alterações de pessoal, viaturas, materiais e equipamentos no serviço operacional, o Coordenador de Dia tem autonomia para movimentar ou remanejar recursos operacionais, dando ciência ao Superior de Dia.',
            'dispositivos': ['§ 1º Quando as alterações ocorrerem durante o horário de expediente, o comando da unidade deve ser informado para adoção das providências cabíveis.', '§ 2º Quando as alterações ocorrerem fora do horário de expediente, adotará as providências necessárias para mitigar o problema, lançando em sua Documentação Diária.', '§ 3º Nos casos de movimentação dos recursos operacionais, o Oficial de Dia/Comandante do Socorro assessora o Coordenador de Dia no melhor emprego operacional.', '§ 4º As demandas de ocorrências (mergulho, busca na mata, BREC, PP, etc.) que exijam o emprego de recursos operacionais especializados, deverá, após colher todas as informações, fazer contato com a unidade especializada para o atendimento da ocorrência, priorizando o atendimento pela unidade mais próxima à ocorrência.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 17',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção II — Poder de Pronto Emprego',
            'caput': 'Art. 18 No cumprimento de ordens de missão e/ou de ocorrência, caso haja necessidade de quaisquer alterações (horário e/ou dos recursos operacionais), o Coordenador de Dia deve determinar que o Oficial de Dia/Comandante de Socorro constate a necessidade de alteração do planejamento inicial, bem como relatar as falhas encontradas e sugerir ações para as corrigir.',
            'dispositivos': ['Parágrafo único. Caso haja necessidade de recursos humanos e/ou remanejamentos, estes devem ser autorizados pelo Superior de Dia. Ocorrências de Defesa Civil'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 18',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção III — Ocorrências de Defesa Civil',
            'caput': 'Art. 19 O Coordenador de Dia deverá realizar triagem de ocorrências de Defesa Civil em conjunto com o Oficial de Comunicação, priorizando ocorrências que necessitem de socorro imediato (ação de resposta).',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 19',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção III — Ocorrências de Defesa Civil',
            'caput': 'Art. 20 As ocorrências de Defesa Civil não relativas à intervenção imediata devem ser direcionadas para as Coordenadorias Municipais de Proteção e Defesa Civil (COMPDC) e aos Coordenadores de Região da CEPDC.',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 20',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção III — Ocorrências de Defesa Civil',
            'caput': 'Art. 21 O Coordenador de Dia deve colher informações necessárias ao acionamento da ocorrência de Defesa Civil que demande emprego imediato de guarnições da CEPDC, com necessidade de apoio com as guarnições do serviço diário do CBMRR.',
            'dispositivos': ['Parágrafo único. Nesse caso, o Coordenador de Dia aciona a CEPDC, solicitando que seja atendida a ocorrência e, caso a Coordenadoria necessite de apoio, a COCB enviará guarnições.'],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 21',
            'match': 'exata',
        },
        {
            'heading': 'Cap. III, Seção III — Ocorrências de Defesa Civil',
            'caput': 'Art. 22 Em caso de existência simultânea, de múltiplas ocorrências, o Coordenador de Dia deve realizar triagem pela ordem de gravidade e determinar o acionamento de viaturas de acordo com o PPE disponível. Escalas de Serviço',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 22',
            'match': 'exata',
        },
        {
            'heading': 'Cap. IV, Seção II — Emprego',
            'caput': 'Art. 35 O Oficial de Dia/Comandante do Socorro deverá ser empregado em atividades operacionais, cumulativamente com as atribuições inerentes à rotina operacional da OBM e outras que se fizerem necessárias à execução das atividades bombeiro militar ou ordenadas pelo Comandante-Geral. Escalas de Serviço',
            'dispositivos': [],
            'source': 'cf. CBMRR, INOp 01/2024 (Serviço Diário dos Oficiais), Art. 35',
            'match': 'exata',
        },
    ],
}
