# GERADO por scripts/extrair_regulamentos.py — NÃO editar à mão.
# Fonte: Paraná - Regimento Interno.md (extração determinística; mapa nos de-paras).
ENRICHMENT = {
    ('atribuicoes-funcoes', 'pr'): [
        {
            'heading': 'Atribuições Funcionais da 2ª Seção do Estado-Maior - BM/2',
            'caput': 'Art. 3º Compete à 2ª Seção do Estado-Maior (BM/2):',
            'dispositivos': ['I - assessorar e manter o Comandante-Geral, o Subcomandante-Geral e o Chefe do Estado-Maior, constantemente informados dos fatos, informes e informações que digam respeito ao Corpo de Bombeiros Militar do Paraná e às responsabilidades de inteligência e contrainteligência atribuídas à Corporação pelo Sistema Estadual de Inteligência de Segurança Pública, Sistema de Inteligência de Segurança Pública e pelo Sistema Brasileiro de Inteligência;', 'II - produzir conhecimento útil e oportuno necessários às decisões do Comandante- Geral, do Subcomandante-geral e o Chefe do Estado-Maior, bem como aos estudos e planejamentos do Estado-Maior; \uf0d8 BM/3 - 3ª Seção- Planejamento, Operações e Estatística'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições Funcionais da 2ª Seção do Estado-Maior - BM/2", Art. 3',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições Funcionais da Ajudância-Geral',
            'caput': 'Art. 4º Compete à Ajudância-Geral:',
            'dispositivos': ['I - executar os trabalhos de protocolo, boletim geral, registro geral, e outros;', 'II - manter atualizada a situação do efetivo do CCB, com base no QO em vigor, coordenando a coleta dos dados necessários;', 'III - executar a administração financeira e o aprovisionamento do Quartel do Comando- Geral (QCG);', 'IV - executar o apoio de pessoal aos órgãos do Comando-Geral;', 'V - preparar e distribuir o Boletim-Geral, providenciando para que um exemplar permaneça em arquivo;', 'VI - organizar e administrar o Arquivo Geral;', 'VII - organizar e administrar o Centro Histórico;', 'VIII - organizar e manter atualizado nos sistemas os dados dos militares estaduais 01/06/2026, 02:41 Estrutura Organizacional | CORPO DE BOMBEIROS MILITAR DO PARANÁ https://www.bombeiros.pr.gov.br/Pagina/Estrutura-Organizacional 3/18 integrantes da Ajudância-Geral e daqueles que servem no QCG, para fins de acionamento e outros;', 'IX - executar a segurança e serviços gerais do QCG/CBMPR, bem como elaborar escalas de serviço para tal finalidade. \uf0d8 Assessoria Estratégica - Assest'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições Funcionais da Ajudância-Geral", Art. 4',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições Funcionais da Assessoria Estratégica',
            'caput': 'Art. 2º Compete à Assessoria Estratégica (ASSEST):',
            'dispositivos': ['I – O Assessoramento direto ao Comandante-Geral, competindo-lhe as atividades de planejamento, implementação e o monitoramento de projetos e ações institucionais; apoio metodológico e assessoramento no desenvolvimento de projetos; gestão, monitoramento e controle da captação de recursos de fontes orçamentárias alternativas; promoção das relações entre as instituições afetas à segurança pública; assessoramento institucional relacionados aos Poderes Legislativo e Judiciário; assessoramento nos assuntos de Defesa Civil; promoção de políticas públicas, controle e a coordenação do sistema de urgência e emergência, no âmbito da Corporação.', 'II – A Assessoria Estratégica do CBMPR é Órgão de Direção da Corporação e vinculada diretamente ao Comandante-Geral do CBMPR;', 'III – Todos os processos de ordem administrativa ordinária e decorrente da vida castrense da ASSEST, definidos nas competências do Chefe da Assessoria, deverão tramitar diretamente via Ajudância-Geral do CBMPR. 01/06/2026, 02:41 Estrutura Organizacional | CORPO DE BOMBEIROS MILITAR DO PARANÁ https://www.bombeiros.pr.gov.br/Pagina/Estrutura-Organizacional 4/18 \uf0d8 Assessoria de Comunicação Organizacional - Assecom'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições Funcionais da Assessoria Estratégica", Art. 2',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições Funcionais da Assessoria de Comunicação Organizacional',
            'caput': 'Art. 2º Compete à ASSECOM:',
            'dispositivos': ['I - assessorar o Comandante-Geral e o Chefe do Estado-Maior no que se refere à comunicação organizacional e ao cerimonial militar;', 'II - elaborar as normas de comunicação social e do cerimonial militar dentro do CBMPR;', 'III - manter permanente ligação com os órgãos de comunicação social, assegurando o perfeito fluxo de informações entre o Comando-Geral e as instituições de comunicação públicas ou privadas;', 'IV - acompanhar e monitorar as notícias, informações e reportagens veiculadas pelos órgãos de imprensa, relativas aos assuntos do CBMPR;', 'V - desenvolver as atividades de cerimonial militar nos eventos realizados no Quartel do Comando-Geral (QCG), bem como, nas solenidades de interesse do Comando- Geral;', 'VI - desenvolver as atividades relacionadas ao preito da tropa nos eventos de repercussão estadual ou federal, e ainda naquelas de interesse do Comando-Geral;', 'VII - promover estudos e planejamentos voltados à melhoria da comunicação interna, do relacionamento com a imprensa e com o público em geral;', 'VIII - orientar tecnicamente e dar apoio material aos órgãos de execução do CBMPR, que estejam envolvidos na comunicação social. \uf0d8 Consultoria Institucional - CI'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições Funcionais da Assessoria de Comunicação Organizacional", Art. 2',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições Funcionais da Consultoria Institucional',
            'caput': 'Art. 1º, § 2º Compete à CJ:',
            'dispositivos': ['I - manifestar-se acerca de questões de direito compreendidas na política de administração geral da Corporação, esgotada a instância de estudo e manifestação dos órgãos de direção do Comando-Geral, em expedientes lhe forem submetidos para análise;', 'II - examinar os aspectos de legalidade dos atos e normas que lhe forem submetidos à apreciação;', 'III - prestar informações:', 'a) em expedientes que lhe forem encaminhados pelo Comandante-Geral ou pelo Subcomandante-Geral;', 'b) em anteprojetos de leis, minutas de decretos e resoluções, portarias, termos de convênios e protocolo e outros documentos, quando determinado pelo Comandante- Geral ou Subcomandante-Geral;', 'c) em mandados de segurança nos pedidos em que a autoridade apontada como coatora seja o Comandante-Geral.', 'IV - realizar o acompanhamento do trâmite de mandados de segurança interpostos em face de atos praticados por autoridades da Corporação;', 'V - acompanhar o trâmite das ações judiciais e de processos em geral de interesse institucional;', 'VI - fornecer, quando formalmente instada, subsídios para atuação da Procuradoria Geral do Estado (PGE) em assuntos correlatos ao CBMPR;', 'VII - coordenar e controlar a atividade jurídica do CBMPR. 01/06/2026, 02:41 Estrutura Organizacional | CORPO DE BOMBEIROS MILITAR DO PARANÁ https://www.bombeiros.pr.gov.br/Pagina/Estrutura-Organizacional 6/18 \uf0d8 Comissões - CM / CPP / CPO'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições Funcionais da Consultoria Institucional", Art. 1',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições Funcionais da Comissão de Mérito',
            'caput': 'Art. 2º Compete à Comissão de Mérito:',
            'dispositivos': ['I - apreciar o mérito da pessoa ou instituição a ser agraciada;', 'II - propor, justificadamente, a outorga de medalhas aos bombeiros militares da Corporação;', 'III - organizar os processos de concessão das condecorações outorgadas pelo Corpo de Bombeiros Militar do Paraná;', 'IV - publicar e registrar os assuntos relativos às condecorações do pessoal do Corpo de Bombeiros Militar do Paraná;', 'V - homologar e apostilar o uso de medalhas nacionais, estaduais, municipais e estrangeiras recebidas por bombeiros militares;', 'VI - propor alterações nas normas para Concessão da Medalha Bombeiro Militar.'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições Funcionais da Comissão de Mérito", Art. 2',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições Funcionais da Comissão de Promoção de Praças',
            'caput': 'Art. 2º Compete à Comissão de Promoção de Praças:',
            'dispositivos': ['I - incluir e excluir Praças do quadro de acesso;', 'II - propor ao Comandante-Geral a adição por excesso, das Praças de Pré irregularmente promovidas;', 'III - classificar os Subtenentes, Sargentos, Cabos e Soldados no Almanaque Militar de praças da Corporação;', 'IV - organizar os quadros de acesso;', 'V - propor a concessão de medalhas; 01/06/2026, 02:41 Estrutura Organizacional | CORPO DE BOMBEIROS MILITAR DO PARANÁ https://www.bombeiros.pr.gov.br/Pagina/Estrutura-Organizacional 7/18', 'VI - propor a promoção de Praças de Pré, indicando o princípio;', 'VII - informar à Comissão de Promoções de Oficiais sobre os Subtenentes com direito a ingresso no oficialato;', 'VIII - mandar registrar na ficha de promoção dos Sargentos, pontos positivos e negativos;', 'IX - adotar todas as medidas administrativas necessárias para o perfeito atendimento da Lei Nº 19.583, de 05 de julho de 2018 – Lei de Promoção de Praças (LPP).'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições Funcionais da Comissão de Promoção de Praças", Art. 2',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições Funcionais da Comissão de Promoção de Oficiais',
            'caput': 'Art. 2º Compete à Comissão de Promoção de Oficiais:',
            'dispositivos': ['I - incluir e excluir Oficiais do quadro de acesso;', 'II - propor ao Comandante-Geral a adição do Oficiais, promovidos e excedem a previsão constante no Quadro Organizacional;', 'III - classificar os Oficiais no pertinente Almanaque Militar da Corporação;', 'IV - organizar os quadros de acesso;', 'V - propor a concessão de medalhas;', 'VI - indicando o princípio pelo qual serão promovidos os Oficiais;', 'VII - mandar registrar na ficha de promoção dos Oficiais, pontos positivos e negativos;', 'VIII - adotar todas as medidas administrativas necessárias para o perfeito atendimento da Lei Nº 5.944, de 23 de maio de 19698 – Lei de Promoção de Oficiais (LPO). \uf0d8 Corregedoria-Geral - COGER'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições Funcionais da Comissão de Promoção de Oficiais", Art. 2',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições Funcionais da Diretoria de Pessoal',
            'caput': 'Art. 2º Compete à DP:',
            'dispositivos': ['I – elaborar os planos e ordens decorrentes das diretrizes do Comandante-Geral sobre a política de pessoal da Corporação;', 'II – planejar, orientar, fiscalizar e coordenar as políticas de pessoal;', 'III – propor ao Estado-Maior do Corpo de Bombeiros Militar (EM/CBM) as medidas que visem a aprimorar as diretrizes gerais e a aperfeiçoar a legislação e a política de pessoal;', 'IV – providenciar os atos a serem editados pelo Diretor de Pessoal, relativos à contagem de tempo de serviço, procedendo às averbações e os registros necessários, com o fornecimento das respectivas certidões, além da concessão e implantação dos direitos decorrentes que tenham reflexos financeiros;', 'V – estabelecer critérios para o emprego judicioso do pessoal militar e civil, fixando prioridades para o preenchimento de funções, bem como sua distribuição nas atividades–fim e meio;', 'VI – desenvolver, orientar, coordenar e controlar as atividades setoriais relativas à pesquisa e desenvolvimento de competências, organização e métodos, além de auditoria de pessoal;', 'VII – elaborar, em conjunto com a BM/1, normas administrativas relativas à seleção, inclusão, exclusão, promoção, movimentação, classificação, nomeação, substituição, condecorações, afastamentos temporários e outras referentes a pessoal, nos termos da lei;', 'VIII – realizar estudos e inspeções de caráter setorial, propondo ao Comandante–Geral medidas para aprimorar o Sistema de Pessoal;', 'IX – Supervisionar e manter o funcionamento do sistema de pessoal, mantendo estreita ligação com as pertinentes seções dos Comandos Regionais de Bombeiro Militar (CRBM) e demais Unidades;', 'X – promover estudos, análises e pesquisas, tendo em vista o aprimoramento e a racionalização de suas atividades;', 'XI – auxiliar a 1ª Seção do Estado–Maior na elaboração de normas que digam respeito ao efetivo da Corporação;', 'XII – cooperar na elaboração dos anteprojetos de legislação referentes a pessoal;', 'XIII – manter levantamentos estatísticos sobre a situação financeira, assistência social, jurídica, religiosa, habitação, bem como acerca da situação disciplinar, o moral e a 01/06/2026, 02:41 Estrutura Organizacional | CORPO DE BOMBEIROS MILITAR DO PARANÁ https://www.bombeiros.pr.gov.br/Pagina/Estrutura-Organizacional 10/18 motivação dos integrantes da Corporação, de forma a subsidiar as diretrizes de política de pessoal a serem elaboradas;', 'XIV – colaborar com a Diretoria de Apoio Logístico e Finanças em suas atividades de auditoria;', 'XV – manter atualizados os cadastros individuais do efetivo;', 'XVI – orientar, coordenar, fiscalizar, controlar e executar as atividades relacionadas com a vida funcional do pessoal, mantendo registros individuais;', 'XVII – coordenar, fiscalizar, controlar e executar as atividades referentes à documentação do pessoal;', 'XVIII – averbar e controlar os atos referentes à implantação de pensão alimentícia, décimo– terceiro salário e auxílio-funeral;', 'XIX – elaborar sumários e relatórios de pessoal;', 'XX – manter atualizada a situação dos efetivos, considerando o Quadro de Organização (QO) em vigor, coordenando a coleta de dados e procedendo aos trabalhos necessários.', 'XXI – controlar o efetivo geral da Corporação, mantendo atualizados os respectivos registros;', 'XXII – elaborar projetos voltados à fixação do efetivo e QO;', 'XXIII – preparar os atos de movimentação de militares estaduais, de acordo com as ordens do Comandante–Geral e as disposições legais e regulamentares;', 'XXIV – manter o controle do pessoal empregado na atividade–fim e na atividade–meio, bem como dos agregados ou afastados da Corporação;', 'XXV – realizar o controle do pessoal que frequenta cursos ou estágios fora da Corporação, bem como dos militares estaduais à disposição de órgãos ou autoridades;', 'XXVI – executar as atividades relativas ao banco de permutas na Corporação;', 'XXVII – planejar, coordenar, controlar e fiscalizar as atividades de identificação funcional da CBMPR;', 'XXVIII – coordenar, fiscalizar, controlar e executar as atividades relativas aos inativos, pensionistas e civis;', 'XXIX – executar as atividades relativas ao porte, registro e aquisição de arma de fogo dos inativos;', 'XXX – estabelecer rotinas internas e procedimentos relativos a direitos, deveres e incentivos de pessoal;', 'XXXI – preparar os atos de exclusão, agregação, concessão e cassação de licenças a serem editados pelo Comandante–Geral, bem como de transferência para a reserva ou reforma de militares estaduais;', 'XXXII – publicar os editais para ingresso na CBMPR e coordenar, controlar e fiscalizar as atividades de recrutamento e de seleção;', 'XXXIII – regular e processar o ingresso na Corporação;', 'XXXIV – coordenar, fiscalizar, controlar e executar as atividades de assistência à saúde, assistência social e assistência religiosa;', 'XXXV – integrar cadastros de absenteísmo, informações médicas e incapacidades;', 'XXXVI – encarregar–se do psicoprognóstico e orientação dos componentes da Corporação. 01/06/2026, 02:41 Estrutura Organizacional | CORPO DE BOMBEIROS MILITAR DO PARANÁ https://www.bombeiros.pr.gov.br/Pagina/Estrutura-Organizacional 11/18 \uf0d8 Diretoria de Apoio Logístico e Finanças - DALF'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições Funcionais da Diretoria de Pessoal", Art. 2',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições Funcionais da Diretoria de Apoio Logístico e Finanças',
            'caput': 'Art. 4º Compete à Diretoria de Apoio Logístico e Finanças (DALF):',
            'dispositivos': ['I - coordenar, fiscalizar e controlar as atividades de apoio logístico e finanças da Corporação, de acordo com as diretrizes baixadas pelo Comandante-Geral;', 'II - coordenar e instruir os processos de compras e licitações de interesse institucional global, visando atender as demandas coletivas da Corporação;', 'III - orientar e assessorar as Unidades da Corporação nos processos de compras e licitações de seu interesse;', 'IV - controlar, fiscalizar e realizar, por seus próprios meios ou por terceiros, a manutenção do material bélico, de intendência e outros;', 'V - coletar e fornecer sumários e relatórios sobre o estado de conservação e utilização de material e instalações;', 'VI - elaborar Boletins Reservados em assuntos de Logística;', 'VII - controlar e fiscalizar o correto registro dos bens patrimoniais da Corporação, solicitando às unidades responsáveis, atualizações e correções quando necessário;', 'VIII - desempenhar, no âmbito da Corporação, as atividades de finanças, contabilidade e auditoria, de acordo com as diretrizes baixadas pelo Comandante-Geral;', 'IX - realizar o acompanhamento orçamentário, cuja fonte de recursos seja o tesouro estadual;', 'X - planejar orçamento de exercícios vindouros;', 'XI - acompanhar o orçamento e o financeiro de convênios do CBMPR firmados com secretarias de estado e entidades governamentais estaduais e federais;', 'XII - orientar, fiscalizar e controlar as comprovações de despesas dos órgãos do CBMPR;', 'XIII - emitir manifestação em questões técnicas de finanças, contabilidade e auditoria;', 'XIV - propor normas e promover estudos para o aprimoramento do Sistema de 01/06/2026, 02:41 Estrutura Organizacional | CORPO DE BOMBEIROS MILITAR DO PARANÁ https://www.bombeiros.pr.gov.br/Pagina/Estrutura-Organizacional 12/18 Administração Financeira, Contabilidade e Auditoria;', 'XV - apoiar a Assessoria Estratégica do Comando-Geral na consolidação dos Projetos de Captação de Recursos Alternativos;', 'XVI - encarregar-se da administração dos recursos que lhe forem atribuídos;', 'XVII - efetuar pagamentos de despesas e a contabilidade dos recursos extraorçamentários;', 'XVIII - montar o processo e a prestação de contas junto ao órgão competente;', 'XIX - analisar e avaliar permanentemente as finanças, bem como realizar a execução da política e da administração financeira da Corporação, de acordo com as diretrizes do Comandante-Geral;', 'XX - receber as prestações de contas das OBMs, e auditá-las na forma dos regulamentos em vigor;', 'XXI - apoiar a supervisão do Comandante-Geral sobre as atividades financeiras. \uf0d8 Diretoria de Atividades Técnicas - DAT'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições Funcionais da Diretoria de Apoio Logístico e Finanças", Art. 4',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições Funcionais da Diretoria de Atividades Técnicas',
            'caput': 'Art. 3º Compete à DAT:',
            'dispositivos': ['I – estabelecer as diretrizes da Segurança Contra Incêndios e TIC;', 'II – fomentar, via Corpo Técnico, que é o colegiado interno responsável por estabelecer as normas de prevenção de incêndio, e com base nas referências técnicas nacionais e internacionais, a legislação de Segurança Contra Incêndios;', 'III – fomentar, estruturar e viabilizar treinamentos para o conhecimento e a interpretação normativa;', 'IV - apoiar o desenvolvimento e controlar o funcionamento dos sistemas 01/06/2026, 02:41 Estrutura Organizacional | CORPO DE BOMBEIROS MILITAR DO PARANÁ https://www.bombeiros.pr.gov.br/Pagina/Estrutura-Organizacional 13/18 informatizados, utilizados pelos públicos interno e externo, responsáveis pelo gerenciamento de informações;', 'V – realizar, com o apoio dos CRBMs e OBMs, estudos e pesquisas voltados à segurança contra incêndios com o objetivo de manter a normatização, os fluxos de processos administrativos e os protocolos de atendimento atualizados;', 'VI – realizar a governança de TIC, sobretudo, a definição de políticas próprias ao emprego da tecnologia e seus produtos, a utilização e a proteção de dados, a gestão de riscos, a padronização de equipamentos de informática, etc.;', 'VII – coordenar os processos de concepção, desenvolvimento e suporte dos sistemas informatizados em uso pela Corporação, fazendo a análise e propositura de metodologias, padrões de tecnologia e arquitetura dos softwares disponíveis;', 'VIII – realizar projetos e pesquisas de inovações na área de TIC;', 'IX – sustentar os ativos e os sistemas que estruturam o uso de tecnologia no CBMPR, apontando as necessidades de ampliação e evolução, bem como garantir aspectos de segurança, infraestrutura, redes, proteção de dados e sistemas. \uf0d8 Escola Superior de Bombeiro Militar - ESBM'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições Funcionais da Diretoria de Atividades Técnicas", Art. 3',
            'match': 'exata',
        },
    ],
    ('competencias-apoio-assessoramento', 'pr'): [
        {
            'heading': 'Atribuições do Estado-Maior',
            'caput': 'Art. 14 O Estado-Maior - EM é o órgão de direção geral responsável, perante o Comandante- Geral do Corpo de Bombeiros Militar do Paraná - CBMPR, pelo planejamento estratégico da Corporação, cabendo-lhe a elaboração de diretrizes e ordens do Comando-Geral no acionamento dos órgãos de direção setorial e de execução no cumprimento de suas missões.',
            'dispositivos': ['§ 1º O Chefe do Estado-Maior será indicado pelo Comandante-Geral e nomeado pelo Governador do Estado, dentre os Coronéis Combatentes da ativa da Corporação.', '§ 2º O Chefe do Estado-Maior terá precedência hierárquica e funcional sobre os demais Oficiais e Praças, exceto o Comandante-Geral e o Subcomandante-Geral. \uf0d8 BM/1 - 1ª Seção - Pessoal e Legislação'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições do Estado-Maior", Art. 14',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições da 1ª Seção do Estado-Maior - BM/1',
            'caput': 'Art. 14, § 3º O Estado-Maior, para realizar o planejamento estratégico, as proposições normativas da Corporação e demais atribuições, será composto pelas seguintes seções:',
            'dispositivos': ['I - 1ª Seção - BM/1: responsável pelos assuntos relativos a pessoal e legislação; \uf0d8 BM/2 - 2ª Seção - Inteligência'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da 1ª Seção do Estado-Maior - BM/1", Art. 14',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições da 2ª Seção do Estado-Maior - BM/2',
            'caput': 'Art. 14, § 3º O Estado-Maior, para realizar o planejamento estratégico, as proposições normativas da Corporação e demais atribuições, será composto pelas seguintes seções:',
            'dispositivos': ['II - 2ª Seção - BM/2: responsável pelas atividades de inteligência;'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da 2ª Seção do Estado-Maior - BM/2", Art. 14',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições da 3ª Seção do Estado-Maior - BM/3',
            'caput': 'Art. 14, § 3º O Estado-Maior, para realizar o planejamento estratégico, as proposições normativas da Corporação e demais atribuições, será composto pelas seguintes seções:',
            'dispositivos': ['III - 3ª Seção - BM/3: responsável pelos assuntos relativos a planejamento, operações e estatística; \uf0d8 BM/4 - 4ª Seção - Logística'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da 3ª Seção do Estado-Maior - BM/3", Art. 14',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições da 4ª Seção do Estado-Maior - BM/4',
            'caput': 'Art. 14, § 3º O Estado-Maior, para realizar o planejamento estratégico, as proposições normativas da Corporação e demais atribuições, será composto pelas seguintes seções:',
            'dispositivos': ['IV - 4ª Seção - BM/4: responsável pelos assuntos relativos à logística da Corporação \uf0d8 Ajudância-Geral - AG'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da 4ª Seção do Estado-Maior - BM/4", Art. 14',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições da Ajudância-geral',
            'caput': 'Art. 16 A Ajudância-Geral, subordinada ao Chefe de Gabinete, exercerá o apoio administrativo ao Comando-Geral, competindo-lhe:',
            'dispositivos': ['I - a organização, a direção e a supervisão:', 'a) do pessoal auxiliar de todos os órgãos do Comando-Geral;', 'b) do efetivo da Banda de Música do Corpo de Bombeiros Militar do Paraná - CBMPR;', 'II - a coordenação dos trabalhos de protocolo geral da Corporação;', 'III - o controle da entrada e retirada de processos e documentos do arquivo geral;', 'IV - a elaboração dos boletins-gerais;', 'V - o desenvolvimento das demais tarefas relacionadas com a segurança do aquartelamento e dos serviços gerais do Comando-Geral;', 'VI - a promoção das atividades necessárias para a manutenção e desenvolvimento do centro histórico.'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da Ajudância-geral", Art. 16',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições da Assessoria Estratégica',
            'caput': 'Art. 17 A Assessoria Estratégica é órgão que presta suporte ao Comandante-Geral, competindo-lhe as atividades de:',
            'dispositivos': ['I - planejamento, implementação e monitoramento de projetos e ações institucionais;', 'II - apoio metodológico e assessoramento no desenvolvimento de projetos;', 'III - gestão, monitoramento e controle da captação de recursos;', 'IV - promoção das relações entre as instituições afetas à segurança pública;', 'V - assessoramento institucional relacionado aos Poderes Legislativo e Judiciário;', 'VI - assessoramento nos assuntos de defesa civil;', 'VII - promoção de políticas públicas, controle e coordenação do Serviço Integrado de Atendimento ao Trauma em Emergência - SIATE, no âmbito da Corporação.'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da Assessoria Estratégica", Art. 17',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições da Assessoria de Comunicação Organizacional',
            'caput': 'Art. 18 A Assessoria de Comunicação Organizacional é órgão que presta assessoramento ao Comando-Geral, competindo-lhe as atividades de:',
            'dispositivos': ['I - comunicação social, campanhas de educação preventiva e assessoria de imprensa;', 'II - organização de solenidades na sede do Corpo de Bombeiros Militar do Paraná - CBMPR, orientando e fiscalizando a execução de eventos nas demais unidades.'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da Assessoria de Comunicação Organizacional", Art. 18',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições da Consultoria Institucional',
            'caput': 'Art. 20 A Consultoria Institucional é o órgão que presta assessoramento direto ao Comandante-Geral e ao Subcomandante-Geral, competindo-lhe:',
            'dispositivos': ['I - o estudo de questões de direito compreendidas na política de administração geral da Corporação, exames de aspectos de legalidade dos atos e normas que forem submetidos à sua apreciação e demais atribuições que venham a ser previstas em regulamentos;', 'II - a orientação quanto ao exato cumprimento de decisões e sentenças judiciais, de acordo com as orientações emanadas pela Procuradoria-Geral do Estado - PGE;', 'III - a compilação de elementos de fato e de direito para preparar as informações que devem ser prestadas à Procuradoria-Geral do Estado - PGE para a defesa dos interesses do Estado em ações judiciais;', 'IV - a análise das minutas e convênios que forem submetidos à sua apreciação, verificando se preenchem os requisitos legais necessários à sua celebração.'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da Consultoria Institucional", Art. 20',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições das Comissões',
            'caput': 'Art. 21 Existirão, no âmbito do Corpo de Bombeiros Militar do Paraná - CBMPR, em caráter permanente, as seguintes comissões, subordinadas diretamente ao Comandante-Geral:',
            'dispositivos': ['I - Comissão de Promoções de Oficiais - CPO;', 'II - Comissão de Promoções de Praças - CPP;', 'III - Comissão de Mérito - CM.', 'Parágrafo único. As comissões serão regulamentadas por ato do Comandante-Geral, que poderá constituir outras comissões de caráter temporário.'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições das Comissões", Art. 21',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições da Diretoria de Pessoal',
            'caput': 'Art. 28 A Diretoria de Pessoal é o órgão de direção setorial do sistema de pessoal, 01/06/2026, 02:41 Estrutura Organizacional | CORPO DE BOMBEIROS MILITAR DO PARANÁ https://www.bombeiros.pr.gov.br/Pagina/Estrutura-Organizacional 9/18 responsável por:',
            'dispositivos': ['I - desenvolvimento, coordenação, fiscalização, orientação, acompanhamento e controle das atividades relacionadas com a classificação e movimentação de pessoal;', 'II - mobilização, inativos, cadastro e avaliação, direitos, deveres, incentivos, gerenciamento e inspeção da folha de pagamento;', 'III - identificação, pessoal civil, serviço auxiliar temporário e recrutamento;', 'IV - acompanhamento e controle das atividades técnico-administrativas relativas aos serviços de saúde física e mental, assistência social e psicológica;', 'V - assessoramento nos assuntos referentes a pessoal.'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da Diretoria de Pessoal", Art. 28',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições da Diretoria de Apoio Logístico e Finanças',
            'caput': 'Art. 29 A Diretoria de Apoio Logístico e Finanças é o órgão de direção setorial responsável por:',
            'dispositivos': ['I - coordenação, controle e execução das atividades de logística;', 'II - suprimento, manutenção e controle patrimonial da Corporação;', 'III - planejamento, acompanhamento e execução orçamentária e financeira;', 'IV - atividades de controladoria e auditoria de recursos descentralizados.'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da Diretoria de Apoio Logístico e Finanças", Art. 29',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições da Diretoria de Atividades Técnicas',
            'caput': 'Art. 30 A Diretoria de Atividades Técnicas é o órgão de direção setorial responsável pela coordenação, controle e assessoramento em assuntos relacionados:',
            'dispositivos': ['I - à prevenção e combate a incêndios e desastres em edificações, estabelecimentos, áreas de risco e eventos temporários, atuando por meio do gerenciamento normativo, estudos e pesquisa de incêndios;', 'II - à tecnologia da informação e comunicação, com ações de gestão e desenvolvimento de sistemas informatizados, infraestrutura, segurança, projetos, inovações e governança.'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da Diretoria de Atividades Técnicas", Art. 30',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições da Escola Superior de Bombeiro Militar <',
            'caput': 'Art. 31 A Escola Superior de Bombeiro Militar é o órgão de direção setorial de ensino e instrução no âmbito do Corpo de Bombeiros Militar do Paraná - CBMPR, responsável pelo planejamento, coordenação, fiscalização, execução e controle das atividades de ensino desenvolvidas pela Corporação, podendo atuar em parceria com outras instituições. \uf0d8 Comandos Regionais de Bombeiro Militar Criados através da PORTARIA Nº 021, DE 26 DE ABRIL DE 2019, que Dispõe da organização e atuação dos Comandos Regionais de Bombeiro Militar',
            'dispositivos': [],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da Escola Superior de Bombeiro Militar <", Art. 31',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições da Escola Superior de Bombeiro Militar <',
            'caput': 'Art. 2º Os CRBMs são escalões intermediários de comando, incumbindo-lhes a execução das missões de bombeiros nas suas regiões.',
            'dispositivos': ['Parágrafo único. São incumbências dos CRBM: 01/06/2026, 02:41 Estrutura Organizacional | CORPO DE BOMBEIROS MILITAR DO PARANÁ https://www.bombeiros.pr.gov.br/Pagina/Estrutura-Organizacional 14/18', 'I – o desenvolvimento de ações operacionais estratégicas nas áreas de combate a incêndio, busca, salvamento, socorro público, ações de defesa civil e de prevenção a incêndio e a desastres, visando ao emprego dinâmico e eficiente dos recursos humanos e materiais sob sua responsabilidade;', 'II – a propositura de distribuição do efetivo operacional, de forma que se atinja o menor tempo-resposta possível ao atendimento, com especial atenção aos pontos mais vulneráveis à ocorrência de sinistros;', 'III – a fiscalização periódica das unidades subordinadas, visando ao fiel cumprimento da política operacional do Comando do Corpo de Bombeiros Militar e do plano de emprego operacional;', 'IV – a fiscalização das ações das seções de justiça e disciplina das Unidades subordinadas, bem como férias e afastamentos dos respectivos Comandantes de Grupamento de Bombeiros e de Subgrupamento de Bombeiros Independentes;', 'V – a fiscalização das Seções de Prevenção e Combate a Incêndios e a Desastres (SPCID) das Unidades subordinadas, de forma a orientar o cumprimento da legislação afeta à temática, visando ao aumento da produtividade e à qualidade do serviço prestado ao contribuinte;', 'VI – a gestão logística dentro de sua região.'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da Escola Superior de Bombeiro Militar <", Art. 2',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições da Escola Superior de Bombeiro Militar <',
            'caput': 'Art. 3º Os CRBM são organizados em:',
            'dispositivos': ['I – Comandante;', 'II – Chefe do Estado-Maior;', 'III – Estado-Maior;', 'IV – Comissão Técnica de Terceira Instância;', 'V – Centro de Operações de Bombeiros (COBOM), somente no 1º CRBM. E através de Decreto Estadual nº 1552 de 2019, foi definido que os comandos regionais são orgão de ececução do CBMPR (Art. 11) e tem responsabilidade operacional e administrativas, nas areas de atuação, estabelecidas pelas unidades que os contemplam. O 1º Comando Regional (1º CRBM) abarca o atendimento operacional da capital do estado, Região Metropolitana, Litoral e Campos Gerais, cobrindo uma área de 75 municípios, sendo composto pelas seguintes Unidades Operacionais: • 1º Batalhão de Bombeiro Militar, com sede em Curitiba; • 2º Batalhão de Bombeiro Militar, com sede em Ponta Grossa; • 6° Batalhão de Bombeiro Militar, com sede em São José dos Pinhais; • 7° Batalhão de Bombeiro Militar, com sede em Colombo; • 8° Batalhão de Bombeiro Militar, com sede em Paranaguá; • 6ª Companhia Independente de Bombeiro Militar, com sede em Irati. O 2º Comando Regional de Bombeiro Militar tem responsabilidade na circunscrição territorial sobre 188 municípios, nos quais estão distribuídas as seguintes unidades subordinadas: 01/06/2026, 02:41 Estrutura Organizacional | CORPO DE BOMBEIROS MILITAR DO PARANÁ https://www.bombeiros.pr.gov.br/Pagina/Estrutura-Organizacional 15/18 • 3º Batalhão de Bombeiro Militar, com sede em Londrina; • 5º Batalhão de Bombeiro Militar, com sede em Maringá; • 11° Batalhão de Bombeiro Militar, com sede em Apucarana; • 1ª Companhia Independente de Bombeiro Militar, com sede em Ivaiporã; • 3ª Companhia Independente de Bombeiro Militar, com sede em Santo Antônio da Platina; • 4ª Companhia Independente de Bombeiro Militar, com sede em Cianorte; • 5ª Companhia Independente de Bombeiro Militar, com sede em Paranavaí. O 3º Comando Regional de Bombeiro Militar, com responsabilidade na circunscrição territorial sobre 136 municípios nos quais estão distribuídas as seguintes unidades subordinadas: • 4º Batalhão de Bombeiro Militar, com sede em Cascavel; • 9° Batalhão de Bombeiro Militar, com sede em Foz do Iguaçu; • 10° Batalhão de Bombeiro Militar, com sede em Francisco Beltrão; • 12° Batalhão de Bombeiro Militar, com sede em Guarapuava; • 13° Batalhão de Bombeiro Militar, com sede em Pato Branco; • 2ª Companhia Independente de Bombeiro Militar, com sede em Umuarama. Conforme a Lei 22.206 - 29 de novembro de 2024, que dispõe sobre a organização básica do Corpo de Bombeiros Militar do Paraná, em seu artigo 11, Inciso I, estabele o CRBM como orgão de execução. \uf0d8 Batalhões de Bombeiro Militar'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da Escola Superior de Bombeiro Militar <", Art. 3',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições dos Batalhões de Bombeiro Militar',
            'caput': 'Art. 39 Os Batalhões de Bombeiro Militar - BBM são constituídos de:',
            'dispositivos': ['I - um Comandante;', 'II - um Subcomandante;', 'III - um Estado-Maior;', 'IV - elementos de Comando (Grupo de Comando e Serviços) e de frações subordinadas (Cia. BM, Pel. BM e Gp. BM) em número variável, de acordo com as necessidades indicadas pela missão. \uf0d8 Companhias Independentes de Bombeiro Militar'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições dos Batalhões de Bombeiro Militar", Art. 39',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições das Companhias Independentes de Bombeiro Militar',
            'caput': 'Art. 40 As Companhias Independentes de Bombeiro Militar - Cia. Ind. BM são constituídas de:',
            'dispositivos': ['I - um Comandante;', 'II - um Subcomandante;', 'III - um Estado-Maior; 01/06/2026, 02:41 Estrutura Organizacional | CORPO DE BOMBEIROS MILITAR DO PARANÁ https://www.bombeiros.pr.gov.br/Pagina/Estrutura-Organizacional 17/18', 'IV - elementos de Comando (Grupo de Comando e Serviços) e de frações subordinadas (Pel. BM e Gp. BM) em número variável, de acordo com as necessidades indicadas pela missão. 01/06/2026, 02:41 Estrutura Organizacional | CORPO DE BOMBEIROS MILITAR DO PARANÁ https://www.bombeiros.pr.gov.br/Pagina/Estrutura-Organizacional 18/18'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições das Companhias Independentes de Bombeiro Militar", Art. 40',
            'match': 'exata',
        },
    ],
    ('disciplina-correicao', 'pr'): [
        {
            'heading': 'Atribuições da Corregedoria-Geral',
            'caput': 'Art. 23 A Corregedoria-Geral do Corpo de Bombeiros Militar do Paraná - CBMPR é o órgão técnico, subordinado ao Comandante-Geral, com atuação em todo o Estado, com a finalidade de:',
            'dispositivos': ['I - assegurar a correta aplicação da lei;', 'II - padronizar os procedimentos de Polícia Judiciária Militar e de processos e procedimentos administrativos;', 'III - realizar correições, fiscalizações e garantir a preservação dos princípios da hierarquia e disciplina na Corporação.', 'Parágrafo único. O Corregedor-Geral será indicado pelo Comandante-Geral e nomeado pelo Governador do Estado, dentre os Coronéis Combatentes da ativa da Corporação.'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições da Corregedoria-Geral", Art. 23',
            'match': 'exata',
        },
        {
            'heading': 'Atribuições Funcionais da Corregedoria-Geral',
            'caput': 'Art. 3º À COGER-CBMPR compete, dentre outras atribuições:',
            'dispositivos': ['I - realizar correições, inspeções e fiscalizações nas diversas Unidades da Corporação;', 'II - manter permanente acompanhamento do público interno, visando prevenir e reprimir a prática de atos de improbidade administrativa, crimes em geral e violações da disciplina e hierarquia militares, bem como produzir o suporte probatório necessário à instauração dos respectivos processos e procedimentos administrativos, quando de sua ocorrência;', 'III - acompanhar, controlar e fiscalizar os autos dos procedimentos de Polícia Judiciária Militar no âmbito da Corporação, sanear e preparar os atos de competência do Comandante-Geral e informar outros documentos quando solicitado;', 'IV - expedir orientações sobre a aplicação da legislação relativa à apuração das infrações criminais e disciplinares, inclusive promover a interpretação de jurisprudências e outras matérias atinentes aos serviços da Corregedoria;', 'V - apurar crimes militares, fatos de cunho administrativo e faltas disciplinares, realizando os procedimentos legais, quando forem avocados, instaurados ou determinados pelo Comandante-Geral;', 'VI - requisitar o comparecimento de militares estaduais e civis vinculados de qualquer forma à Corporação;', 'VII - receber reclamações contra ações ou omissões perpetradas por militares estaduais, tomando as medidas legais cabíveis ou as encaminhando à autoridade competente;', 'VIII - prover apoio aos Comandantes de Unidades e a quaisquer órgãos, quando solicitado, prestando auxílio técnico especializado, procedendo a diligências e exarando informações e pareceres;', 'IX - acompanhar procedimentos investigatórios a que tenham sido submetidos militares estaduais em repartições policiais, organizações militares e outras;', 'X - manter atualizados os arquivos de identificação por todos os meios disponíveis e o registro dos antecedentes dos integrantes da Corporação;', 'XI - cumprir, prioritariamente, os mandados de prisão e alvarás de soltura que envolvam integrantes da Corporação;', 'XII - adotar, de ofício, ou, quando provocada, qualquer outra providência necessária ao fiel desempenho das atribuições que lhe são conferidas na presente Lei;', 'XIII - outras atividades por delegação de competência do Comandante-Geral. \uf0d8 Diretoria de Pessoal - DP'],
            'source': 'cf. CBMPR, Atribuições institucionais (portal oficial), bloco "Atribuições Funcionais da Corregedoria-Geral", Art. 3',
            'match': 'exata',
        },
    ],
}
