# GERADO por scripts/extrair_regulamentos.py — NÃO editar à mão.
# Fonte: Distrito Federal - Regimento Interno.md (extração determinística; mapa nos de-paras).
ENRICHMENT = {
    ('disciplina-correicao', 'df'): [
        {
            'heading': 'TÍT. I, Cap. XIV — Corregedoria',
            'caput': 'Art. 95. A Corregedoria – COGED possui a seguinte estrutura:',
            'dispositivos': ['I - Seção de Assessoramento em Processos Administrativos Disciplinares e Judiciais – SAPAJ;', 'II - Seção de Polícia Judiciária Militar e Investigação Correcional – SEPOL;', 'III - Seção de Instrução de Processos Administrativos Disciplinares – SEPAD;', 'IV - Seção de Processos Administrativos de Responsabilidade Civil por Danos ao Erário – SEARC;', 'V - Seção de Acompanhamento Judicial e Extrajudicial de Pessoal – SEJEP;', 'VI - Seção de Gerenciamento Processual e Cartorário – SEGEC;', 'VII - Seção de Apoio Administrativo – SEAAD. Das Competências Orgânicas'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 95',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. XIV — Corregedoria',
            'caput': 'Art. 96. À Corregedoria, além das atribuições previstas no art. 78, compete:',
            'dispositivos': ['I - planejar, organizar, dirigir e controlar as atividades de instauração, confecção, instrução, homologação e solução dos pr ocessos administrativos e judiciais no âmbito do CBMDF, sob a esfera de responsabilidade penal, cível e administrativa;', 'II - instaurar e instruir sindicâncias e inquéritos policiais militares;', 'III - promover investigações visando instruir procedimentos em curso n o âmbito de sua competência;', 'IV - avocar atos, procedimentos e processos disciplinares instaurados no âmbito da Corporação ou declarar a nulidade desses instrumentos, exceto os de competência do Comandante-Geral e do Controlador;', 'V - acompanhar demandas administrativas e judiciais envolvendo bombeiros militares;', 'VI - cumprir ou determinar o cumprimento de diligências requisitadas pelos órgãos dos Poderes Executivo, Judiciário e Legislativo, bem como do Ministério Público, acompanhando e controlando os atos administrativos praticados, com vistas à averiguação de suas soluções;', 'VII - verificar os requisitos legais e solucionar ou, conforme o caso, homologar os processos administrativos disciplinares e de responsabilidade civil por dano ao erário no âmbito do CBMDF, exceto os de competência do Comandante-Geral e do Controlador;', 'VIII - supervisionar as atividades de escolta e custódia desenvolvidas pelo NCUST, bem como outras relacionadas com as atribuições da Corregedoria;', 'IX - instruir processos de Conselho de Justificação e de Co nselho de Disciplina, bem como Processos Administrativos de Licenciamento;', 'X - adotar os procedimentos legais cabíveis visando controlar a remissão, progressão de estágio, indulto, comutação, redução ou agravamento de pena dos bombeiros sob custódia;', 'XI - controlar e acompanhar o andamento dos processos judiciais criminais que abarquem militares do CBMDF;', 'XII - manter a DIGEP e a DINAP informadas acerca das alterações relativas ao inciso anterior.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 96',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. XIV — Corregedoria',
            'caput': 'Art. 97. À Seção de Assessoramento em Processos Administrativos Disciplinares e Judiciais, além das atribuições constantes no art. 79, compete:',
            'dispositivos': ['I - instruir processos referentes à instauração, análise e solução de:', 'a) Conselho de Disciplina;', 'b) Conselho de Justificação;', 'c) Processo Administrativo de Licenciamento a bem da disciplina;', 'd) Inquérito Policial Militar;', 'e) Processos Administrativos Disciplinares ou Sindicâncias.', 'II - analisar procedimento correicional e propor ato de impulsão, caso necessário;', 'III - indicar os encarregados dos procedimentos a ser instaurados ou em andamento;', 'IV - analisar e responder às demandas relacionadas aos processos e procedimentos previstos no inciso I;', 'V - analisar e responder aos pedidos de informações formulados pelos órgãos competentes com a finalidade de instruir o andamento de processos judiciais, quando o obje to esteja relacionado aos processos e procedimentos previstos no inciso I deste artigo;', 'VI - propor alterações dos diplomas infralegais e instrumentos normativos, visando fortalecer os mecanismos de controle e evitar a ocorrência e/ou repetição de irregularidades;', 'VII - propor normas para o serviço de Corregedoria por meio de Portarias, Instruções Normativas e Recomendações referentes à matéria disciplinar da Corporação.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 97',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. XIV — Corregedoria',
            'caput': 'Art. 98. À Seção de Polícia Judiciária Militar e Investigação Correcional, além das atribuiçõ es previstas no art. 79, compete:',
            'dispositivos': ['I - planejar, orientar e coordenar as atividades de investigação de competência da Corregedoria;', 'II - instruir inquéritos policiais militares no âmbito do CBMDF;', 'III - realizar operações e demais atividades de investigação visando instruir processos em curso ou fornecer elementos indispensáveis à instauração de novos procedimentos;', 'IV - executar a coleta e busca de dados inerentes às atividades de competência da Corregedoria;', 'V - cooperar com outros órgãos de investigação da Corporação e do Distrito Federal;', 'VI - controlar, instruir e delegar os Procedimentos de Apuração Preliminar instaurados pelas unidades do CBMDF;', 'VII - monitorar, quando solicitado, o tráfego da rede e dos logs das máquinas de informática do CBMDF, visando combater ações del ituosas em redes de computadores, dispositivo de comunicação ou sistema informatizado;', 'VIII - propor a instauração de inquérito policial militar quando houver indício de crime militar praticado em ambiente cibernético;', 'IX - coletar e atestar a veracidade e autenti cidade dos dados provenientes de um equipamento de informática com o objetivo de instruir processo administrativo e criminal;', 'X - sugerir a nomeação de oficiais e praças de outras OBMs como encarregados, escrivães e demais funções necessárias à condução dos inquéritos policiais militares, caso necessário.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 98',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. XIV — Corregedoria',
            'caput': 'Art. 99. À Seção de Instrução de Processos Administrativos e Disciplinares, além das atribuições previstas no art. 79, compete:',
            'dispositivos': ['I - conduzir as sindicâncias e processos administrativos de licenciamento instau rados pelo Corregedor, pelo Controlador ou pelo Comandante-Geral;', 'II - instruir os processos relacionados no Inciso I, possibilitando a tomada de decisão pelas autoridades competentes;', 'III - atentar para os regramentos aos quais estão submetidos os processos administrativos;', 'IV - conduzir processos administrativos disciplinares e sindicâncias utilizando oficiais e praças lotados na própria Seção;', 'V - sugerir a nomeação de oficiais e praças lotados em outras unidades da Corporação, em caso de necessidade, como encarrega dos, escrivães e demais funções necessárias à condução dos processos administrativos disciplinares ou sindicâncias.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 99',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. XIV — Corregedoria',
            'caput': 'Art. 100. À Seção de Processos Administrativos de Responsabilidade Civil por Danos ao Erário, além das atribuições previstas no art. 79, compete:',
            'dispositivos': ['I - centralizar, instaurar, instruir e controlar os processos emanados das diversas OBMs, com vistas à apuração preliminar de responsabilidade civil por dano ao erário, bem como à propositura de instauração de Tomada de Contas Especial – TCE;', 'II - examinar a adequada formalização processual e a suficiência documental, as quais constituem elementos essenciais para a apuração preliminar de responsabilidade civil por dano ao erário e à propositura de instauração de TCE;', 'III - elaborar os documentos de competênci a do Comandante -Geral concernente a TCE, submetendo-os à análise e assinatura;', 'IV - fornecer subsídios para a elaboração de solução de recurso interposto, bem como do pronunciamento do Comandante-Geral, concernentes ao processo de TCE;', 'V - exercer estrito contr ole dos prazos com vistas à preparação processual e solicitação de instauração de TCE;', 'VI - verificar a adequada formalização e instrução processual, com vistas à eventual responsabilização do agente público ou terceiro alheio à administração pública que der causa injustificada a dano ao erário;', 'VII - solicitar às diversas OBMs a execução das diligências necessárias à instrução dos processos de apuração preliminar de responsabilidade civil por dano ao erário;', 'VIII - solicitar o ajuizamento de ação de ressarcimento quan do as apurações preliminares de responsabilidade civil por dano ao erário concluírem pela responsabilização de terceiro e este recusar-se a efetuar a devida regularização;', 'IX - propor a instauração de TCE quando as apurações preliminares de responsabilidade c ivil por dano ao erário concluírem pela responsabilização de agente público e este recusar -se a efetuar a devida regularização;', 'X - solicitar o ajuizamento de ação de ressarcimento quando a TCE concluir pela imputação de responsabilidade civil ao agente público e este não efetuar a devida regularização;', 'XI - acompanhar a tramitação dos processos com vistas à consecução judicial do ressarcimento pretendido;', 'XII - propor a instauração do devido processo legal nos casos em que, após análise em sede de apuração prelimin ar de responsabilidade civil e de TCE, for verificada a existência de indícios de cometimento de transgressão disciplinar ou crime militar;', 'XIII - sugerir a nomeação de oficiais e praças de outras OBMs como encarregados, membros de comissão tomadora de contas e demais funções relativas à condução dos processos de responsabilidade civil por danos ao erário, caso necessário.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 100',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. XIV — Corregedoria',
            'caput': 'Art. 101. À Seção de Acompanhamento Judicial e Extrajudicial de Pessoal, além das atribuições previstas no art. 79, compete:',
            'dispositivos': ['I - acompanhar an damentos de autos relativos a processos de militares denunciados na Justiça Criminal, autuados em flagrante delito ou indiciados em Inquérito Policial, por crime comum ou militar;', 'II - realizar leitura diária do Diário de Justiça Eletrônico, das publicações d os órgãos do Tribunal de Justiça do DF e Territórios e das cortes extraordinárias com a finalidade de obter dados e informações sobre militares que estejam respondendo a processo criminal, alimentando o banco de dados, para controle, bem como informando à DIGEP ou DINAP;', 'III - disponibilizar informações referentes à situação judicial de bombeiros militares, quando solicitado pelos órgãos da Corporação;', 'IV - manter atualizada a relação de militares que respondem a processos judiciais criminais na Auditoria Militar e nos demais órgãos da Justiça;', 'V - informar à Auditoria Militar a relação dos Oficiais aptos a participarem do sorteio para composição do Conselho Permanente e Especial de Justiça;', 'VI - viabilizar a apresentação de juízes militares e dos demais militares convocados pela Auditoria Militar;', 'VII - encaminhar ofícios de requisição de bombeiros militares, oriundos dos tribunais e demais órgãos, às organizações bombeiros militares nas quais estejam lotados, para a devida apresentação;', 'VIII - prestar informações à Justiça sobre dados cadastrais de militares, quando requisitado.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 101',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. XIV — Corregedoria',
            'caput': 'Art. 102. À Seção de Gerenciamento Processual e Cartorário, além das atribuições previstas no art. 79, compete:',
            'dispositivos': ['I - controlar as informações funcionais dos militares aptos a presidir procedimentos ou processos administrativos disciplinares, inclusive quanto à programação anual de férias, impedimentos e outros afastamentos;', 'II - coordenar e controlar o recebimento, a numeração, a autuação, o encaminhamento e a distribuição dos processos e demais documentos re metidos à Corregedoria, zelando pelo cumprimento dos prazos fixados;', 'III - coordenar e controlar o recebimento, a autuação, a protocolização e o encaminhamento de Processos Administrativos Disciplinares, Sindicâncias, Conselhos de Justificação e Disciplina, Inquéritos Policiais Militares e Licenciamento Disciplinar de Praça;', 'IV - acompanhar, controlar e registrar as publicações das matérias afetas aos documentos e processos tramitados na Corregedoria;', 'V - controlar o encaminhamento dos autos dos processos ou procedi mentos ao Tribunal de Justiça do Distrito Federal e aos demais órgãos do Poder Judiciário, Executivo ou Legislativo, nas esferas Distrital e Federal;', 'VI - elaborar relatórios estatísticos das atividades da Corregedoria;', 'VII - arquivar e administrar o arquivo de p rocessos administrativos disciplinares após o cumprimento da punição disciplinar ou o encerramento do feito, tanto em meio físico quanto digital. Das Competências Funcionais'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 102',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. XIV — Corregedoria',
            'caput': 'Art. 103. Ao Corregedor, além das atribuições previstas no art. 81, compete:',
            'dispositivos': ['I - zelar pela justiça e disciplina dos militares no CBMDF;', 'II - instaurar os processos e procedimentos administrativos relacionados à atividade correicional, sob as esferas de responsabilidade penal militar, civil e administrativo -disciplinar, no âmbito da Corporação;', 'III - solucionar os processos instaurados pela Corregedoria, bem como a reconsideração de ato interposta contra sua decisão;', 'IV - exercer autoridade de polícia judiciária militar no âmbito do CBMDF, nos termos da lei;', 'V - solicitar, sempre que conveniente para o processo apuratório, o afastamento de bombeiros militares acusados de crimes ou transgressões graves do exercício de suas funções ou solicitar a transferência para outras unidades;', 'VI - solucionar os processos apuratórios de responsabilidade ci vil por danos ao erário, homologando as composições administrativas que forem realizadas;', 'VII - acionar e supervisionar as atividades de escolta e custódia do NCUST.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 103',
            'match': 'exata',
        },
    ],
    ('ensino-instrucao', 'df'): [
        {
            'heading': 'TÍT. I, Cap. VII — Departamento de Ensino, Pesquisa, Ciência e Tecnologia',
            'caput': 'Art. 47. O Departamento de Ensino, Pesquisa, Ciência e Tecnologia – DEPCT possui a seguinte estrutura:',
            'dispositivos': ['I - Assessoria Técnico-Administrativa – ASTAD;', 'II - Seção de Apoio Administrativo – SEAAD.', 'Parágrafo único. O Museu Histórico – MUSEU subordina-se administrativa e operacionalmente ao DEPCT.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 47',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VII — Departamento de Ensino, Pesquisa, Ciência e Tecnologia',
            'caput': 'Art. 48. São órgãos de direção setorial subordinados ao DEPCT:',
            'dispositivos': ['I - Diretoria de Ensino – DIREN;', 'II - Diretoria de Pesquisa, Ciência e Tecnologia – DIREP;', 'III -Diretoria de Tecnologia da Informação e Comunicação – DITIC Das Competências Orgânicas'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 48',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VII — Departamento de Ensino, Pesquisa, Ciência e Tecnologia',
            'caput': 'Art. 49. Ao Departamento de Ensino, Pesquisa, Ciência e Tecnologia, além das atribuições constantes no art. 34, compete:',
            'dispositivos': ['I - planejar, orientar, coordenar e controlar as atividades relacionadas com:', 'a) formação, aperfeiçoamento, especialização e altos estudos de bombeiros militares;', 'b) ensino e pesquisa aplicada às atividades de bombeiro militar;', 'c) promoção do acesso à educação por meio de ensino militar;', 'd) desenvolvimento científico e tecnológico aplicado à profissão bombeiro militar;', 'e) modernização administrativa e operacional com o emprego das tecnologias de informação e comunicação;', 'f) capacitação continuada.', 'II - analisar e aprovar o Plano de Ensino, Pesquisa e Ciência da Corporação e o Plano Diretor de Tecnologia da Informação;', 'III - convocar à inspeção de saúde os militares candidatos à matrícula em cursos, estágios e situações afins.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 49',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VII — Departamento de Ensino, Pesquisa, Ciência e Tecnologia',
            'caput': 'Art. 50. Ao Museu Histórico compete: conservar, investigar, comunicar, interpretar e expor, para fins de preservação, estudo, pesquisa, educação, contemplação e turismo, acervo relativo ao patrimônio cultural do CBMDF. Das Competências Funcionais',
            'dispositivos': [],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 50',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VII — Departamento de Ensino, Pesquisa, Ciência e Tecnologia',
            'caput': 'Art. 51. Ao chefe do DEPCT, além das atribuições previstas no art. 37, compete:',
            'dispositivos': ['I - promover a modernização administrativa e operacional, mediante a capacitação profissional, o des envolvimento científico e tecnológico e o emprego de ferramentas da tecnologia de informação e comunicação;', 'II - homologar os editais de seleção aos cursos e estágios internos e externos;', 'III - designar e dispensar instrutores e monitores dos órgãos do sistema de ensino;', 'IV - determinar a quantidade de vagas em cursos e estágios a ser oferecidas a outras organizações militares;', 'V - aprovar mecanismos de controle, avaliação, capacitação e regras de ensino.', 'VI - analisar a indicação de bombeiros militares para cursos de pós -graduação e estágios técnico-científicos;', 'VII - homologar o Plano Diretor de Tecnologia da Informação e Comunicação da Corporação;', 'VIII - aprovar a política de segurança da informação e comunicação da Corporação;', 'IX - solucionar recursos contra decisões dos diretores subordinados.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 51',
            'match': 'exata',
        },
    ],
    ('pessoal-quadros', 'df'): [
        {
            'heading': 'TÍT. II, Cap. III — Diretoria de Inativos e Pensionistas',
            'caput': 'Art. 139. A Diretoria de Inativos e Pensionistas – DINAP possui a seguinte estrutura:',
            'dispositivos': ['I - Seção de Reserva e Reforma – SEREF;', 'II - Seção de Pensões Militares – SEPEM;', 'III - Seção de Pagamento de Inativos e Pensionistas – SEPAG;', 'IV - Seção de Recepção e Atendimento – SERAT;', 'V - Seção de Controle da Prestação de Tarefa por Tempo Certo – SECOT;', 'VI - Seção de Arquivo – SEARQ;', 'VII - Assessoria Técnica – ASTEC;', 'VIII -Seção de Apoio Administrativo – SEAAD. Das Competências Orgânicas'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 139',
            'match': 'parcial',
        },
        {
            'heading': 'TÍT. II, Cap. III — Diretoria de Inativos e Pensionistas',
            'caput': 'Art. 140. À Diretoria de Inativos e Pensionistas, além das atribuições constantes no art. 120, compete:',
            'dispositivos': ['I - instruir processos de concessão e revisão de reforma dos militares inativos e remetê-los aos órgãos de controle;', 'II - instruir processos de concessão e revisão de pensão militar e remetê-los aos órgãos de controle;', 'III - confeccionar, controlar, atualizar e fiscalizar a folha de pagamento do pessoal inativo e dos pensionistas;', 'IV - instruir processos para revisão de proventos;', 'V - promover a seleção e o chamamento de militares inativos para a prestação de tarefa por tempo certo;', 'VI - instruir processos de reconvocação de pessoal da reserva remunerada para o serviço ativo da Corporação;', 'VII - manter atualizados o cadastro e os registros funcionais dos militares inativos e pensionistas, por intermédio do recadastramento periódico;', 'VIII - promover o transporte ambulatorial eletivo de pessoal inativo, seus dependentes e pensionistas;', 'IX - instruir processos de inclusão e exclusão de dependentes de militares inativos e pensionistas. Art.141. À Seção de Reserva e Reforma, além das atribuições constantes no art. 121, compete:', 'I - analisar e instruir os processos de concessão de reserva remunerada e de reforma, para fins de inclusão na folha de pagamento e demais atos decorrentes;', 'II - instruir processos de convocação de pessoal da reserva remunerada para o serviço ativo da Corporação;', 'III - promover, anualmente, o chamamento à inspeção de saúde dos militares prestes a atingir a idade-limite de permanência na reserva remunerada;', 'IV - instruir processos de reforma por incapacidade e por atingimento de idade-limite na reserva remunerada;', 'V - cadastrar os processos de reforma ou de melhoria de reforma no sistema próprio do TCDF;', 'VI - promover o chamamento dos militares reformados que percebam o benefício auxílio- invalidez à inspeção de saúde de controle;', 'VII - notificar inativos acerca de decisão que demande alteração pecuniária.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 140',
            'match': 'parcial',
        },
        {
            'heading': 'TÍT. II, Cap. III — Diretoria de Inativos e Pensionistas',
            'caput': 'Art. 142. À Seção de Pensões Militares, além das atribuições constantes no art. 121, compete:',
            'dispositivos': ['I - analisar e instruir os processos relativos a pensões militares;', 'II - cadastrar os processos de pensão militar no sistema próprio do TCDF;', 'III - notificar pensionistas acerca de decisão que demande alteração pecuniária.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 142',
            'match': 'parcial',
        },
        {
            'heading': 'TÍT. II, Cap. III — Diretoria de Inativos e Pensionistas',
            'caput': 'Art. 143. À Seção de Pagamento, além das atribuições constantes no art. 121, compete:',
            'dispositivos': ['I - elaborar e controlar a folha de pagamento dos militares inativos e dos pensionistas;', 'II - gerenciar os dados dos militares inativos e dos pensionistas nos sistemas de gestão de folha de pagamento dos governos federal e distrital;', 'III - cadastrar, excluir e atualizar pensões alimentícias e demais descontos na folha de pagamento de militares inativos e de pensionistas, por determinação judicial;', 'IV - disponibilizar as fichas financeiras de militares inativos e de pensionistas;', 'V - apurar dívidas de exercícios anteriores para reconhecimento pela autoridade competente e respectivo pagamento;', 'VI - manter arquivados os documentos que ensejam lançamentos na folha de pagamento, observada a tabela de temporalidade;', 'VII - atestar a execução de desconto em folha de pagamento dos inativos e pensionistas, a título de indenização ou ressarcimento devido à Fazenda Nacional;', 'VIII - realizar o cálculo do impacto financeiro decorrente de nomeações de militares para a Prestação de Tarefa por Tempo Certo – PTTC;', 'IX - realizar os cálculos e pagamentos das indenizações por ocasião da passagem do militar para a inatividade;', 'X - atualizar, anualmente, o saldo devedor dos descontos realizados em folha de pagamento dos inativos e pensionistas, nos termos da legislação em vigor;', 'XI - elaborar a proposta orçamentária anual das despesas com folha de pagamento dos militares inativos e pensionistas', 'XII - providenciar as informações concernentes à DINAP para confecção dos relatórios de prestação de contas anual da Corporação ao Tribunal de Contas da União e ao Tribunal de Contas do Distrito Federal;', 'XIII - realizar os cálculos e pagamentos das indenizações devidas por oca sião da exoneração ou término do período de nomeação para a PTTC.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 143',
            'match': 'parcial',
        },
        {
            'heading': 'TÍT. II, Cap. III — Diretoria de Inativos e Pensionistas',
            'caput': 'Art. 144. À Seção de Recepção e Atendimento, além das atribuições constantes no art.121, compete:',
            'dispositivos': ['I - realizar o acolhimento e o atendimento inicial aos inativos e pensionistas;', 'II - gerenciar o serviço de transporte ambulatorial eletivo aos militares inativos, dependentes e pensionistas militares.', 'III - instruir processos relativos a:', 'a) inclusão, permanência e exclusão do rol de dependentes;', 'b) adicional de pensão militar;', 'c) concessão de auxílio natalidade, auxílio pré-escolar e auxílio funeral;', 'd) ajuste do Fundo de Saúde.', 'IV - manter atualizadas as informações relativas aos inativos, pensionistas e dependentes nos sistemas de gestão de pessoal do CBMDF;', 'V - gerenciar relatórios do sistema de controle para fins de manutenção ou exclusão do rol de dependentes.', 'VI - prestar atendimento ao público pelos canais de comunicação disponíveis;', 'VII - realizar desbloqueio de acesso ao Sistema de Gestão de Acesso - SIGAC ou outro que o substitua;', 'VIII - recadastrar periodicamente os militares inativos e pensionistas do CBMDF;', 'IX - instruir processos relativos a ressarcimento ao erário oriundos de inconsistências apuradas no recadastramento, conforme legislação vigente;', 'X - notificar os militares inativos e pensionistas a respeito de alterações cadastrais e financeiras;', 'XI - realizar as diligências necessárias a fim de apurar os motivos da não realização de recadastramento por parte de militar inativo ou pensionista;', 'XII - receber e processar críticas e sugestões dirigidas à DINAP.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 144',
            'match': 'parcial',
        },
        {
            'heading': 'TÍT. II, Cap. III — Diretoria de Inativos e Pensionistas',
            'caput': 'Art. 145. À Seção de Controle da Prestação de Tarefa por Tempo Certo, além das atribuições constantes no art. 121, compete:',
            'dispositivos': ['I - manter atualizado o cadastro de militares inativos inscritos para a PTTC;', 'II - instruir os processos de seleção, chamamento e nomeação para o exercício da PTTC;', 'III - exercer o controle de frequência dos militares nomeados visando instruir os processos de pagamento;', 'IV - instruir processos de exoneração de militares nomeados;', 'V - instruir processos de concessão, alteração, remarcação, retificação e cancelamento dos afastamentos abaixo relacionados aos militares nomeados:', 'a) férias regulamentares;', 'b) férias radiológicas;', 'c) dispensa do serviço para desconto em férias;', 'd) abono anual.', 'VI - controlar os afastamentos discriminados no inciso V;', 'VII - organizar e disponibilizar o Plano de Férias Anual dos militares nomeados para a PTTC;', 'VIII - manter atualizado o sistema de controle dos afastamentos.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 145',
            'match': 'parcial',
        },
        {
            'heading': 'TÍT. II, Cap. III — Diretoria de Inativos e Pensionistas',
            'caput': 'Art. 146. À Seção de Arquivo, além das atribuições constantes no art. 121, compete:',
            'dispositivos': ['I - manter os dossiês dos inativos e pensionistas atualizados;', 'II - organizar e conservar o arquivo de dossiês;', 'III - encaminhar à DIGEP o dossiê do militar que retornar ao serviço ativo;', 'IV - manter arquivados os dossiês dos militares falecidos e ex-pensionistas, observada a tabela de temporalidade;', 'V - manter os assentamentos dos militares inativos, dependentes e pensionistas atualizados com as publicações dos meios oficiais;', 'VI - disponibilizar acesso aos dossiês, observando as hipóteses legais de sigilo.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 146',
            'match': 'parcial',
        },
        {
            'heading': 'TÍT. II, Cap. III — Diretoria de Inativos e Pensionistas',
            'caput': 'Art. 147. À Assessoria Técnica, além das atribuições constantes no art. 121, compete:',
            'dispositivos': ['I - assessorar o diretor no planejamento, orientação e coordenação das atividades da diretoria;', 'II - prestar assessoramento técnico ao diretor sobre questões que lhe forem afetas;', 'III - assessorar o diretor em assuntos de natureza disciplinar e correicional;', 'IV - realizar estudos, pesquisas, análise de legalidade e minutar atos visando subsidiar o diretor na tomada de decisão;', 'V - examinar processos administrativos, decisões judiciais, demandas que extrapolem a competência das seções e outros atos afetos ao diretor e subdiretor;', 'VI - analisar minutas de atos normativos propostos pelos setores da diretoria.', 'Parágrafo único. Poderá ser produzida manifestação jurídica assinada por oficial, bacharel em direito, no âmbito da Assessoria Técnica, em matéria administrativa exclusiva da DINAP, a qual será submetida à Cota de Aprovação da chefia da ASJUR como condição de eficácia.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 147',
            'match': 'parcial',
        },
        {
            'heading': 'TÍT. II, Cap. III — Diretoria de Inativos e Pensionistas',
            'caput': 'Art. 148. À Seção de Apoio Administrativo da DINAP, além das atribuições constantes no art. 121, compete:',
            'dispositivos': ['I - instruir processos relacionados a:', 'a) cancelamento de registro de punição, mediante requerimento do inativo interessado;', 'b) cumprimento de punição;', 'c) apresentação de militar à Justiça e aos encarregados de procedimentos apuratórios.', 'II - prover o suporte logístico necessário à execução das atividades da diretoria;', 'III - elaborar e acompanhar a tramitação dos pedidos de aquisição de materiais e de execução de serviços relativos à área de atuação da DINAP. Das Competências Funcionais'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 148',
            'match': 'parcial',
        },
        {
            'heading': 'TÍT. II, Cap. III — Diretoria de Inativos e Pensionistas',
            'caput': 'Art. 149. Ao Diretor de Inativos e Pensionistas, além das atribui ções previstas no art. 123, compete gerir a folha de pagamento do pessoal inativo e dos pensionistas, ressalvada a competência da DIOFI quanto à liquidação e pagamento.',
            'dispositivos': [],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 149',
            'match': 'parcial',
        },
        {
            'heading': 'TÍT. II, Cap. III — Diretoria de Inativos e Pensionistas',
            'caput': 'Art. 150. Ao Subdiretor de Inativos e Pensionistas, além das atribuições previstas no art. 124, compete gerenciar as atividades relacionadas a suprimentos de fundos.',
            'dispositivos': ['Parágrafo único. O Subdiretor da Diretoria de Inativos e Pensionistas exercerá, cumulativamente, a Chefia da Seção de Reserva e Reforma. (NOVA REDAÇÃO DADA PELA EMENDA REGIMENTAL Nº 03, DE 2025.)'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 150',
            'match': 'parcial',
        },
        {
            'heading': 'TÍT. II, Cap. III — Diretoria de Inativos e Pensionistas',
            'caput': 'Art. 151. Ao chefe da SEPAG, além das atribuições constantes no art. 125, compete atestar a execução de descontos em processos administrativos ou documentos.',
            'dispositivos': [],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 151',
            'match': 'parcial',
        },
    ],
    ('seguranca-contra-incendio', 'df'): [
        {
            'heading': 'TÍT. I, Cap. VIII — Departamento de Segurança Contra Incêndio',
            'caput': 'Art. 52. O Departamento de Segurança Contra Incêndio – DESEG possui a seguinte estrutura:',
            'dispositivos': ['I - Assessoria Técnico-Administrativa – ASTAD;', 'II - Seção de Apoio Administrativo – SEAAD.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 52',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VIII — Departamento de Segurança Contra Incêndio',
            'caput': 'Art. 53. São órgãos de direção setorial subordinados ao DESEG:',
            'dispositivos': ['I - Diretoria de Vistorias – DIVIS;', 'II - Diretoria de Estudos e Análise de Projetos – DIEAP;', 'III - Diretoria de Investigação de Incêndio – DINVI. Das Competências Orgânicas'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 53',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VIII — Departamento de Segurança Contra Incêndio',
            'caput': 'Art. 54. Ao Departamento de Segurança Contra Incêndio, além das atribuições previstas no art. 34, compete:',
            'dispositivos': ['I - realizar atividades de segurança contra incêndio e pânico, com vistas à proteção das pessoas e dos bens públicos e privados;', 'II - realizar perícias em incêndio e explosões;', 'III - planejar, orientar, coordenar e controlar as atividades de segurança contra incêndio e pânico relacionadas a:', 'a) credenciamento e fiscalização;', 'b) serviço de hidrante urbano;', 'c) proposição de normas, programas e diretrizes;', 'd) análise de projetos de instalações de proteção contra incêndio e pânico e de arquitetura;', 'e) prevenção e proteção contra incêndio e pânico;', 'f) investigação de incêndios.', 'IV - promover e participar de campanhas educativas direcionadas à comunidade em sua área de atuação;', 'V - realizar pesquisas técnico-científicas, com vistas à obtenção de produtos e processos, que permitam o desenvolvimento de sistemas de segurança contra incêndio e pânico;', 'VI - fiscalizar, na área de sua competência, o cumprimento da legislação referente à prevenção contra incêndio e pânico;', 'VII - realizar vistorias e emitir pareceres técnicos com possíveis consequências de penalidades por infração, na forma da legislação específica;', 'VIII - credenciar os agentes fiscalizadores para realizar as vistorias técnicas.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 54',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VIII — Departamento de Segurança Contra Incêndio',
            'caput': 'Art. 55. À Assessoria Técnico-Administrativa do DESEG, além das atribuições previstas no art. 35, compete:',
            'dispositivos': ['I - fomentar atividades de ensino relacionadas à atividade de segurança contra incêndio aos militares do DESEG;', 'II - propor a realização de pesquisa técnico -científica com vistas à obtenção de produtos e processos que permitam o desenvolvimento do sistema de segurança contra incêndio e pânico. Das Competências Funcionais'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 55',
            'match': 'exata',
        },
        {
            'heading': 'TÍT. I, Cap. VIII — Departamento de Segurança Contra Incêndio',
            'caput': 'Art. 56. Ao chefe do DESEG, além das atribuições previstas no art. 37, compete:',
            'dispositivos': ['I - planejar e orientar as atividades de segurança contra incêndio e pânico;', 'II - tratar questões de grande repercussão relativas à segurança contra incêndio e pânico;', 'III - homologar plano de ação de fiscalização conjunta com o Comando Operacional;', 'IV - presidir o Conselho do Sistema de Engenharia de Segurança Contra Incêndio e Pânico;', 'V - credenciar os agentes fiscalizadores para realizar as vistorias técnicas;', 'VI - solucionar recursos contra decisões dos diretores subordinados.'],
            'source': 'cf. CBMDF, RI (Portaria nº 24/2020), Art. 56',
            'match': 'exata',
        },
    ],
}
