# GERADO por scripts/extrair_regulamentos.py — NÃO editar à mão.
# Fonte: Tocantins - Regulamento de Serviço.md (extração determinística; mapa nos de-paras).
ENRICHMENT = {
    ('central-operacoes-193', 'to'): [
        {
            'heading': 'NGA SIOP (Anexo 2) — Coordenador de Operações, Despachante e Atendente',
            'caput': 'Art. 12 É o Oficial Superior ou Oficial Intermediário responsável pela coordenação do serviço operacional do SIOP/BM, e tem como principais atribuições:',
            'dispositivos': ['I – Conferir, testar e zelar pelos equipamentos e materiais de sua responsabilidade;', 'II – Permanecer nas dependências do SIOP durante o serviço;', 'III – Autorizar a saída temporária do efetivo do Serviço Operacional do SIOP/BM;', 'IV – Fiscalizar o efetivo do serviço operacional do SIOP/BM;', 'V – Conferir o lançamento dos relatórios de ocorrências das UBM’s do CBMTO;', 'VI – Acionar o Oficial de Área da capital atendimento às ocorrências;', 'VII – Realizar o contato com os Oficiais de Área e/ou Comandante s de Socorro das UBM’s do CBMTO para detalhamento de informações sobre ocorrências, ordens de serviço, simulados, etc.;', 'VIII – Coordenar as ocorrências de médio e grande vulto, principalmente com o acionamento de órgãos externos para provimento de recursos adicionais a fim contribuir para solução de uma situação emergencial;', 'IX – Repassar informações e demandas operacionais ao Superior de Dia, Gerente do SIOP/BM e/ou Comandante Operacional;', 'X – Registrar em Parte Diária as ações e alterações do serviço exec utado e encaminhá -la ao Gerente do SIOP/BM. Parágrafo Único. Quando da ausência do Coordenador de Operações, o Oficial de Área'],
            'source': 'cf. CBMTO, NGA do SIOP (Diretriz COB, Portaria nº 003/2019), Art. 12',
            'match': 'exata',
        },
        {
            'heading': 'NGA SIOP (Anexo 2) — Coordenador de Operações, Despachante e Atendente',
            'caput': 'Art. 13 É o Praça mais antigo que compõe o serviço operacional, com a responsabilidade principal de estabelecer a comunicação entre o SIOP/BM e o efetivo operacional, e a ele compete as seguintes atribuições:',
            'dispositivos': ['I – Conferir, testar e zelar pelos equipamentos e materiais de sua responsabilidade;', 'II – Permanecer nas dependências do SIOP durante o serviço;', 'III – Comunicar ao Coordenador de Operações as ações e alterações no decorrer de seu serviço;', 'IV – Receber as informações do Atendente e providenciar o despacho de viaturas e efetivo condizente a cada situação emergencial;', 'V – Monitorar as viaturas do serviço operacional do dia;', 'VI – Acionar o Oficial de Área da capital quando da ausência do Coordenador de Operações;', 'VII – Fiscalizar as atividades do(s) Atendente(s), bem como período de sua ausência, quando autorizada pelo Oficial de Área;', 'VIII – Acionar a s guarnições correspondentes para cumprimento das Ordens de Serviço previstas;', 'IX – Monitorar as ocorrências em andamento e fazer o repasse de informações ao Coordenador de Operações e/ou Oficial de Área;', 'X – Registrar os dados referentes ao controle de at endimento às ocorrências, como horários, quilometragens, etc.;', 'XI – Por necessidade do serviço, o Despachante pode acumular momentaneamente a função de Atendente;', 'XII – Conferir se os relatórios das ocorrências estão na conformidade do sistema virtual de registros;', '§ 1º O Despachante deve subordinação administrativa ao Gerente do SIOP/BM e deve encaminhar ao mesmo os problemas administrativos e logísticos que encontrar no desempenho de sua função.', '§ 2º O Despachante tem direito à prática de Treinamento Físi co Militar junto ao efetivo do 1º BBM em período de até uma hora, desde que sem prejuízo ao seu serviço operacional.', '§3º O Despachante poderá se ausentar por até 30 (trinta) minutos para providenciar sua refeição, desde que sem prejuízo ao seu serviço oper acional e com prévia autorização do Coordenador de Operações ou do Oficial de Área e informe dos horários de saída e retorno.'],
            'source': 'cf. CBMTO, NGA do SIOP (Diretriz COB, Portaria nº 003/2019), Art. 13',
            'match': 'exata',
        },
        {
            'heading': 'NGA SIOP (Anexo 2) — Coordenador de Operações, Despachante e Atendente',
            'caput': 'Art. 14 Praça(s) que compõem(m) o serviço operacional, com a responsabilidade principal de atendimento às ligações da COCB, e a ele compete as seguintes atribuições:',
            'dispositivos': ['I – Conferir, testar e zelar pelos equipamentos e materiais de sua responsabilidade;', 'II – Permanecer nas dependências do SIOP durante o serviço;', 'III – Comunicar ao Despachante as ações e alterações no decorrer de seu serviço;', 'IV – Comunicar-se com o solicitante para coleta e/ou repasse de informações gerais e específicas;', 'V – Iniciar o registro da ocorrência no software disponibilizado, bem como providenciar as informações associadas;', 'VI – Ofertar suporte profissional ao Despachante para o atendimento à situação emergencial;', 'VII – Por necessidade do serviço, o Atendente pode acumular momentaneamente a função de Despachante;', 'VIII – Providenciar o relatório de ocorrências, tão quanto necessário;', '§ 1º O Atend ente deve subordinação administrativa ao Gerente do SIOP/BM e deve encaminhar ao mesmo, via Despachante, os problemas administrativos e logísticos que encontrar no desempenho de sua função.', '§ 2º O Atendente tem direito à prática de Treinamento Físico Milit ar junto ao efetivo do 1º BBM em período de até uma hora, desde que sem prejuízo ao seu serviço operacional.', '§3º O Atendente poderá se ausentar por até 30 (trinta) minutos para providenciar sua refeição, desde que sem prejuízo ao seu serviço operacional e com prévia autorização do Coordenador de Operações ou do Oficial de Área e informe dos horários de saída e retorno.'],
            'source': 'cf. CBMTO, NGA do SIOP (Diretriz COB, Portaria nº 003/2019), Art. 14',
            'match': 'exata',
        },
    ],
}
